### ISSUE TITLE
Option to automatically delete source maps after upload

### ISSUE THREAD

**Issue by YaYaPao** [getsentry/sentry-javascript-bundler-plugins#147]
For security purposes, we should not expose sourcemaps online. So a `cleanSourceMaps` configuration is good to autodelete sourcemaps after artifacts has been uploaded successfully.

**Comment by lforst** [comment]
We thought about adding this before in the webpack plugin we already had. For now, we consider this a bit out of scope as you can just delete source maps yourself after your build is complete and there is always the challenge for the Sentry plugin to know which files to delete - is it just the ones that the plugin uploaded or also the rest? Just some things to consider.

I will leave this issue open as it is a valid feature to think about.

**Comment by wtachau** [comment]
Here's what I ended up doing to delete sourcemaps after uploading (in the build script):
```sh
find <output dir> -type f -name '*.js.map' -delete
find <output dir> -type f -name '*.css.map' -delete
find <output dir> -type f -name '*.js' -exec sed -i -E 's/sourceMappingURL=[^ ]*\.js\.map//g' {} +
find <output dir> -type f -name '*.css' -exec sed -i -E 's/sourceMappingURL=[^ ]*\.css\.map//g' {} +
```

**Comment by kricsleo** [comment]
Deleting sourcemaps also means a lot to me. I prefer to delete all of them before deployment. If someone wants to keep them, they can disable this config and do the job as they want. But in most cases, deleting all sourcemaps would be a more common use case.

**Comment by filiptammergard** [comment]
Nice @lforst! Can you please announce here when `deleteFilesAfterUpload` is available to use, and how to use it?

**Comment by lforst** [comment]
@filiptammergard I hope I don't forget :D

**Comment by lforst** [comment]
We released this in the newest version of the plugin! :)

**Comment by filiptammergard** [comment]
@lforst Nice! Any documentation on how to you it? Is the glob relative to project root or relative to built folder?

**Comment by lforst** [comment]
@filiptammergard Docs are on the npm page of the plugin you're using. The globs are relative to cwd by default.

**Comment by filiptammergard** [comment]
> @lforst where are the docs? Sorry - been searching for them for a bit - can't find them.

As @lforst said you can find the docs on NPM for the plugin you're using. For example here: https://www.npmjs.com/package/@sentry/vite-plugin

**Comment by meotimdihia** [comment]
@filiptammergard I can't find it too: 

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/300961/c93255b4-753b-4916-b56a-0fbfc69dcc63)

**Comment by lforst** [comment]
@meotimdihia These are the SDK docs. The plugin docs are located here [npmjs.com/package/@sentry/vite-plugin](https://www.npmjs.com/package/@sentry/vite-plugin)

**Comment by meotimdihia** [comment]
@lforst I just use `@sentry/nextjs`  and a simple `next build` command then can't I still do this?
