### ISSUE TITLE
Getting inconsistently failing builds using vite-plugin and Vercel

### ISSUE THREAD

**Issue by hardyjosh** [getsentry/sentry-javascript-bundler-plugins#159]
### Environment

```
"@sentry/vite-plugin": "^0.3.0",
"vite": "^3.1.0",
"@sentry/node": "^7.27.0",
"@sentry/svelte": "^7.26.0",
"@sentry/tracing": "^7.26.0",
```

### Steps to Reproduce

1. Add the plugin to Vite per these instructions https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/vite/
2. Build using Vercel

### Expected Result

Sourcemaps would be uploaded and releases automatically created in Sentry, with no other side-effects.

### Actual Result

I'm getting inconsistently failing builds in Vercel with this error:

```
Error: spawn /vercel/path0/node_modules/@sentry/cli/sentry-cli ENOENT
--
15:30:52.098 | at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
15:30:52.098 | at onErrorNT (node:internal/child_process:485:16)
15:30:52.098 | at processTicksAndRejections (node:internal/process/task_queues:83:21) {
15:30:52.098 | errno: -2,
15:30:52.098 | code: 'ENOENT',
15:30:52.098 | syscall: 'spawn /vercel/path0/node_modules/@sentry/cli/sentry-cli',
15:30:52.098 | path: '/vercel/path0/node_modules/@sentry/cli/sentry-cli',
15:30:52.098 | spawnargs: [ 'releases', 'propose-version' ],
15:30:52.098 | cmd: '/vercel/path0/node_modules/@sentry/cli/sentry-cli releases propose-version'
15:30:52.098 | }

```

This doesn't happen every time. I can redeploy the same commit in Vercel and it will work 1 out of every 3 times.

**Comment by lforst** [comment]
Hi, thanks for writing in about this. The build failing non-deterministically seems very weird to me but we had issues with Sentry CLI + Vercel before. Is there anything else in the build logs worth sharing?

**Comment by raethlo** [comment]
Hey all 👋🏻  we are experiencing the same issue and there is not much to go after. @hardyjosh any chance you figured out what the issue was?

Our sentry package versions:
```
"@sentry/react": "^7.50.0",
"@sentry/tracing": "^7.50.0",
"@sentry/vite-plugin": "0.7.2",
```

The log from vercel build:
```
[sentry-vite-plugin] Info: Sending error and performance telemetry data to Sentry.
--
13:09:43.770 | [sentry-vite-plugin] Info: To disable telemetry, set `options.telemetry` to `false`.
13:09:43.772 | ✓ 0 modules transformed.
13:09:43.772 | [sentry-plugin] spawn /vercel/path0/node_modules/.pnpm/@sentry+cli@2.17.5/node_modules/@sentry/cli/sentry-cli ENOENT
13:09:43.772 | error during build:
13:09:43.772 | Error: spawn /vercel/path0/node_modules/.pnpm/@sentry+cli@2.17.5/node_modules/@sentry/cli/sentry-cli ENOENT
13:09:43.772 | at ChildProcess._handle.onexit (node:internal/child_process:283:19)
13:09:43.772 | at onErrorNT (node:internal/child_process:476:16)
13:09:43.773 | at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
13:09:43.780 | ELIFECYCLE  Command failed with exit code 1.
13:09:43.803 | Error: Command "pnpm build && pnpm run sourcemaps:clear" exited with 1
13:09:44.548 | Deployment completed
13:09:44.157 | BUILD_UTILS_SPAWN_1: Command "pnpm build && pnpm run sourcemaps:clear" exited with 1
```

Okay now that I've put this together, I have actually noticed the part that seems wrong 
> 13:09:43.772 | ✓ 0 modules transformed.  
Healthy builds do have a non-zero number there as well as  additional logs + rebuild on a deployment that is failing this way seems to produce a healthy build again.

**Comment by lforst** [comment]
Hmm I assume this is somehow related to the build cache. The Sentry CLI binary, which can't be found here, is installed via a post-install script (trust me I don't like this but fixing this is gonna take a while) and maybe the binary isn't stored across builds.

Maybe it's related to https://github.com/pnpm/pnpm/issues/4649 and is solved by setting `side-effects-cache=false` in pnpm?

**Comment by raethlo** [comment]
Hmm, yeah, the symptoms are similar to https://github.com/pnpm/pnpm/issues/4649 I'll try some of the fixes that people mentioned in the comments and I'll report back. Worst case I guess a hacky fix could be to somehow always install `@sentry/cli` fresh 🤔
