### ISSUE TITLE
sentryEsbuildPlugin is not a function

### ISSUE THREAD

**Issue by senordelaflor** [getsentry/sentry-javascript-bundler-plugins#161]
### Environment

Sentry esbuild plugin version 0.3.0 run on esbuild 0.16.12 

### Steps to Reproduce
Followed the usage guide in https://github.com/getsentry/sentry-javascript-bundler-plugins/tree/main/packages/esbuild-plugin
```JS
// esbuild.config.js
const sentryEsbuildPlugin = require("@sentry/esbuild-plugin");

require("esbuild").build({
  plugins: [
    sentryEsbuildPlugin({
      include: ".",
      ignore: ["node_modules", "esbuild.config.js"],
      org: process.env.SENTRY_ORG,
      project: process.env.SENTRY_PROJECT,
      authToken: process.env.SENTRY_AUTH_TOKEN,
    }),
  ],
});
```

### Expected Result

Sentry plugin would run

### Actual Result

It broke the build with error `TypeError: sentryEsbuildPlugin is not a function`

![image](https://user-images.githubusercontent.com/10679537/212160721-402d7307-37a4-455c-99e6-0bf63a48c614.png)

**Comment by lforst** [comment]
Hi @senordelaflor can you console.log `sentryEsbuildPlugin` and share what it prints?

**Comment by senordelaflor** [comment]
@lforst This is what prints for `sentryEsbuildPlugin`:
```JS
{ default: [Getter] }
```

**Comment by Lilja** [comment]
I got the same error, I worked around by `sentryEsbuildPlugin.default({...})`

**Comment by lforst** [comment]
Yeah this is something we gotta fix. Thanks for letting us know! Stupid little oversight. We'll likely change the default export to a named export before we promote the package to a stable version.
