### ISSUE TITLE
Provide option to delete source maps after upload

### ISSUE THREAD

**Issue by SassNinja** [getsentry/sentry-javascript-bundler-plugins#172]
I've just started implementing sentry using the [JavaScript SDK](https://docs.sentry.io/platforms/javascript/)

Next I've tried to upload source maps using this webpack plugin. In the course of it I obviously had to generate sourcemaps for my production build and was wondering: how do I prevent those files from being deployed (which would mean revealing all source code)

I was quite surprised there's nothing built-in this webpack plugin because it's a major security concern! As I can see there's an old issue about this topic which has been closed: https://github.com/getsentry/sentry-webpack-plugin/issues/56

The mentioned solutions can be used though it feels more like a workaround. It was also mentioned that a custom webpack plugin might be an option and my immediate thought was: "why is it not part of this plugin?"

A simple option could be "deleteSourceMaps" which would delete all uploaded source maps at the end of the build process. Even if the underlying sentry-cli doesn't support this, it shouldn't be difficult to extend this webpack plugin.

Are there any reasons not to do this?

**Comment by meotimdihia** [comment]
Please support this feature. Workarounds are confusing and don't work for me.

**Comment by SassNinja** [comment]
@AbhiPrasad I'm glad to hear you're open for re-evaluation 

>  could lead to files being deleted accidentally

I would set this new option to default `false` so that you explicitly need to enable it. This would prevent any unintended behaviour as the logic is quite clear: delete all source maps that have been uploaded at the end of the build process.

**Comment by SassNinja** [comment]
@lforst yes that's true and intuitive in my opinion

The new option would only delete what's uploaded by the plugin. So if you only upload subset of your source maps, only those files will be deleted afterwards.

The right option name could emphasise this (e.g. "deleteSourceMapsAfterUpload" or "deleteUploadedSourceMaps") so that hardly anyone would expect all source maps get deleted when only a subset is uploaded. I think some documentation would help to avoid any confusion.

**Comment by AbhiPrasad** [comment]
> deleteUploadedSourceMaps

I think an option named like this is reasonable, it'll require us to make changes to `sentry-cli` though, since the JS layer doesn't get this info iirc.

We can make this `false` by default, and then evaluate turning it on based on further user feedback. @lforst what do you think?

**Comment by BrianHung** [comment]
Would love this feature to be included in the vite plugin as well!

**Comment by ethubert** [comment]
Any news on this? Or do we need to have some pipeline scripts for that?

**Comment by lforst** [comment]
Resolved with #244

**Comment by lforst** [comment]
We released this in the newest version of the plugin btw :)
