### ISSUE TITLE
@sentry/vite-plugin"' has no exported member 'sentryVitePlugin'

### ISSUE THREAD

**Issue by victorlmneves** [getsentry/sentry-javascript-bundler-plugins#177]
After updating @sentry/vite-plugin from version 0.3.0 to 0.4.0 I get this error
`Module '"@sentry/vite-plugin"' has no exported member 'sentryVitePlugin'. Did you mean to use 'import sentryVitePlugin from "@sentry/vite-plugin"' instead?`

Based on your documentation we should use it like this
`import { sentryVitePlugin } from '@sentry/vite-plugin';`

But if Import it like this (as suggested by the VS Code), I don't get the error/warning but when running the app it throws an error while the other one works fine
`import sentryVitePlugin from '@sentry/vite-plugin';`

### Expected Result

Everything should work perfectly 

### Actual Result

It complaines saying that ``Module '"@sentry/vite-plugin"' has no exported member 'sentryVitePlugin'. Did you mean to use 'import sentryVitePlugin from "@sentry/vite-plugin"' instead?``

**Comment by lforst** [comment]
Hi, this is the plugin is exported like this: https://unpkg.com/browse/@sentry/vite-plugin@0.4.0/dist/esm/index.mjs

Can you delete your node_modules, reinstall them and try again? It seems like something weird is going on.

**Comment by victorlmneves** [comment]
@lforst 
Hi, already did it and I still get the warning, but I have updated last night on a personal project and it doesn't complain.
So probably it's some settings that I have on the project that is causing that.

Thanks

**Comment by victorlmneves** [comment]
Now I remember
There is a difference between the projects, on the one I get the warning we are using ECMAScript Modules. Could this be the reason? But looking at the way it is exported it also uses ECMAScript Modules, right?

**Comment by lforst** [comment]
> Now I remember There is a difference between the projects, on the one I get the warning we are using ECMAScript Modules. Could this be the reason? But looking at the way it is exported it also uses ECMAScript Modules, right?

You should be able to use both ES modules and CJS modules without any issues. The file I shared is esm.

**Comment by Ghirigoro** [comment]
I am also having this issue. This is the first time I've used the plugin so it can't be stale node modules, and I've tried changing my project from ESM to CJS and back and neither worked.

**Comment by lforst** [comment]
Can any of you provide a repro example we can pull to debug this further? A stackblitz or something like that would also work.
