### ISSUE TITLE
Entrypoint source map has 10 extra lines due to @sentry/esbuild-plugin

### ISSUE THREAD

**Issue by jiangzhuo** [getsentry/sentry-javascript-bundler-plugins#179]
Hello,

I'm currently working on a Node.js lambda project written in TypeScript. I'm using the @sentry/esbuild-plugin to upload source maps to Sentry. While I can successfully view the source code on Sentry, I've noticed that the entrypoint source map has 10 extra lines, causing the line numbers in Sentry to not match the line numbers in my GitHub repo.

After investigating, I found that the extra lines are generated by the following code inserted by @sentry/esbuild-plugin during the transform process:
https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/97a2a2f7e72b19aade44d008a55ee5a8490c51b1/packages/bundler-plugin-core/src/index.ts#L351-L361

However, since I'm explicitly setting the release in my code when I use Sentry and I'm aware that I'm running in a lambda environment, I don't really need this piece of code.

I'm wondering if there's a way to address the line number mismatch issue, such as adding a switch to skip the generateGlobalInjectorCode function.

Thanks!

**Comment by lforst** [comment]
Hi, you can set `releaseInjectionTargets: []` like this in order to skip the release injection process.

**Comment by jiangzhuo** [comment]
@lforst Thank you very much.
