### ISSUE TITLE
Release injection not working with @sentry/plugin-vite

### ISSUE THREAD

**Issue by dd-jonas** [getsentry/sentry-javascript-bundler-plugins#180]
### Environment

- `vite @4.1.4`
- `@sentry/vite-plugin @0.4.0`

### Steps to Reproduce

1. Add Sentry plugin in `vite.config.ts`
1. Run `vite build` to trigger a Sentry release
1. Run `vite preview`
1. Log `SENTRY_RELEASE` in the Chrome devtools console

### Expected Result

`{ id: "abc123" }`

### Actual Result

`Uncaught ReferenceError: SENTRY_RELEASE is not defined`

### Additional info

I did some debugging and it looks like the index.html file is seen as the entry point of the application. This means that the `transformInclude` function will not include any file as the .html extension is not valid, which means the transform hook won't get called at all and no release id is injected. Not sure what the reason is why the index.html is the entry point. Currently working around this by using `releaseInjectionTargets: /src\/index\.tsx$/`.

**Comment by andrey-hohlov** [comment]
https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/178#issuecomment-1440741634

**Comment by dd-jonas** [comment]
Cool, good to know that `releaseInjectionTargets` is the recommended way of handling this

**Comment by lforst** [comment]
I thought of a way to fix release injection for this use case but I won't get to it for a while. Give or take a month.

In the meanwhile `releaseInjectionTargets` is definitely the way to go.
