### ISSUE TITLE
Error: A release slug is required (provide with --release)

### ISSUE THREAD

**Issue by todsul** [getsentry/sentry-javascript-bundler-plugins#181]
### Environment

"@sentry/vite-plugin": "^0.4.0"
"vite": "^4.1.4"

### Steps to Reproduce

Both including or excluding "release" in the config produces the error. The default config suggests removing "release" and allow it to detect release name. // Optionally uncomment the line below to override automatic release name detection

sentryVitePlugin({
  org: "org",
  project: "project",
  include: "./dist",
  authToken: "xxx",
}),

or...

sentryVitePlugin({
  org: "org",
  project: "project",
  release: "aaa",
  include: "./dist",
  authToken: "xxx",
}),

### Expected Result

Upload sourcemaps successfully.

### Actual Result

The release shows in the Sentry UI, but there are no sourcemaps. If I remove "release", it shows a generated release name, and if I specify the "release", it shows that name in the UI. But never any sourcemaps.

The log of `vite build` is below.
...
dist/assets/index-38a72625.js             358.20 kB │ gzip: 108.79 kB │ map: 1,749.33 kB
[sentry-vite-plugin] Info: Successfully created release.
[sentry-vite-plugin] Info: Uploading Sourcemaps.
**error: A release slug is required (provide with --release)**
[sentry-vite-plugin] Info: Successfully uploaded source maps.
[sentry-vite-plugin] Info: Successfully finalized release.

**Comment by todsul** [comment]
I did the ol' reboot (meaning delete node_models, npm update, vite build) and it all suddenly worked.

**Comment by micah-redwood** [comment]
Weird, same fix worked for me:
```
rm -r node_modules
rm package-lock.json
npm i
```
Then committed updated package-lock.json file and re-deployed.
