### ISSUE TITLE
Sentry try grabbing the sourcemaps even though I disable `Enable JavaScript source fetching`

### ISSUE THREAD

**Issue by hckhanh** [getsentry/sentry-javascript-bundler-plugins#187]
### Environment

SaaS (https://sentry.io/)

### Link

https://tenxtenx.sentry.io/issues/4030585679/?project=5715127&query=is%3Aunresolved&referrer=issue-stream

### Steps to Reproduce

Export sourcemap in `hidden` mode
Upload the sourcemap using `@sentry/vite-plugin`

### Expected Result

It should use the uploaded sourcemap only

### Actual Result

It try getting all the sourcemap it can: 

![image](https://user-images.githubusercontent.com/6380436/227254191-addb1e14-2770-4a44-a343-dce417e416aa.png)

**Comment by Lms24** [comment]
Hi @hckhanh thanks for writing in!

Just to clarify: Are you reporting that Sentry tries to download source maps although you disabled this? I took a look at your project settings and currently "Allow JavaScript Source Fetching" is enabled. 

Or are you reporting that uploading hidden source maps doesn't work with the plugin? Can you try setting `rewrite: true`?

**Comment by hckhanh** [comment]
Hi @Lms24 I confirm that I already disabled it in my project![image](https://user-images.githubusercontent.com/6380436/227497873-532081b8-6f18-476e-b90d-2e7934921234.jpeg)

**Comment by hckhanh** [comment]
But i still let it enabled in org scope

**Comment by hckhanh** [comment]
> Can you try setting `rewrite: true`?

I cannot enable `rewrite` in `@sentry/vite-plugin`. But when I move to `sentry-cli`, it can work with `rewrite` - even if I disable `rewrite`, it still works.

**Comment by Lms24** [comment]
>I cannot enable rewrite with @sentry/vite-plugin

Is there a reason why you cannot do this? it's just an option to set to `true`. 

>But when I move to sentry-cli, it can work with rewrite - even if I disable rewrite, it still works correctly and Sentry can parse my sourcemap.

Can you please provide a minimal reproduction (e.g. via a github repo) so that we can debug this further? I recently tried uploading hidden source maps with our webpack plugin which worked out of the box. Also, both the Vite and the Webpack plugin just use Sentry CLI under the hood, so I'm pretty sure, it's a configuration problem.
