### ISSUE TITLE
"__DEBUG_BUILD__" declared error，repeat globals.d.ts.  with @sentry/types @sentry/react .

### ISSUE THREAD

**Issue by houxd1992** [getsentry/sentry-javascript-bundler-plugins#217]
### Environment

What version are you running? Etc.
node: v14.18.3
@sentry/vite-plugin": "^0.7.2"
@sentry/react": "^7.48.0"
@sentry/tracing": "^7.48.0"

### Steps to Reproduce

1. What
2. you
3. did.

### Expected Result

What you thought would happen.

#### error log

$ tsc && vite build
node_modules/@sentry/bundler-plugin-core/node_modules/@sentry/types/types/globals.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.

2     const __DEBUG_BUILD__: boolean;
            ~~~~~~~~~~~~~~~

  node_modules/@sentry/types/types/globals.d.ts:2:11
    2     const __DEBUG_BUILD__: boolean;
                ~~~~~~~~~~~~~~~
    '__DEBUG_BUILD__' was also declared here.

node_modules/@sentry/types/types/globals.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.

2     const __DEBUG_BUILD__: boolean;
            ~~~~~~~~~~~~~~~

  node_modules/@sentry/bundler-plugin-core/node_modules/@sentry/types/types/globals.d.ts:2:11
    2     const __DEBUG_BUILD__: boolean;
                ~~~~~~~~~~~~~~~
    '__DEBUG_BUILD__' was also declared here.

Found 2 errors in 2 files.

Errors  Files
     1  node_modules/@sentry/bundler-plugin-core/node_modules/@sentry/types/types/globals.d.ts:2
     1  node_modules/@sentry/types/types/globals.d.ts:2
error Command failed with exit code 2.

=============================================

is that a error? Looking forward to your help.

**Comment by lforst** [comment]
Hi, please align all your sentry dependencies to the same version.

**Comment by houxd1992** [comment]
I upgrade @sentry/react to "7.50.0"，it's worked ，thx
