### ISSUE TITLE
Vite + sentryVitePlugin breaks debugging on chrome

### ISSUE THREAD

**Issue by nahumzs** [getsentry/sentry-javascript-bundler-plugins#238]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

On my code, I'm setting the `debugger` word to stop and inspect my code, at the moment of adding `sentryVitePlugin` chrome debugger not longer stops on the exact step, but instead stops at a random position; see images.

**This is when the plugin has not been added.**

![image](https://user-images.githubusercontent.com/19418590/234704832-e29a2269-81c2-4667-8277-d287c9bf9d6c.png)

**Once the plugin has been added, stops at the start or the component function**

![image](https://user-images.githubusercontent.com/19418590/234705861-68781426-1837-42b0-a1cd-aa151c182e7f.png)

## vite configuration

```js
export default () => {
  return defineConfig({
    plugins: [
      react({ include: "**/*.tsx" }),
      sentryVitePlugin({
        org: "---",
        project: "---",
        authToken: "---",

        sourcemaps: {
          assets: "./dist/**",
        },
      }),
    ],
    build: {
      target: "esnext",
      minify: false,
    },
  });
};
```

### Expected Result

The plugin shouldn't affect the debugging experience for the developer.

### Actual Result

Is messing with the Developer Experience

### Product Area

Unknown

### DSN

o4504879322693632

**Comment by lforst** [comment]
Hm, not gonna look into this right now but it might be due to source mapping quality. I wonder if we can even fix this.

**Comment by JonTutis** [comment]
@nahumzs I was having the same problem, didn't even suspect Sentry until this. I removed `sentryVitePlugin` and BOOM debugging is working again. Really annoying but thanks for discovering this. Maybe one day it will be fixed O_o

**Comment by nahumzs** [comment]
> Hm, not gonna look into this right now but it might be due to source mapping quality. I wonder if we can even fix this.

If it cant be fixed then should be only a bundle step? Dont really undestand why the plugin should even work at dev level. Of course there might be things that i dont have the full context. 

Wouldnt adding an option to disabled it at dev level would be enough?

**Comment by lforst** [comment]
@JonTutis What version of the vite plugin are you using? I suspect this might have been fixed with https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/383 which was released with `2.7.0`.

@nahumzs There is a `disable` option you can fall back to.

**Comment by JonTutis** [comment]
@lforst You are correct, please ignore me, upgraded to 2.7.1 (from 2.6.x) and all is good in the world.

**Comment by lforst** [comment]
@JonTutis Awesome! Glad to hear it works for you again!
