### ISSUE TITLE
@sentry/esbuild-plugin incredibly slow with individual lambda function

### ISSUE THREAD

**Issue by josh-burton** [getsentry/sentry-javascript-bundler-plugins#245]
### Environment

What version are you running? Etc.
**0.7.2**

### Steps to Reproduce

We've been successfully using `@sentry/esbuild-plugin` to upload sourcemaps in a project with >20 lamba functions exported from a single index file.

Now we have migrated each handler to their own file, and are using the serverless package individually option.

After this change, our deploys are taking much much longer, and we're seeing:
- `@sentry/esbuild-plugin` upload source maps after each individual function is built (so if we have 30 functions, the plugin runs 30 times)
- `@sentry/esbuild-plugin` upload source maps _cumulatively_ - i.e. the sourcemaps for every previously built function
- we end up hundreds of sourcemap artifacts uploaded after each deploy.

### Expected Result

Either the plugin uploads the sourcemaps for just the current lambda function, or it runs once at the end of the deploy.

### Actual Result

See above.

**Comment by lforst** [comment]
Hey, I feel like this is an issue with your configuration. If you add the plugin 30 times, it's gonna upload 30 times.

If you feel like this is an issue with the plugin, what is the proposed solution?

**Comment by josh-burton** [comment]
It could well be a configuration issue, although I'm not adding the plugin 30 times, just once. 

I would expect the plugin to run at the end of the build, i.e. after running `sls package`. But currently I guess it runs after a different serverless hook?

I guess my questions are:
- can the point at which the plugin runs be controlled?
- how can I prevent it uploading the same sources each time? I don't really mind if it runs 30 times, as long as each time it runs only the source + map for that function is uploaded

**Comment by lforst** [comment]
> `sls package`

I have sadly no idea what that command is.

> can the point at which the plugin runs be controlled?

Esbuild is really flexible since the API is programmatic so it is totally up to you when the plugin runs. I guess you should just add multiple entrypoints when building instead of running esbuild for each lambda individually.

> how can I prevent it uploading the same sources each time?

Look into how the `sourcemaps.assets` and `sourcemaps.ingnore` option work. You can provide globs here.

**Comment by josh-burton** [comment]
Sorry I should have mentioned I'm using serverless framework. I believe the esbuild entrypoints are not customisable since serverless framework controls this.

I probably need to look more into serverless framework and it's integration with esbuild.

**Comment by mitchh** [comment]
@josh-burton did you ever get resolution on this? I'm having the same issue...
