### ISSUE TITLE
Automatically turn on source maps generation

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-javascript-bundler-plugins#256]
- How to do safely so we don't end up publishing user code by accident?
- Maybe just add some warnings + instructions?
- Auto remove source maps after upload?

**Comment by HazAT** [comment]
I think if someone goes as far and adds the plugin - they want source maps.

For those people where the wizard adds it - it's also fine.
This is not an issue and we don't need to be overly careful with it.

The countet argument is, without source maps - Sentry is more or less useless.

**Comment by lforst** [comment]
I _want_ to be careful especially with the move towards Next.js server actions and all. We could be publishing serverside source code that contains secrets. But yea I wanna do this too.

**Comment by timfish** [comment]
> * Auto remove source maps after upload?

I think this would be key. If you force enable source maps, they should not end up in the output. 

I've seen production Electron apps that have shipped source maps and this is almost always unintentional!

**Comment by s1gr1d** [comment]
Related to this issue: https://github.com/getsentry/sentry-javascript/issues/13993

If no source map settings are set, we will enable 'hidden' source maps.
