### ISSUE TITLE
Artifact bundle source map upload to self-hosted Sentry shows -1 artifacts

### ISSUE THREAD

**Issue by fliize** [getsentry/sentry-javascript-bundler-plugins#261]
### Environment

What version are you running? Etc.

### Steps to Reproduce
my config
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/62690481/31028b70-b728-4716-872c-cd65f0cf94ad)
log
![1684838401291](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/62690481/a504ff82-288f-462d-83ce-3ee1d74c25aa)
sentry platform
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/62690481/6a89058f-e62f-4f13-8404-9266f6dc2366)

### Expected Result

see ARTIFACTS not -1 but 170

### Actual Result

ARTIFACTS is -1, connot see sourcemaps

**Comment by lforst** [comment]
Hey, are you using self-hosted? If so, please use the `release.uploadLegacySourcemaps` option instead of `sourcemaps.assets` for now. This feature will hit self-hosted soon.

**Comment by lforst** [comment]
@fliize the self hosted version you're using likely doesn't support the upload via sourcemaps.assets yet.

Closing this since it seems resolved. Feel free to ping or reopen any time if you run into any more issues.

**Comment by biesbjerg** [comment]
Can you elaborate on this @lforst ?

I'm on self hosted as well and am getting `Artifacts -1` using `sourcemap.assets` as well as with suggested `release.uploadLegacySourcemaps`?

```ts
      sentryVitePlugin({
        org: process.env.PUBLIC_SENTRY_ORG,
        project: process.env.PUBLIC_SENTRY_PROJECT,
        url: process.env.PUBLIC_SENTRY_URL,
        authToken: process.env.PUBLIC_SENTRY_AUTH_TOKEN,
        release: {
          name: "TEST-" + new Date().toISOString(),
          uploadLegacySourcemaps: {
            paths: ["./dist/assets/**"]
          }
        }
      })
```

```ts
      sentryVitePlugin({
        org: process.env.PUBLIC_SENTRY_ORG,
        project: process.env.PUBLIC_SENTRY_PROJECT,
        url: process.env.PUBLIC_SENTRY_URL,
        authToken: process.env.PUBLIC_SENTRY_AUTH_TOKEN,
        sourcemaps: {
          assets: "./dist/assets/**"
        }
      })
```

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/230182/afd8c05a-5968-4e5e-94f7-a7168ae5a6cb)


![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/230182/523c2092-f602-4540-af44-6a9d080a0d31)

Sentry self-hosted is using latest master and vite plugin is 2.1.0.

Am I missing something?

**Comment by lforst** [comment]
I forwarded this internally to understand a bit what might be going on. I have a feeling this will be resolved with the next self hosted release though. Can I ask, is this just a visual bug or are source maps actually not working for you at all?

**Comment by biesbjerg** [comment]
Thanks!

I'm having trouble telling if it is partly working or not, since I kind of get real code when error occurs in vue components - but not in typescript files.

**Scenario A:**

A syntax error in the entry point file (`main.ts`) after Sentry has been initialized:

```ts
setTimeout(() => {
  eval("syntax error in main.ts");
}, 1000);
```

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/230182/08bb8957-31b7-425e-ae82-b9b826bbc860)

**Scenario B:**

A syntax error in a vue file:

```vue
<script setup lang="ts">
...
setTimeout(() => {
  eval("syntax error in a vue file");
}, 1000);
</script>
...
```

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/230182/386cc302-b123-448b-9bcb-659ebe962431)


Please let me know if  you need anything else from me.

**Comment by lforst** [comment]
Scenario A looks weird today because the stacktrace seems completely unrelated to how and where the error is thrown.

**Comment by lforst** [comment]
Maybe ionic messes up source maps in some scenarios.

**Comment by biesbjerg** [comment]
I just tried building and then using `sentry-cli` to upload the source maps - and artifacts are showing up in Sentry, which suggests the issues is with the bundler plugin, right? I don't think I'm able to easily test if errors are showing up properly this way though.

```
npx sentry-cli sourcemaps upload dist/assets -p safe --release uploaded-via-sentry-cli
> Found 76 files
> Analyzing 76 sources
> Analyzing completed in 0.004s
> Rewriting sources
> Rewriting completed in 0.02s
> Adding source map references
> Bundling completed in 0.095s
> Bundled 76 files for upload
> Bundle ID: 98940622-fb09-551e-978d-fa1c3275b2e5
> Optimizing completed in 0.002s
> Uploading completed in 0.301s
> Uploaded files to Sentry
> Processing completed in 0.133s
> File upload complete (processing pending on server)
> Organization: medware
> Project: safe
> Release: uploaded-via-sentry-cli
> Dist: None
> Upload type: release bundle

Source Map Upload Report
  Minified Scripts
    ~/AboutPage-2a988325.js (sourcemap at AboutPage-2a988325.js.map, debug id cb4d8766-41fe-5b49-91ef-49bba60bab1d)
    ~/ActivitiesFavoritesPage-56b2c507.js (sourcemap at ActivitiesFavoritesPage-56b2c507.js.map, debug id 3ece9383-83d1-54f9-a78c-ac0a6ff99a3d)
    ~/ActivitiesHelperPage-03ac503e.js (sourcemap at ActivitiesHelperPage-03ac503e.js.map, debug id 83a320ca-d00e-56b3-82b1-9b10eab54836)
    ~/ActivitiesPatientPage-8dd5a21d.js (sourcemap at ActivitiesPatientPage-8dd5a21d.js.map, debug id b0e2d3ae-fd42-5ec8-91cb-4310613128a2)
    ~/ArticleDetailPage-93fd8e34.js (sourcemap at ArticleDetailPage-93fd8e34.js.map, debug id 0ff1bc3f-dcdc-53f2-aecc-837bc3af940d)
    ~/ArticlesPage-eb40daa2.js (sourcemap at ArticlesPage-eb40daa2.js.map, debug id 2a0cd4f5-ed9a-5c58-bf33-ce24b64d8fc9)
    ~/BackToFrontPageButton-53351d34.js (sourcemap at BackToFrontPageButton-53351d34.js.map, debug id d93c512c-1dfd-55e0-b88e-3c5c6b5311c3)
    ~/FirstBootPage-7438566e.js (sourcemap at FirstBootPage-7438566e.js.map, debug id 05a25b51-907a-5e1b-a96d-2209c4ab06b2)
    ~/FrontPage-4fa90ffc.js (sourcemap at FrontPage-4fa90ffc.js.map, debug id 1a6912cb-8f5e-52fe-9e7b-2a94d6b39b4e)
    ~/HelpPage-27b7f546.js (sourcemap at HelpPage-27b7f546.js.map, debug id e3514ed6-b271-54d6-b17f-c52027b4eb0d)
    ~/HotlineDetailPage-d4ad28a5.js (sourcemap at HotlineDetailPage-d4ad28a5.js.map, debug id bfcceb5e-f712-54c1-a28d-99da1e5df458)
    ~/LocationsPage-7e611d90.js (sourcemap at LocationsPage-7e611d90.js.map, debug id 5e84f426-8d0b-5b22-8636-222a0f7a24a0)
    ~/MainPage-1f1bc2fc.js (sourcemap at MainPage-1f1bc2fc.js.map, debug id 43011fe4-573d-57bf-a6f3-70df85dbe256)
    ~/MwCard-7dd8e99d.js (sourcemap at MwCard-7dd8e99d.js.map, debug id 246dc6aa-3480-5557-84ec-b614f3cb5e96)
    ~/MwCardSimple-2bc7f5ca.js (sourcemap at MwCardSimple-2bc7f5ca.js.map, debug id 538d0b15-a4a9-5c6b-9b63-91c479921625)
    ~/MyNotesList-63e8325c.js (sourcemap at MyNotesList-63e8325c.js.map, debug id 5d7a6d10-a4cf-5aba-bc3a-122e3cc8e067)
    ~/MyNotesPage-99c7c9eb.js (sourcemap at MyNotesPage-99c7c9eb.js.map, debug id 7a718e39-3c9f-5893-91ac-34c798a30118)
    ~/MyWellBeingPage-6e304c7c.js (sourcemap at MyWellBeingPage-6e304c7c.js.map, debug id 069f3b16-b60b-55ad-8bb5-38bd6354ee31)
    ~/NoteForm-4ae86500.js (sourcemap at NoteForm-4ae86500.js.map, debug id fd03d1f0-fd60-5207-af0c-b753d494b901)
    ~/ProfilePage-3911478f.js (sourcemap at ProfilePage-3911478f.js.map, debug id 23493e3f-29ef-51b8-abc0-d9082d6b017a)
    ~/SafeAreaTop-2a05584c.js (sourcemap at SafeAreaTop-2a05584c.js.map, debug id 4a282df1-75e3-56a6-b5d7-e1f9140d9560)
    ~/WhoIsBehindPage-3a7882f0.js (sourcemap at WhoIsBehindPage-3a7882f0.js.map, debug id ce2aa03d-b9a1-5816-8ad0-eab1cf0f9168)
    ~/focus-visible-56d4fbba.js (sourcemap at focus-visible-56d4fbba.js.map, debug id 1192fa43-1e58-5c95-8eff-4aa8339e1645)
    ~/icon-note-04cd6e8a.js (sourcemap at icon-note-04cd6e8a.js.map, debug id e7d7c6f9-7669-52d1-a9b6-462a5e8b1714)
    ~/index-348ae88f.js (sourcemap at index-348ae88f.js.map, debug id 8a595673-0525-5ec3-9223-636a6b0d61d5)
    ~/index9-3d7dc098.js (sourcemap at index9-3d7dc098.js.map, debug id 5d178a46-385d-5a18-950b-f5038a38ca99)
    ~/input-shims-106b2a69.js (sourcemap at input-shims-106b2a69.js.map, debug id 837d24d8-3110-5653-a941-aff3e1443e2a)
    ~/ios.transition-8b30a5e1.js (sourcemap at ios.transition-8b30a5e1.js.map, debug id 9df315c1-c83c-58a8-92d8-33ff7163b6a0)
    ~/keyboard2-78b51126.js (sourcemap at keyboard2-78b51126.js.map, debug id 08a68b3d-3590-56d8-9f8c-c22cc4cdca60)
    ~/logo-regions-ab9ea786.js (sourcemap at logo-regions-ab9ea786.js.map, debug id d4fa1792-fcef-562b-b407-78072e564d2b)
    ~/md.transition-cdad0091.js (sourcemap at md.transition-cdad0091.js.map, debug id fc43e3e9-e925-57c7-b80c-7d89d3e512e4)
    ~/status-tap-5d6c222b.js (sourcemap at status-tap-5d6c222b.js.map, debug id 9970beaa-a698-5385-8857-452f359b08c3)
    ~/swipe-back-33ca09ca.js (sourcemap at swipe-back-33ca09ca.js.map, debug id 770e0a64-726d-5cd3-998a-354377e1a259)
    ~/web-3037e854.js (sourcemap at web-3037e854.js.map, debug id 42a2e966-996b-53bc-ad8c-e40afa9590fe)
    ~/web-38181ed8.js (sourcemap at web-38181ed8.js.map, debug id d482cb52-9d23-5427-999c-2370eb1a6d94)
    ~/web-66d01a31.js (sourcemap at web-66d01a31.js.map, debug id 41fa407e-ba90-5144-a1e2-8f18ee9d789c)
    ~/web-b9b6b08b.js (sourcemap at web-b9b6b08b.js.map, debug id d59218ce-6542-5d2b-abaa-30ca768251a8)
    ~/web-c4617bba.js (sourcemap at web-c4617bba.js.map, debug id f1ba1fac-114a-51d5-b607-abe7a0cf9f65)
  Source Maps
    ~/AboutPage-2a988325.js.map (debug id cb4d8766-41fe-5b49-91ef-49bba60bab1d)
    ~/ActivitiesFavoritesPage-56b2c507.js.map (debug id 3ece9383-83d1-54f9-a78c-ac0a6ff99a3d)
    ~/ActivitiesHelperPage-03ac503e.js.map (debug id 83a320ca-d00e-56b3-82b1-9b10eab54836)
    ~/ActivitiesPatientPage-8dd5a21d.js.map (debug id b0e2d3ae-fd42-5ec8-91cb-4310613128a2)
    ~/ArticleDetailPage-93fd8e34.js.map (debug id 0ff1bc3f-dcdc-53f2-aecc-837bc3af940d)
    ~/ArticlesPage-eb40daa2.js.map (debug id 2a0cd4f5-ed9a-5c58-bf33-ce24b64d8fc9)
    ~/BackToFrontPageButton-53351d34.js.map (debug id d93c512c-1dfd-55e0-b88e-3c5c6b5311c3)
    ~/FirstBootPage-7438566e.js.map (debug id 05a25b51-907a-5e1b-a96d-2209c4ab06b2)
    ~/FrontPage-4fa90ffc.js.map (debug id 1a6912cb-8f5e-52fe-9e7b-2a94d6b39b4e)
    ~/HelpPage-27b7f546.js.map (debug id e3514ed6-b271-54d6-b17f-c52027b4eb0d)
    ~/HotlineDetailPage-d4ad28a5.js.map (debug id bfcceb5e-f712-54c1-a28d-99da1e5df458)
    ~/LocationsPage-7e611d90.js.map (debug id 5e84f426-8d0b-5b22-8636-222a0f7a24a0)
    ~/MainPage-1f1bc2fc.js.map (debug id 43011fe4-573d-57bf-a6f3-70df85dbe256)
    ~/MwCard-7dd8e99d.js.map (debug id 246dc6aa-3480-5557-84ec-b614f3cb5e96)
    ~/MwCardSimple-2bc7f5ca.js.map (debug id 538d0b15-a4a9-5c6b-9b63-91c479921625)
    ~/MyNotesList-63e8325c.js.map (debug id 5d7a6d10-a4cf-5aba-bc3a-122e3cc8e067)
    ~/MyNotesPage-99c7c9eb.js.map (debug id 7a718e39-3c9f-5893-91ac-34c798a30118)
    ~/MyWellBeingPage-6e304c7c.js.map (debug id 069f3b16-b60b-55ad-8bb5-38bd6354ee31)
    ~/NoteForm-4ae86500.js.map (debug id fd03d1f0-fd60-5207-af0c-b753d494b901)
    ~/ProfilePage-3911478f.js.map (debug id 23493e3f-29ef-51b8-abc0-d9082d6b017a)
    ~/SafeAreaTop-2a05584c.js.map (debug id 4a282df1-75e3-56a6-b5d7-e1f9140d9560)
    ~/WhoIsBehindPage-3a7882f0.js.map (debug id ce2aa03d-b9a1-5816-8ad0-eab1cf0f9168)
    ~/focus-visible-56d4fbba.js.map (debug id 1192fa43-1e58-5c95-8eff-4aa8339e1645)
    ~/icon-note-04cd6e8a.js.map (debug id e7d7c6f9-7669-52d1-a9b6-462a5e8b1714)
    ~/index-348ae88f.js.map (debug id 8a595673-0525-5ec3-9223-636a6b0d61d5)
    ~/index9-3d7dc098.js.map (debug id 5d178a46-385d-5a18-950b-f5038a38ca99)
    ~/input-shims-106b2a69.js.map (debug id 837d24d8-3110-5653-a941-aff3e1443e2a)
    ~/ios.transition-8b30a5e1.js.map (debug id 9df315c1-c83c-58a8-92d8-33ff7163b6a0)
    ~/keyboard2-78b51126.js.map (debug id 08a68b3d-3590-56d8-9f8c-c22cc4cdca60)
    ~/logo-regions-ab9ea786.js.map (debug id d4fa1792-fcef-562b-b407-78072e564d2b)
    ~/md.transition-cdad0091.js.map (debug id fc43e3e9-e925-57c7-b80c-7d89d3e512e4)
    ~/status-tap-5d6c222b.js.map (debug id 9970beaa-a698-5385-8857-452f359b08c3)
    ~/swipe-back-33ca09ca.js.map (debug id 770e0a64-726d-5cd3-998a-354377e1a259)
    ~/web-3037e854.js.map (debug id 42a2e966-996b-53bc-ad8c-e40afa9590fe)
    ~/web-38181ed8.js.map (debug id d482cb52-9d23-5427-999c-2370eb1a6d94)
    ~/web-66d01a31.js.map (debug id 41fa407e-ba90-5144-a1e2-8f18ee9d789c)
    ~/web-b9b6b08b.js.map (debug id d59218ce-6542-5d2b-abaa-30ca768251a8)
    ~/web-c4617bba.js.map (debug id f1ba1fac-114a-51d5-b607-abe7a0cf9f65)
```

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/230182/832c1e1d-1953-4fda-b1ee-1ebd38b9a378)

**Comment by lforst** [comment]
The bundler plugins use Sentry CLI under the hood. You might have an old version of Sentry CLI that is compatible with your self hosted version.

I am gonna go ahead and say we should wait this out until the next release of self-hosted where this will likely be fixed anyways.

**Comment by d2461379109** [comment]
> 捆绑器插件在后台使用 Sentry CLI。您可能拥有与您的自托管版本兼容的旧版本 Sentry CLI。
> 
> 我要继续说我们应该等到下一个自托管版本发布，无论如何这可能会被修复。

Is it fixed now?

**Comment by biesbjerg** [comment]
Seems to be fixed for me after updating to Sentry self-hosted@v2.6.1 and @sentry/vite-plugin@2.3.0 :-)

**Comment by lforst** [comment]
@biesbjerg Amazing. Thanks for the update!

**Comment by ddubrava** [comment]
Hey! Unfortunately, it doesn't work for us. We use `"@sentry/webpack-plugin": "2.3.0"` and self hosted `Sentry 23.5.2
ad182e5`. I tried both configurations

```ts
release: {
    name: `f${Date.now().toString(16)}`,
    uploadLegacySourcemaps: {
        paths: [`${distPath}/**`],
    },
},
```

 and
            
```ts
sourcemaps: {
    assets: [`${distPath}/**`],
},
```

So both of them do not work. The debug message says that everything is okay: '[sentry-webpack-plugin] Info: Successfully uploaded source maps to Sentry.' However, the artifacts for each release are -1. Additionally, the source maps do not work when I open an event.

**Comment by lforst** [comment]
@ddubrava yes upgrading to the latest 23.6.* version will likely fix it for you. There was a feature flag the default of which we only quite recently flipped which caused this.

**Comment by ddubrava** [comment]
> @ddubrava yes upgrading to the latest 23.6.* version will likely fix it for you. There was a feature flag the default of which we only quite recently flipped which caused this.

good, thank you. But is there a workaround for the current version (23.5.2)? For example, can I downgrade the webpack plugin?

**Comment by lforst** [comment]
@ddubrava Yea if you're using the webpack plugin you can downgrade to version 1.x. I would strongly recommend upgrading the self hosted version instead though since sourcemaps are way easier to set up with the 2.x version of the plugin.

**Comment by pankucsi** [comment]
Hello,

I tried out both config what @ddubrava suggested, and I use "@sentry/webpack-plugin": "2.3.0" with self hosted Sentry 23.6.1, but still unlucky. Terminal shows everything is fine, but I see -1 artifacts still. Any suggestion what should I look for ?

**Comment by lforst** [comment]
@pankucsi Pls share your plugin setup and double check you're actually on the newest versions.

**Comment by ddubrava** [comment]
> Hello,
> 
> I tried out both config what @ddubrava suggested, and I use "@sentry/webpack-plugin": "2.3.0" with self hosted Sentry 23.6.1, but still unlucky. Terminal shows everything is fine, but I see -1 artifacts still. Any suggestion what should I look for ?

Hi! We still haven't solved the problem, but in our case, the issue lies with the infrastructure. The sentry workers do not share the same volume, see [this](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-workers-are-sharing-the-same-volume-as-web-if-running-self-hosted-sentry-via-docker). You can upload source maps via sentry-cli. If that doesn't work, the problem is not related to a plugin.

**Comment by ddubrava** [comment]
@lforst

Hi! Finally, we fixed the issue by sharing volumes between pods. However, we still have a strange problem with the Sentry UI. Artifacts are uploaded successfully, source maps work, but they show as -1, and I can't check them through the UI. However, if I upload them using sentry-cli, everything works.

<img width="375" alt="Screenshot 2023-06-23 at 19 12 39" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/22116465/1a4944bc-d5dc-42b8-b263-141d1e8a9b27">

<img width="1169" alt="Screenshot 2023-06-23 at 19 12 34" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/22116465/836f5b80-3c02-41e8-8e57-621923b5cb7d">

**Comment by lforst** [comment]
@ddubrava What self-hosted version are you on, and, what sentry-cli version are you using?

**Comment by ddubrava** [comment]
> @ddubrava What self-hosted version are you on, and, what sentry-cli version are you using?

```
"@sentry/webpack-plugin": "2.3.0",
Sentry 23.6.1, 5534341
```

sentry-cli I was using via npx - `npx -p @sentry/cli sentry-cli`

**Comment by lforst** [comment]
Since you are using `npx`. Can you quickly check for me whether and which `@sentry/cli` version you have installed globally? Thanks!

**Comment by ddubrava** [comment]
> Since you are using `npx`. Can you quickly check for me whether and which `@sentry/cli` version you have installed globally? Thanks!

<img width="652" alt="Screenshot 2023-06-28 at 10 59 28" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/22116465/2703e9d0-0646-4451-a7ca-86a8361270ed">

**Comment by ddubrava** [comment]
@lforst Hi! Any updates? It's not a big deal, but it's strange to see a -1 indication when we upload with the plugin

**Comment by lforst** [comment]
@ddubrava  Hi, I asked around internally and the screenshot you posted [here](https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/261#issuecomment-1604519952) seems to be on an old Sentry Self-hosted version. Can you double check that you are on at least 23.6.1?

**Comment by ddubrava** [comment]
> @ddubrava Hi, I asked around internally and the screenshot you posted [here](https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/261#issuecomment-1604519952) seems to be on an old Sentry Self-hosted version. Can you double check that you are on at least 23.6.1?

<img width="1508" alt="Screenshot 2023-07-04 at 11 33 49" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/22116465/af3ffa1c-0766-47f9-834d-4f98d4f8f8d7">

**Comment by lforst** [comment]
> Is it somehow possible to have -1 on 23.6.1? I'll try to upload them again in a few days

I honestly don't know. I think there is something funky going on because we had a feature flag for this feature to gradually roll it out.

We are removing all the legacy fallbacks and feature flags right now so let's try again with the next self-hosted release:
- https://github.com/getsentry/sentry/pull/52114
- https://github.com/getsentry/sentry/pull/52102
