### ISSUE TITLE
Using @sentry/electron with @sentry/webpack-plugin doesn't provide proper stack traces anymore (1.X worked fine)

### ISSUE THREAD

**Issue by tom2strobl** [getsentry/sentry-javascript-bundler-plugins#286]
### Environment

`"@sentry/webpack-plugin": "^2.1.0"`
`"@sentry/electron": "^4.5.0"` _(which uses "@sentry/browser": "7.50.0", which should be compatible and have debug_id support)_

### Steps to Reproduce

I'm using electron and a dual build with separate configs for building main and the renderer.

In production code I use the following SDK in main:
```typescript
import * as Sentry from '@sentry/electron/main'
Sentry.init({
  dsn: process.env.SENTRY_DSN,
  release: APP_VERSION || 'unknown',
  environment: process.env.STAGE,
  integrations: [new Sentry.Integrations.ElectronMinidump()]
})
```
And the following in the renderer:
```typescript
import * as Sentry from '@sentry/electron/renderer'
Sentry.init({
  dsn: process.env.SENTRY_DSN,
  release: process.env.APP_VERSION || 'unknown',
  environment: process.env.STAGE,
  integrations: (defaultIntegrations) => {
    return [new CaptureConsoleIntegration(), ...defaultIntegrations]
  }
})
```

I'm using the following for the main webpack config:
```javascript
import { sentryWebpackPlugin } from '@sentry/webpack-plugin'
sentryWebpackPlugin({
  authToken: process.env.SENTRY_AUTH_TOKEN,
  org: 'XXXXX',
  project: 'XXXXX-desktop',
  sourcemaps: {
    assets: [
      path.join(__dirname, '..', '..', '..', 'desktop-release', 'app', 'dist', 'main.js.map'),
      path.join(__dirname, '..', '..', '..', 'desktop-release', 'app', 'dist', 'main.js'),
      path.join(__dirname, '..', '..', '..', 'desktop-release', 'app', 'dist', 'pdfWorker.js.map'),
      path.join(__dirname, '..', '..', '..', 'desktop-release', 'app', 'dist', 'pdfWorker.js')
    ]
  }
})
```
and the following for the renderer webpack config:
```javascript
import { sentryWebpackPlugin } from '@sentry/webpack-plugin'
sentryWebpackPlugin({
  authToken: process.env.SENTRY_AUTH_TOKEN,
  org: 'XXXXXX',
  project: 'XXXXX-desktop',
  sourcemaps: {
    assets: [path.join(__dirname, '..', '..', '..', 'desktop-release', 'app', 'dist', '**')],
    // those are handled by the main build
    ignore: ['main.js', 'main.js.map', 'pdfWorker.js', 'pdfWorker.js.map']
  }
})
```

The logs of the main build process:

```
Source Map Upload Report
  Minified Scripts
    ~/600a95d7-1ae2-4529-98c1-f9862b6de145-0.js (sourcemap at main.js.map, debug id 600a95d7-1ae2-4529-98c1-f9862b6de145)
    ~/e90f76c6-acb5-46ca-9791-6722a6566319-1.js (sourcemap at pdfWorker.js.map, debug id e90f76c6-acb5-46ca-9791-6722a6566319)
  Source Maps
    ~/600a95d7-1ae2-4529-98c1-f9862b6de145-0.js.map (debug id 600a95d7-1ae2-4529-98c1-f9862b6de145)
    ~/e90f76c6-acb5-46ca-9791-6722a6566319-1.js.map (debug id e90f76c6-acb5-46ca-9791-6722a6566319)
```
The logs of the renderer build process:
```
Source Map Upload Report
  Minified Scripts
    ~/1e674106-c4ca-473f-8846-4ba4c32fd4c2-1.js (sourcemap at windowAuth.js.map, debug id 1e674106-c4ca-473f-8846-4ba4c32fd4c2)
    ~/4e803fcc-3af8-4e1a-a133-7d0d2437cda1-2.js (sourcemap at runtime.js.map, debug id 4e803fcc-3af8-4e1a-a133-7d0d2437cda1)
    ~/600a95d7-1ae2-4529-98c1-f9862b6de145-6.js (sourcemap at main.js.map, debug id 600a95d7-1ae2-4529-98c1-f9862b6de145)
    ~/693adea4-6c20-43ae-87d6-1e65ceb6ce16-9.js (no sourcemap ref, debug id 693adea4-6c20-43ae-87d6-1e65ceb6ce16)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/693adea4-6c20-43ae-87d6-1e65ceb6ce16-9.js)
    ~/8ba42dbb-5a24-4dc0-a266-455ba38368ae-0.js (sourcemap at windowMain.js.map, debug id 8ba42dbb-5a24-4dc0-a266-455ba38368ae)
    ~/91348eeb-3570-44cb-a750-ceb848961393-8.js (no sourcemap ref, debug id 91348eeb-3570-44cb-a750-ceb848961393)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/91348eeb-3570-44cb-a750-ceb848961393-8.js)
    ~/c488e720-7582-4c36-9795-65d3164cf26a-10.js (no sourcemap ref, debug id c488e720-7582-4c36-9795-65d3164cf26a)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/c488e720-7582-4c36-9795-65d3164cf26a-10.js)
    ~/e28603d3-7806-4eb9-b165-6e4f47976d07-7.js (sourcemap at loader.js.map, debug id e28603d3-7806-4eb9-b165-6e4f47976d07)
    ~/e90f76c6-acb5-46ca-9791-6722a6566319-4.js (sourcemap at pdfWorker.js.map, debug id e90f76c6-acb5-46ca-9791-6722a6566319)
  Source Maps
    ~/1e674106-c4ca-473f-8846-4ba4c32fd4c2-1.js.map (debug id 1e674106-c4ca-473f-8846-4ba4c32fd4c2)
    ~/4e803fcc-3af8-4e1a-a133-7d0d2437cda1-2.js.map (debug id 4e803fcc-3af8-4e1a-a133-7d0d2437cda1)
    ~/600a95d7-1ae2-4529-98c1-f9862b6de145-6.js.map (debug id 600a95d7-1ae2-4529-98c1-f9862b6de145)
    ~/8ba42dbb-5a24-4dc0-a266-455ba38368ae-0.js.map (debug id 8ba42dbb-5a24-4dc0-a266-455ba38368ae)
    ~/e28603d3-7806-4eb9-b165-6e4f47976d07-7.js.map (debug id e28603d3-7806-4eb9-b165-6e4f47976d07)
    ~/e90f76c6-acb5-46ca-9791-6722a6566319-4.js.map (debug id e90f76c6-acb5-46ca-9791-6722a6566319)
```

Then in main.ts I capture an Exception:
```javascript
import * as Sentry from '@sentry/electron/main'
Sentry.captureException(new Error('main test error'))
```
And in the renderer I throw:
```javascript
throw new Error('renderer test error')
```

Main Result (eventId: 1803622f265e4d8e82afc5c621c8d736):
<img width="474" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/557074/2789032a-2e3f-4f28-b25a-2e10da8d48d4">

Renderer Result (eventId: 452429489c4849db8a73c8c8745a90e6):
<img width="495" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/557074/7c7ee16e-58df-4fa9-b82a-4c8299e0cadd">

### What I expect

I expect the stacktraces to point me exactly where in the code the Error was thrown. As it was before when using 1.x.

### Things I tried out

I tried adding
```typescript
release: {
  name: APP_VERSION || 'unknown'
}
```
to the config and also tried without it. It doesn't really have an effect other than me knowing which artifacts belong to which release, if I understood correctly.

I am sure that artifacts are uploaded correctly, as I can see them under Project > Source Maps > Artifact Bundles.

If I download a file from an artifact bundle I can see both `sourceMappingURL=XXX` and `debugId=YYY` being present.

Neither am I using a `dist` value in SDK, nor in sentryWebpackPlugin.

As a reference: This used to be my previous 1.x renderer config that worked flawlessly:
```typescript
new SentryWebpackPlugin({
  authToken: process.env.SENTRY_AUTH_TOKEN,
  org: 'XXX',
  project: 'XXX',
  include: {
    urlPrefix: 'app:///dist/',
    stripCommonPrefix: true,
    paths: [path.join(__dirname, '..', '..', '..', 'desktop-release', 'app', 'dist')]
  },
  // those are handled by the main build
  ignore: ['main.js', 'main.js.map', 'pdfWorker.js', 'pdfWorker.js.map'],
  release: APP_VERSION || 'unknown'
}),
```
Note that I had to use the urlPrefix `app:///dist`. With the new artifact system this should not be necessary anymore, right?

Due to running out of ideas I tried adding ```rewriteSources: (source) => `app:///dist/${source}` ```, but that had no effect as far as I could tell.

If I look at the json of the two events, I **CANNOT** see a bundle_id anywhere, so I'm assuming this is the culprit?

---

PS: this page is out of date: https://docs.sentry.io/platforms/javascript/sourcemaps/best-practices/

**Comment by lforst** [comment]
Hey, can you share a link to the sentry event that is not uminified properly? You can use the share button if you don't want your org name public. Thanks! :)

**Comment by lforst** [comment]
By the way: I wanna give you props for doing a bunch of research before you opened this issue. You basically provided all the info I would have asked for :)

**Comment by tom2strobl** [comment]
> Hey, can you share a link to the sentry event that is not uminified properly? You can use the share button if you don't want your org name public. Thanks! :)

@lforst org name public shouldn't be an issue, is that what you wanted?
https://fugoya.sentry.io/issues/4207322458/events/1803622f265e4d8e82afc5c621c8d736/
https://fugoya.sentry.io/issues/4207365171/events/452429489c4849db8a73c8c8745a90e6/

> By the way: I wanna give you props for doing a bunch of research before you opened this issue. You basically provided all the info I would have asked for :)

I hate opening issues on github because it means I take away attention from someone else that could be doing something more productive, but in this case I'm just kinda lost on what to try next :-)

Btw liebe Grüße ausm 7. in den 2. ✌🏻

**Comment by tom2strobl** [comment]
> Also: If you set `debug: true` in the plugin. Can you share logs with the `[sentry-webpack-plugin]` prefix? thanks!

That's what I get in addition:

```
[sentry-webpack-plugin] Info: Sending error and performance telemetry data to Sentry. To disable telemetry, set `options.telemetry` to `false`.
[sentry-webpack-plugin] Debug: Could not determine debug ID from bundle. This can happen if you did not clean your output folder before installing the Sentry plugin. File will not be source mapped: /XXX/desktop-release/app/dist/preload.js
[sentry-webpack-plugin] Debug: Could not determine source map path for bundle: /XXX/desktop-release/app/dist/362.js
[sentry-webpack-plugin] Debug: Could not determine source map path for bundle: /XXX/desktop-release/app/dist/374.js
[sentry-webpack-plugin] Debug: Could not determine source map path for bundle: /XXX/desktop-release/app/dist/126.js
[sentry-webpack-plugin] Debug: Could not determine debug ID from bundle. This can happen if you did not clean your output folder before installing the Sentry plugin. File will not be source mapped: /XXX/desktop-release/app/dist/pdf.worker.js
```

Interesting.
So the 362.js 374.js and 126.js are actually just i18n files, so don't worry about them.
The preload.js and pdf.worker.js are something to fix differently I guess, but both of them are not _that_ important.
The main.js and windowMain.js are the two really important ones, both are not logged in a special way since flagging debug.

**Comment by tom2strobl** [comment]
I just saw: while the uploaded artifacts have a `debugId=YYY`, the main.js in my dist (that gets packaged into the final binary) does not have a `debugId` at the bottom, only `//# sourceMappingURL=main.js.map`. Is that correct?

**Comment by tom2strobl** [comment]
Running `sentry-cli sourcemaps explain` yields:
```
✔ Fetched data for event: 452429489c4849db8a73c8c8745a90e6
✔ Event has release name: 0.1.11
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
⚠ Exception is already source mapped and first resolved frame points to:

> [missing context line]
```

**Comment by lforst** [comment]
> I just saw: while the uploaded artifacts have a debugId=YYY, the main.js in my dist (that gets packaged into the final binary) does not have a debugId at the bottom, only //# sourceMappingURL=main.js.map. Is that as intended?

Yeah that is intended!

We actually found the culprit and a fix is on its way: https://github.com/getsentry/sentry-electron/pull/676

**Comment by lforst** [comment]
SDK development any% (test skip glitch allowed) PB

**Comment by tom2strobl** [comment]
@lforst I saw one runner timed out preventing the release of 4.6.0, can you check?
https://github.com/getsentry/sentry-electron/actions/runs/5091595222

**Comment by lforst** [comment]
@tom2strobl thanks for the heads up. Electron SDK CI is a bit flakey. The release is out now if you wanna try it out.

LG ausm 2. :)

**Comment by tom2strobl** [comment]
4.6.0 build went through, updated @sentry/electron, tested it and can user-confirm, both renderer and main stacktrace now like a charm. Thanks!

**Comment by lforst** [comment]
@tom2strobl great! Thanks for verifying :)
