### ISSUE TITLE
Track User Agent

### ISSUE THREAD

**Issue by scefali** [getsentry/sentry-javascript-bundler-plugins#288]
We should modify the user agent to say which bundler it came from so we can track it in analytics better. Currently, only the webpack bundler supports it.

**Comment by lforst** [comment]
Hey, can you elaborate a bit? What do you mean with user agent? Do you refer to SDK event's user agent or the bundler telemetry?

**Comment by scefali** [comment]
@lforst I'm talking about the bundler. Basically extend this: https://github.com/getsentry/action-release/blob/7d9c3a86a287efcbedca1328c56e15f2f15d5f80/src/cli.ts#L13
