### ISSUE TITLE
[Error] Occur “release not found" when upload sourcemap

### ISSUE THREAD

**Issue by KeithChou** [getsentry/sentry-javascript-bundler-plugins#289]
### Environment
MacBook Pro Ventuna 13.4
node: v16.16.0

What version are you running? Etc.
@sentry/vite-plugin 2.2.0

### Steps to Reproduce
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/18112461/489371eb-9a7f-4ae0-916e-e350f568692f)

### Expected Result
upload files to sentry successfully

What you thought would happen.

### Actual Result
oops! : (

<img width="611" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/18112461/a6898f16-1444-437d-8943-e995930edbb9">

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by lforst** [comment]
Are you using self hosted or SaaS?

**Comment by KeithChou** [comment]
> Are you using self hosted or SaaS?

yep! do u know whats problem?

**Comment by lforst** [comment]
Self hosted hasn't caught up yet to the upload via `sourcemaps.assets` please use the `release.uploadLegacySourcemaps` option instead.

**Comment by lforst** [comment]
I gotta add this to the docs :)

**Comment by KeithChou** [comment]
> Self hosted hasn't caught up yet to the upload via `sourcemaps.assets` please use the `release.uploadLegacySourcemaps` option instead.

🙀🙀🙀 okk, can u tell me how to write this code? I tried to use the following code to upload
```
release: {
      name: 'hello-world-3',
      uploadLegacySourcemaps: {
        paths: ['./dist/assets/**']
      }
    }
```

but it still occurs issue like 'release not found'

**Comment by KeithChou** [comment]
> Are you using self hosted or SaaS?

oh, sorry. we use self-hosted.

**Comment by lforst** [comment]
what version of self-hosted are you using?

**Comment by KeithChou** [comment]
> what version of self-hosted are you using?

Sentry 22.11.0 60999b0  can't work, 'release not found'
Sentry 21.1.0486d790 can't work, 'release not found'
we try to upgrade the version to the latest, which I remembered was 23.*.*, but we could not create a new auth token. That means, there is no auth token when I click to create auto token: (

**Comment by lforst** [comment]
Can you try to use sentry-cli for uploading sourcemaps and see if that works? thanks!

**Comment by KeithChou** [comment]
> Can you try to use sentry-cli for uploading sourcemaps and see if that works? thanks!

yep I tried this before.

version: sentry-cli 2.18.1

I used the same configuration to upload sourcemap,  it can work! sourcemap can be uploaded successfully!

the best way is to use @sentry/vite-plugin to upload : (

**Comment by KeithChou** [comment]
> > Can you try to use sentry-cli for uploading sourcemaps and see if that works? thanks!
> 
> yep I tried this before.
> 
> version: sentry-cli 2.18.1
> 
> I used the same configuration to upload sourcemap, it can work! sourcemap can be uploaded successfully!
> 
> the best way is to use @sentry/vite-plugin to upload : (

ant this is a command: sentry-cli releases files "hello-world123" upload-sourcemaps ~/code/test/dist/assets/**

**Comment by lforst** [comment]
Which version of sentry-cli are you using to do this?

**Comment by KeithChou** [comment]
> version: sentry-cli 2.18.1

this one, version: sentry-cli 2.18.1

**Comment by lforst** [comment]
can you share your exact configuration with auth token and org redacted when you were using `release.uploadLegacySourcemaps`? Thanks!

**Comment by KeithChou** [comment]
> can you share your exact configuration with auth token and org redacted when you were using `release.uploadLegacySourcemaps`? Thanks!
of course! here it is

sentryVitePlugin({
    org: 'sentry',
    url: 'url',
    project: 'javascript-vue',
    release: {
      name: 'hello-world-3',
      uploadLegacySourcemaps: {
        paths: ['~/dist/assets/**']
      }
    },
    authToken: 'auth token'
  })

**Comment by KeithChou** [comment]
> > can you share your exact configuration with auth token and org redacted when you were using `release.uploadLegacySourcemaps`? Thanks!
> > of course! here it is
> 
> ```
> sentryVitePlugin({
>     org: 'sentry',
>     url: 'url',
>     project: 'javascript-vue',
>     release: {
>       name: 'hello-world-3',
>       uploadLegacySourcemaps: {
>         paths: ['~/dist/assets/**']
>       }
>     },
>     authToken: 'auth token'
>   })
> ```

hi, Iforst. do u have any methods to handle this problem? This has been bugging me for a week: (

**Comment by lforst** [comment]
what is the full error message?

**Comment by salmasov** [comment]
Got the same problem with `@sentry/webpack-plugin`.

Macos BigSur
node -v: v18.16.0

Version of the plugin:
`@sentry/webpack-plugin 2.2.0`

Self-hosted Sentry, backend application version is:
`Sentry 22.3.0`

### Steps do reproduce
1. Define all ENVs (not gonna show them :)
1. Define Plugin in webpack config

```
...other plugins...
      sentryWebpackPlugin({
        disable: process.env.NODE_ENV !== 'production',
        telemetry: false,
        org: process.env.SENTRY_ORG,
        project: process.env.SENTRY_PROJECT,
        dsn: process.env.SENTRY_DSN,
        authToken: process.env.SENTRY_AUTH_TOKEN,
        release: {
          uploadLegacySourcemaps: {
            paths: ['dist']
          },
          name: process.env.VUE_APP_TAG
            ? `generic-project-name@${process.env.VUE_APP_TAG}`
            : `generic-project-name@${lastCommitHash}`
        },
        ignore: ['node_modules', 'webpack.config.js']
      }),
...other plugins...
```

3. Do `build` command; in my case it's `yarn build` calling `vue-cli-service build`

4. Build command is executed, all artifacts in `/dist` folder. Got error in console `error: release not found`. 
Full build log in attachment file!

### Expected result

Sentry Webpack Plugin creates release on backend, and i can see attached artifacts.

### Actual result

I can see that releases are created, but there is zero artifacts attached to it.


<img width="1204" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/36544178/b285a5fd-7d10-424f-b2cd-a0e57672c5a8">


### Observations

tried with different names of `release`, such as: 62c30f1, v0.0.1-rc.1, frontend-root62с30f1, frontend-root@62c30f1 (in web collapses to 62c30f1), project-foo-bar@v0.0.1 (collapses to v0.0.1)

tried with `updateLegacySourcemaps` and `sourcemaps`;

Got same result

## Here is a log file 

[log.txt](https://github.com/getsentry/sentry-javascript-bundler-plugins/files/11575974/log.txt)

**Comment by salmasov** [comment]
@lforst 

> is it feasible for you to upgrade to the newest self hosted version? I have a feeling that some part (either the plugin, or the underlying CLI) has a compat regression with self hosted.

Not today i'm afraid, will try to force this update on DevOps team :)

> Can you also check which sentry-cli version is installed in your node_modules?

line#5 in `log.txt`:
```
  DEBUG   2023-05-26 18:34:57.247404 +05:00 sentry-cli version: 2.18.1, platform: "darwin", architecture: "x86_64"
```

**Comment by KeithChou** [comment]
> what is the full error message?

thanks for your response : )  the whole error message I got was 'release not found'. I dont know why there was different result with the same configuration between @sentry/vite-plugin and sentry-cli :(

**Comment by zhuguibin1-tal** [comment]
`{
        url: '',
        org: 'sentry',
        project: '',
        release: {
          name: '1.0.0',
          uploadLegacySourcemaps: {
            paths: ['dist'],
          },
        },
        sourcemaps: {
          assets: 'dist/assets/**',
          ignore: ['node_modules'],
        },
        authToken: '',
      }`
it bugs for a while, util I change the config like this. now it works well

**Comment by andreaswachowski** [comment]
I am pretty sure I just stumbled upon the same problem. We are using self-hosted Sentry 21.12.

I can reproduce this locally by running

```
sentry-cli releases <release-id> upload-sourcemaps --use-artifact-bundle ...
```

which yields in essence

> Uploaded files to Sentry
> error: release not found

But performing this call without `--use-artifact-bundle` works:

> Uploaded files to Sentry
> Processing completed in 0.132s
> File upload complete (processing pending on server)
> ...

The `--use-artifact-bundle` option [^1][^2] has recently been set to `true` in the bundler-plugin-core [^3]. The effect is that instead of calling `/api/0/organizations/<org>/releases/<release-id>/assemble/`, sentry-cli 
POSTs to `/api/0/organizations/<org>/artifactbundle/assemble/`, which I presume does not exist on our older Sentry version (I am not sure but it looks like that endpoint was introduced with [^4]).

[^1]: https://github.com/getsentry/sentry-cli/pull/1557
[^2]: https://github.com/getsentry/sentry-cli/pull/1559
[^3]: https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/64fe2c19768ddefb1b83dbbd8ac8f4f936c4441e/packages/bundler-plugin-core/src/debug-id-upload.ts#L157
[^4]: https://github.com/getsentry/sentry/commit/14a6b2c8a27e64b613c81e81b12b1ffa6bd0fbce#diff-3b7525ea8524de9febb94974740c90f520ce7b5a7f9e432340287bc68d9d3b77R19

**Comment by andreaswachowski** [comment]
As an add-on to the above comment, the debug log shows (I have removed the "DEBUG <timestamp>" prefixes and indented instead):

```
> Uploading completed in 5.013s
> Uploaded files to Sentry
    request POST https://<host>/api/0/organizations/<org>/artifactbundle/assemble/
    using token authentication
    json body: {"checksum":"617293400c7f9ef3db07dc7f4e9d1cf59b82dee0","chunks":["3d0f313ebb9253f86e761df9a17945001999419b","4762d7c24d9428f6682f13550a20b92c4a8bce77","bb536ad287bb89617121c84d220382385ff1bfbe"],"projects":["<project>"],"version":"<hash>"}
    retry number 0, max retries: 5
    > POST /api/0/organizations/<org>/artifactbundle/assemble/ HTTP/1.1
    > Host: <host>
    > Accept: */*
    > Connection: TE
    > TE: gzip
    > User-Agent: sentry-cli/2.19.0
    > Authorization: Bearer 2d47d8e2***
    > Content-Type: application/json
    > Content-Length: 244
    < HTTP/1.1 404 Not Found
    < Server: nginx/1.18.0
    < Date: Wed, 14 Jun 2023 11:42:09 GMT
    < Content-Type: text/html; charset=utf-8
    < Content-Length: 0
    < Connection: keep-alive
    < Vary: Accept-Language, Cookie
    < Content-Language: en
    < X-Frame-Options: deny
    < X-Content-Type-Options: nosniff
    < X-XSS-Protection: 1; mode=block
    response status: 404
error: release not found
```

**Comment by jiaodingding** [comment]
I have encountered the same problem. Do you have a solution

**Comment by andreaswachowski** [comment]
I was not able to get the `uploadLegacySourcemaps` configuration to work, and haven't analysed the source code to understand why. So I stopped investigating that and now try to integrate the older version v0.7.2 instead. From what I can see, the current v2 sentry/vite-plugin breaks compatibility with older Sentry on-premises installations.

@lforst Is the official suggestion to upgrade Sentry on-premises (and if so, which is the minimum version required?), or would a future release of sentry/vite-plugin (or the bundler-plugin-core actually) remove the dependency on artifact bundles (i.e. make it optional)? I'd assume that dependency is unintentional.

**Comment by andreaswachowski** [comment]
@lforst Thanks!

> I don't quite understand what you mean by this. If you mean that the plugin will stop using artifact bundles by default: no, that won't happen as artifact bundles are the new process.

I meant whether the plugin would be able to _fall back_ to not using artifact bundles if they are not available (but use them by default). If I understand correctly, however, this should not be necessary because the proposed workaround for a plugin-user is to use the `uploadLegacySourcemaps` option. In other words, using that option should prevent the call of sentry-cli with the `--use-artifact-bundle` option, and therefore it should still work with older on-premises instances that don't have the corresponding endpoint.

I will debug why `uploadLegacySourcemaps` did not exhibit that behavior in my case.

**Comment by adgud** [comment]
Is there any workaround for this? I'm still hitting the same error on self hosted v22.5.0 with sentryWebpackPlugin 2.6.2.

**Comment by lforst** [comment]
@adgud can you try upgrading your self-hosted instance to the newest version? Thanks!

**Comment by adgud** [comment]
@lforst upgrading to 23.3.1 resolved the issue (error no longer appears and source maps are properly uploaded).

**Comment by ggyuer** [comment]
self hosted v22.11.0
sentryWebpackPlugin
Is there any way? Downgraded version? 2.7.0

**Comment by ggyuer** [comment]
self hosted v22.11.0
sentryWebpackPlugin 2.7.0
Is there any way? Downgraded version?

**Comment by lforst** [comment]
@ggyuer upgrading is the way to go

**Comment by ggyuer** [comment]
self hosted v22.11.0
sentryWebpackPlugin 2.2.1

{
   ...
   org:'',
   release:{
            name: pg.version,
            uploadLegacySourcemaps: ['local_dist']
             },
}
 
This configuration solves my problem.

**Comment by demakoff** [comment]
It looks like issue is live again at cli 2.32.1 :(
https://hub.docker.com/layers/getsentry/sentry-cli/2.32.1/images/sha256-d9c7c110c97b3c0c17928c4eb94dc6d09f5d67d97f5ccb0bde796c8806b1b8bd?context=explore

Our log:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/5207710/a3918a73-c9b0-4c42-ba03-9a08e7cdacdf)

**Comment by earthjan** [comment]
[SOLUTION] Here's a solution for folks who use self-hosted GlitchTip with Sentry.

# Configuration
The following configuration uses the `uploadLegacySourcemaps` option instead of `sourcemaps` to allow us working with self-hosted-sentry-compatible services, such as GlitchTip, that rely on mapping a reported issue with its release that has an associated sourcemap file. 

> ℹ️ `release.uploadLegacySourcemaps` and `sourcemaps` are treated differently [[source](https://www.npmjs.com/package/@sentry/vite-plugin#releaseuploadlegacysourcemaps)].

_Sentry now uses the Debug ID injected to the [artifact bundles](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/vite/#configuration) to perform mapping_.

```typescript
export default defineConfig({
  plugins: [
    // ..other plugins (As Sentry says, `sentryVitePlugin` comes after the other plugins https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/vite/#configuration)
    sentryVitePlugin({
      release: {
        name: packageJson.version,
      
        uploadLegacySourcemaps: [
          {
            paths: ["dist/assets"],
            urlPrefix: "~/assets",
          },
        ],
      },
    }),
  ],
  build: {
    sourcemap: true,
  },
});
```

## Additional Info
### Deleting the sourcemap/`.map` after uploading to the self-hosting service
We use the npm package [`rimraf`](https://www.npmjs.com/package/rimraf), for example, `npx rimraf dist/assets/**/*.js.map`. We don't use the `sourcemaps.filesToDeleteAfterUpload` as it is being prioritized over `release.uploadLegacySourcemaps`, resulting in uploading the minified file only.

### Configuring `sentryVitePlugin` with host services that support single env variable file only
We use AWS Amplify to host our web app, and as far as we know, it has only a single environment variable file shared by deployed branches. This conflicts with `sentryVitePlugin` as it gets configurations from the `.env.sentry-build-plugin` file. Therefore, we need to set the AWS Amplify's Build Settings (amplify.yml) to create a file  `.env.sentry-build-plugin` that contains configs for `sentryVitePlugin`.

---

Hope this helps!

**Comment by NiklasPor** [comment]
Hey @earthjan, thanks for the setup tips. I'm still running into the `error: release not found` (with the exact same selfhosted setup) after all files have been uploaded. Any other things to look out for when debugging this?

**Comment by lforst** [comment]
@NiklasPor upgrading your self-hosted version to a recent version will likely fix it.
