### ISSUE TITLE
Ability to define multiple projects as upload targets

### ISSUE THREAD

**Issue by beaugunderson** [getsentry/sentry-javascript-bundler-plugins#291]
`webpack-sentry-plugin` supported multiple projects, so we could associate a release with multiple projects within our Cloud Sentry account.

How do we do that with `@sentry/webpack-plugin`?

We have ~90 projects and uploading for each manually is unacceptable given the time it would take.

**Comment by lforst** [comment]
If you're referring to https://www.npmjs.com/package/webpack-sentry-plugin, that package is not maintained by us so you would have to raise an issue there.

Right now, to upload to multiple projects you have to define separate plugin instances for each project. If the plugin is not flexible enough for you, you can use Sentry CLI.

If you have improvements for the plugin, PRs are always welcome!

**Comment by op57no23** [comment]
@beaugunderson their readme says you can pass an array: https://github.com/40thieves/webpack-sentry-plugin/blob/9f027aeacc4040d9da6b6896b1dc62cf5c195a54/README.md?plain=1#LL56C1-L56C1

**Comment by beaugunderson** [comment]
> Right now, to upload to multiple projects you have to define separate plugin instances for each project. If the plugin is not flexible enough for you, you can use Sentry CLI.

it was not flexible enough for us so we collapsed those 90 projects down to one.

**Comment by beaugunderson** [comment]
> @beaugunderson their readme says you can pass an array: [40thieves/webpack-sentry-plugin@`9f027ae`/README.md?plain=1#LL56C1-L56C1](https://github.com/40thieves/webpack-sentry-plugin/blob/9f027aeacc4040d9da6b6896b1dc62cf5c195a54/README.md?plain=1#LL56C1-L56C1)

correct, that's what we did when we used that plugin--now that we have to use the new plugin from Sentry to get artifact uploads we lost that ability. to work around that we've removed all of our projects in favor of one universal project.
