### ISSUE TITLE
I don't understand what release does. Now I have not configured release, but only sourcemaps. sourcemap is still not uploaded successfully

### ISSUE THREAD

**Issue by Nicolerobinn** [getsentry/sentry-javascript-bundler-plugins#299]
### Environment

What version are you running? Etc.
 "@sentry/webpack-plugin": "^2.2.0"
### Steps to Reproduce

sentryWebpackPlugin({
      authToken: SentryAuthToken,
      org: 'sentry',
      project: 'truck',
      url: SentryUrl,
      sourcemaps: {
        ignore: ['node_modules', 'webpack.config.js'],
        deleteFilesAfterUpload: [path.resolve(PROJECT_PATH, './front/sourceMap/**/*.map')],
      }
    })

### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?
The actual sourcemaps file uploaded after packaging is 0

<img width="1243" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/48322373/5dee495a-b4dd-45e2-802f-b10916790375">

**Comment by lforst** [comment]
Hey, please update to the latest self hosted version. You can read up on how to upload source maps with legacy dependencies here:

https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/uploading-without-debug-ids/?original_referrer=https%3A%2F%2Fwww.google.com%2F

**Comment by Nicolerobinn** [comment]
@lforst Thank you very much. I tried to solve the problem according to your method
