### ISSUE TITLE
Sourcemaps file names different from the sources file names

### ISSUE THREAD

**Issue by ramikhafagi96** [getsentry/sentry-javascript-bundler-plugins#307]
### Environment

issue happened after upgrading to `@sentry/webpack-plugin` v2.2.0
"@sentry/webpack-plugin": "^2.2.0",
"@sentry/angular": "7.50.0",
"@sentry/capacitor": "0.11.4",
"@sentry/tracing": "7.50.0",
"@angular-builders/custom-webpack": "15.0.0",
### Steps to Reproduce
this is our custom webpack configuration file
```
const { appVersions } = require("./src/environments/app-versions");
const { sentryWebpackPlugin } = require("@sentry/webpack-plugin");

module.exports = (config, options, targetOptions) => {
  const dist = targetOptions.configuration;
  if (options.sourceMap) {
    config.devtool = "source-map";
    config.plugins.push(
       sentryWebpackPlugin({
        authToken: process.env.SENTRY_AUTH_TOKEN,
        org: "cartona",
        project: "ionic-app",
        release: {
            name: appVersions[dist],
            dist,
            cleanArtifacts: true,
        },
        sourcemaps: {
          assets: './www/**',
        }
      })
    );
  }
  return config;
};

```

### Expected Result

the source maps should be uploaded to sentry and when an error occurs I should see the stack trace

### Actual Result

Looking at the error events on sentry issues I find that for example the error is happening in `main.js` but checking the release artifacts I found that there's no such file or  the associated map file `main.js.map`, and the files in the artifacts are like this `~/002fdaa6-c9eb-4a1a-9c63-ef9d733c39bc-84.js` and `~/002fdaa6-c9eb-4a1a-9c63-ef9d733c39bc-84.js.map`, which is different from the file names mention in the events

<img width="772" alt="Screenshot 2023-06-07 at 5 31 07 PM" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/38646828/4e911b2a-fcb0-41ef-bfe9-5d4a495fd2bc">
<img width="921" alt="Screenshot 2023-06-07 at 5 31 51 PM" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/38646828/9cb6998e-be63-4fe8-b566-623eaa2bb7b9">
<img width="921" alt="Screenshot 2023-06-07 at 5 32 11 PM" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/38646828/97fd3d9f-1bbb-40f7-94c6-f263b7860b3e">

**Comment by ramikhafagi96** [comment]
I'd like to add an update, I used sentry-cli explain for an event and this is the output:
```
✔ Fetched data for event: 764d1f0d3fc1463f8e70d431c5540df6
✔ Event has release name: 4.1.0-beta
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
✖ Event exception stacktrace selected frame (0) has incorrect abs_path (valid url is required). Found /2920.js
```

**Comment by ramikhafagi96** [comment]
@lforst No we're not using `RewriteFrames`, I understand that Sentry is using now `debug IDs`. However, it's not working, it's not able to map the error to the corresponding source map, in the second [comment](https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/307#issuecomment-1582422930) it shows that there is a problem in the `abs_path` of the file. I fixed it temporarily by using `uploadLegacySourcemaps`

**Comment by lforst** [comment]
I think the capacitor SDK doesn't support debug IDs yet. `uploadLegacySourcemaps` is the way to go here. We have to update the docs.
