### ISSUE TITLE
SENTRY_RELEASE environment variable is ignored in v2

### ISSUE THREAD

**Issue by andreaswachowski** [getsentry/sentry-javascript-bundler-plugins#316]
### Environment

@sentry/vite-plugin 2.2.2,
@sentry/bundler-plugin-core 2.2.2

### Steps to Reproduce

1. Initialize the environment variable SENTRY_RELEASE with a value
2. Execute a build with vite.config.ts including a configuration that uses sentryVitePlugin to upload source maps, but does not configure the release.name option.

### Expected Result

The release is set to the value in SENTRY_RELEASE.

### Actual Result

The release is set to the abbreviated git commit hash.

### Analysis

The documentation for the release.name option[^1] states

> This value can also be specified via the SENTRY_RELEASE environment variable.

This is incorrect as of v2.2.2. In `normalizeUserOptions`[^2] , we have

```
name: userOptions.release?.name ?? determineReleaseName(),
```

`determineReleaseName`[^3] is using a number of environment variables from CI systems and falls back to `git rev-parse --short HEAD` if possible, but does not take `SENTRY_RELEASE` into account.

This option was lost with d1c6972524fb. Previously, we had[^4]

```
release: userOptions.release ?? process.env["SENTRY_RELEASE"],
```

whereas now, it is[^5]
```
release: {
  name: determineReleaseName(),
```

[^1]: https://www.npmjs.com/package/@sentry/vite-plugin#option-release-name
[^2]: https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/2c8e290ef1b5c3a0f573ceeea25b790b720f7336/packages/bundler-plugin-core/src/options-mapping.ts#L24
[^3]: https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/2c8e290ef1b5c3a0f573ceeea25b790b720f7336/packages/bundler-plugin-core/src/utils.ts#L194
[^4]: https://github.com/getsentry/sentry-javascript-bundler-plugins/commit/d1c6972524fbfc733826b83c2030e455370a9ccb#diff-706dca21c5a067090cc2b6011e4b5d6e7df2e4432c38f13d1eeb1fb34b208e68L82
[^5]: https://github.com/getsentry/sentry-javascript-bundler-plugins/commit/d1c6972524fbfc733826b83c2030e455370a9ccb#diff-706dca21c5a067090cc2b6011e4b5d6e7df2e4432c38f13d1eeb1fb34b208e68R23

**Comment by lforst** [comment]
Hi, thanks for raising this. I think this was just an oversight. We'll add it back in the next release.

For now, as a temporary workaround, you can just manually pass `release: { name: process.env.SENTRY_RELEASE }` to the plugin.

**Comment by jiaodingding** [comment]
Can you share your configuration  for sentryVitePlugin.

**Comment by andreaswachowski** [comment]
@jiaodingding In the excerpt below, the essential part regarding this issue is (as suggested by lforst above) the `release: ...` part. With that, the SENTRY_RELEASE environment variable is used.

```
sentryVitePlugin({
  url: process.env.SENTRY_URL,
  org: process.env.SENTRY_ORG,
  project: process.env.SENTRY_PROJECT,
  authToken: process.env.SENTRY_AUTH_TOKEN,
  release: {
    name: process.env.SENTRY_RELEASE
  }
})
```

Alas, a blocker for me to use the current version v2.2.2 is https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/289, because our Sentry on-premises version (21.12) is apparently too old. I have not found a working configuration.
