### ISSUE TITLE
Add a way to configure the plugins via an external file

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-javascript-bundler-plugins#332]
In `v2` of the bundler plugins we got rid of the functionality to configure the plugins with a [`.sentryclirc` file](https://docs.sentry.io/product/cli/configuration/#to-authenticate-manually). We wanted to abstract away as much as possible that Sentry CLI is used under the hood. It allowed us to reduce complexity and be way more specific in the error messages we print.

When working on a [source map CLI wizard](https://github.com/getsentry/sentry-wizard/issues/290), we noticed that we need a file that we can `gitignore` and put an auth token into for a quick setup.

We thought about bringing back `.sentryclirc` but that would leave us with the drawbacks we steered away from in `v2`. So now we decided to go with a new file that aims to be a bit more clear in what it does when paired with the bundler plugins:

`.env.sentry-build-plugin`

We settled for the `.env` file format because it is the config format that JS devs are most used to besides `.json`. We explored other names for the file:

- `.env.sentry` (too generic)
- `.env.sentry-vite-plugin` (complexity across bundlers, also complicated to document)
- `.env.sentry-plugin` (might be confused with SDK configuration)
- `.env.sentry-ci` (plugins can run locally too, not just in CI)
- `.env.sentry-auth` (too specific - we could have other things in that config too)
- `.env.sentry-sourcemaps` (too specific - it's not just about source maps)

---

The plan is to just dump all environment variables inside `.env.sentry-build-plugin` onto `process.env` when a plugin is initialized.

We also want to print a log message when a `.env.sentry-build-plugin` file is loaded.

For now, we only want to look for the file in `process.cwd()`. We thought about doing the discovery with an upwards folder search but that comes with complications, like how do you disable searching upwards when you don't want to use a higher nested config etc.

We also thought about adding something like an `envFile` option. For now, we don't see it as necessary, as alternative people can just provide all the values that would be inside `.env.sentry-build-plugin` manually as options. The main use case for this functionality is the source map wizard.

**Comment by nemoDreamer** [comment]
> We wanted to abstract away as much as possible that Sentry CLI is used under the hood.

But why, tho?

Since the Sentry UI tells folks to run `sentry-cli sourcemaps ...` to debug their issues, we anyway have to have a `.sentryclirc` locally.

Now I have to provide our config using 2 different mechanisms, on the same machine... 😭

**Comment by lforst** [comment]
> But why, tho?

@nemoDreamer explaining to people how source maps work so they end up being correctly uploaded is hard enough already. We wanted to avoid confronting them with yet another tool. For you, everything might be obvious since you likely spent some time with source maps and Sentry already. For newly onboarding users though, we found bringing Sentry CLI into the picture might be confusing.

> We want to be able to do local testing with the CLI, but also use the same config file in CI (where we have to add the auth token from CI secrets).

@JannikGM wouldn't environment variables solve this use case for you?

> Please put information in the migration guide and what best practices should be followed now.

@JannikGM Honestly I don't know myself what the best practices should be. We provide different ways of configuring the plugin. Pick one and you're (hopefully) good to go 😁. It's not like we can remove or change the configurations anyhow without doing a major bump so you should be fine for quite a while!

**Comment by MSerj** [comment]
for some reason process.env.SENTRY_ENV isn't loaded from the file correctly, so such a config will just fail to start.
```
sentryVitePlugin({
  release: {
    deploy: { env: process.env.SENTRY_ENV }
  }
})
```
However if we pass it via command line like `set SENTRY_ENV=DEV && vite` it does work.
