### ISSUE TITLE
SourceMap  how to set urlPrefix

### ISSUE THREAD

**Issue by KobeZhou** [getsentry/sentry-javascript-bundler-plugins#336]
My question :
my project 's static  assets is on CDN, and the cdn url is dynamic， for example： this time， the url is    http:// XX.com/dist/1/static/js,   next time building,  the  url is http:// XX.com/dist/2/static/js;    so,   how to set the urlPrefix.

**Comment by lforst** [comment]
Hi, please use the latest version of the bundler plugin and the latest version of the SDK and this should work without urlPrefix. Thanks!
