### ISSUE TITLE
[Error] Vite build with sourcemap upload but got Syntax Error 

### ISSUE THREAD

**Issue by KeithChou** [getsentry/sentry-javascript-bundler-plugins#337]
### Environment

node v16.16.0

What version are you running? Etc.

"@sentry/vite-plugin": "^2.2.1"
 "html2canvas": "^1.4.1",

### Steps to Reproduce

In my project, I used the Vite to build. everything gonna normal until I import the html2canvas library dynamically.

the code like the following code
```
const upload = async () => {
    const html2canvas = (await import('html2canvas')).default
    html2canvas(el, (canvas) => {
        // do something
   })
  }
```

and the @sentry/vite-plugin configuration. BTW, I only used two plugin, another one is @vitejs/plugin-react'
```
return sentryVitePlugin({
    org: 'sentry',
    project: 'project',
    url: 'url',
    authToken: 'auth token',
    release: {
      name: process.env.SENTRY_RELEASE_VERSION,
    }
  })
```

when executing `vite build`, it occurred something like `Caused by: Syntax Error`
<img width="1271" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/18112461/a5d55c6b-8477-44a0-99eb-4f33c95c3c21">

I formatted the code and found that the sentry injected some codes into the html2canvas' code
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/18112461/c93fea64-155f-4ecf-a1a1-f83d14d8a32f)

I did not what happened to this, and I tried to found the reason from the sentry website, and it gave me the relevant answer.
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/18112461/95b5797f-45aa-4728-94ff-d354b7f42362)

can I know how to solve this issue, hope for a response, thank a lot!

### Expected Result

build successfully when
1. import html2canvas dynamically
2. upload sourcemap with @sentry/vite-plugin. BTW, **we use the self-hosted** 

### Actual Result

`Caused by: Syntax Error`

**Comment by lforst** [comment]
Hey, thanks for writing in. To debug these kinds of errors we need a reproduction example. A small github repo we can clone is more than enough. Thanks!

**Comment by lforst** [comment]
Ah, I think this is a bug in version `2.2.1`. Should be fixed in the newest version (2.4.0)!

**Comment by KeithChou** [comment]
> Ah, I think this is a bug in version `2.2.1`. Should be fixed in the newest version (2.4.0)!

hi, Iforst, thank you for your quick response! I really appreciate it! 😀😀😀. 

Can I know if is there any incompatible logic when I upgrade from version `2.2.1` to the newest one?

**Comment by lforst** [comment]
Nope should be all compatible: https://semver.org/

**Comment by KeithChou** [comment]
> yeah should be all compatible: https://semver.org/

ok, get it. thx!🤟🤟🤟

**Comment by KeithChou** [comment]
> > yeah should be all compatible: https://semver.org/
> 
> ok, get it. thx!🤟🤟🤟

let me try for the newest version `2.4.0`

**Comment by KeithChou** [comment]
> > > yeah should be all compatible: https://semver.org/
> > 
> > 
> > ok, get it. thx!🤟🤟🤟
> 
> let me try for the newest version `2.4.0`

@lforst hi Iforst, it gonna ok now when I use version `2.4.0`. Thx: )

**Comment by lforst** [comment]
I think this is resolved. Let us know if there are still any issues :)
