### ISSUE TITLE
Conflicting information about sourcemap upload

### ISSUE THREAD

**Issue by oliversalzburg** [getsentry/sentry-javascript-bundler-plugins#338]
<https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/packages/bundler-plugin-core/src/types.ts#L88-L91> says:

```js
  /**
   * Options for source maps uploading.
   * Leave this option undefined if you do not want to upload source maps to Sentry.
   */
```

This seems to indicate pretty clearly that sourcemap will not be uploaded if `sourcemaps` is left `undefined`.

The documentation at <https://docs.sentry.io/platforms/node/sourcemaps/uploading/esbuild> seems to ignore this, and sets no `sourcemaps`, which would prevent sourcemap uploading, which seems counter-intuitive, given that esbuild was instructed with `sourcemap: true` here.

Which is it?

I'm trying to troubleshoot why I'm not seeing source code for stack traces on Sentry and this conflicting information makes it hard to determine if anything is working as intended.

**Comment by lforst** [comment]
Ah, you're right, this comment is a leftover from a previous version. We should remove it.
