### ISSUE TITLE
`release` option ignored

### ISSUE THREAD

**Issue by lsmith77** [getsentry/sentry-javascript-bundler-plugins#340]
### Environment

What version are you running? Etc.

### Steps to Reproduce

```
const sentryWebpackPluginInstance =
  process.env.SENTRY_SOURCEMAPS && process.env.SENTRY_AUTH_TOKEN
    ? sentryWebpackPlugin({
      org: "...",
      project: "...",
      authToken: process.env.SENTRY_AUTH_TOKEN,
      release: `${process.env.VERSION_STRING}-${target}-${nodeEnv}`,
      cleanArtifacts: true,
    })
    : () => {
      this.apply = () => { };
    };
```

### Expected Result

Release should be derived from `${process.env.VERSION_STRING}-${targetBrowser}-${nodeEnv}`

### Actual Result

Release is derived as if no `release` option would be set (ie. uses the output of sentry cli release)

**Comment by nemoDreamer** [comment]
v2 introduced so many breaking changes, with no change-log or migration guide in sight... "if you previously used plain `release` String, you now need to provide x y & z"

**Comment by lsmith77** [comment]
> What version of the plugin are you using?

`"@sentry/webpack-plugin": "^2.4.0"`

> **CORRECTION:** change-log / migration guide is at the root of the repo, not in each plug-in's sub-folder. My bad!

Looking at https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/MIGRATION.md and https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/CHANGELOG.md I don't see the relevant information.

**Comment by lsmith77** [comment]
let's see if this works, ie. `release.name` https://www.npmjs.com/package/@sentry/webpack-plugin
