### ISSUE TITLE
nuxt build failed with sentry and browserify polyfills

### ISSUE THREAD

**Issue by janhmeyer** [getsentry/sentry-javascript-bundler-plugins#342]
### Environment

Linux with Node 18

### Steps to Reproduce

1. Install nuxt 3 base
2. Use vite
3. Use vite plugin with vite-plugin-node-polyfills
4. Use sentry Plugin
5. "nuxt build" fails

Does not happen, when using polyfills or sentry separately.

### Expected Result

build success

### Actual Result

 ERROR  "sentry-release-injection-file" is imported as an external by "browserify-sign/algos.js?commonjs-external", but is already an existing non-external module id.                                                                                                16:08:04

 ERROR  "sentry-release-injection-file" is imported as an external by "browserify-sign/algos.js?commonjs-external", but is already an existing non-external module id.                                                                                                16:08:04

  at error (node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)

**Comment by lforst** [comment]
Hi, I don't know why this might be happening. Do you mind raising an issue over at https://github.com/davidmyersdev/vite-plugin-node-polyfills? My suspicion/suggestions is that they would need to ignore virtual modules injected by other plugins similar to the fix in `rollup-plugin-commonjs` here: https://github.com/rollup/rollup-plugin-commonjs/pull/327.

**Comment by janhmeyer** [comment]
Thank you, I will raise the issue there.
