### ISSUE TITLE
Sentry Vite-plugin failing to upload sourcemaps

### ISSUE THREAD

**Issue by lokeshwarobuli** [getsentry/sentry-javascript-bundler-plugins#343]
### Environment
Node - 18.16.0

What version are you running? Etc.
"@sentry/vite-plugin": "^2.4.0"
"@sentry/browser": "^7.57.0",
"@sentry/react": "^7.57.0",
"@sentry/tracing": "^7.57.0",

### Steps to Reproduce
1. I am using Vite with react. I was getting the following error in the sentry dashboard

<img width="811" alt="Screenshot 2023-07-11 at 8 32 59 PM" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/85650351/9b262953-bc36-49de-b957-473354a2bd6b">

2. Then I followed the documentation which was in the URL https://docs.sentry.io/platforms/node/guides/connect/sourcemaps/uploading/vite/ 

3. The URL said it won't run in dev mode, so I ran yarn build to build the prod build. But it kept on failing with the following message
<img width="1127" alt="Screenshot 2023-07-11 at 8 36 01 PM" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/85650351/ababc910-c1a3-4720-812b-b19239739796">

### Expected Result
I though it would upload the source map along with it in the build folder

### Actual Result
It is even failing to do the build. I have also attached the vite.config.ts here for your reference
```
/// <reference types="vitest" />
import linaria from '@linaria/vite';
import { sentryVitePlugin } from '@sentry/vite-plugin';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    outDir: 'build',
    sourcemap: true,
  },
  plugins: [
    react(),
    linaria(),

    // Put the Sentry vite plugin after all other plugins
    sentryVitePlugin({
      org: 'foo',
      project: 'foo-web',
      authToken: process.env.VITE_APP_SENTRY_AUTH_TOKEN,
    }),
  ],
  test: {
    globals: true,
    environment: 'jsdom',
    globalSetup: './src/test-globals.ts',
    setupFiles: './src/setupVitest.ts',
  },
  server: {
    port: 3000,
    host: '0.0.0.0',
    open: true,
  },
});
```

**Comment by lokeshwarobuli** [comment]
Any update on this ??

**Comment by lforst** [comment]
Thanks for writing in. Can you confirm whether the same error occurs when not using the `linaria()` plugin? Thanks.

**Comment by lforst** [comment]
One additional thing you could try is switching the order of the linaria and sentry plugin.

**Comment by lokeshwarobuli** [comment]
I played the orders with the orders of the plugins but nothing helped but removing linaria

**Comment by lforst** [comment]
Ok I have a feeling this is a problem with linaria then. Would you mind opening an issue in their repository? Thanks!
