### ISSUE TITLE
Vite production build broken after upgrading to @sentry/vite-plugin v2

### ISSUE THREAD

**Issue by GabrielCousin** [getsentry/sentry-javascript-bundler-plugins#356]
### Environment

Created a git repository to ease reproducing https://github.com/GabrielCousin/my-sentry-vite-buggy-app
Basically using react-ts vite template:
- `vite#4.4.7`
- react 18
- typescript
- `@sentry/vite-plugin#2.5.0`

```
import { defineConfig, splitVendorChunkPlugin } from "vite";
import react from "@vitejs/plugin-react";
import { sentryVitePlugin } from "@sentry/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig(({ command }) => ({
  build: {
    sourcemap: true,
    chunkSizeWarningLimit: 2048,
    rollupOptions: {
      output: {
        manualChunks: (fullPathFile: string) => {
          if (
            fullPathFile.includes("libs/i18n") ||
            fullPathFile.includes("node_modules/i18n")
          ) {
            return "i18n";
          }

          return undefined;
        },
      },
    },
  },

  plugins: [
    react(),

    splitVendorChunkPlugin(),

    sentryVitePlugin({
      disable: command === "serve",

      org: process.env.SENTRY_ORG,
      project: process.env.SENTRY_PROJECT,

      // Auth tokens can be obtained from https://sentry.io/settings/account/api/auth-tokens/
      // and need `project:releases` and `org:read` scopes
      authToken: process.env.SENTRY_AUTH_TOKEN,

      release: {
        name: Date.now().toString(),
      },

      sourcemaps: {
        assets: "./dist/**/*",
      },
    }),
  ],
}));
```

### Steps to Reproduce

Locally:
1. Run `npm run build`
2. Run `npm run preview`

### Expected Result

I expected the build process to basically work: building the app, uploading sourcemaps obviously without breaking the project 😄 
We experienced that issue after upgrading from 0.6 to 2.x without really knowing where it could come from.
I suspect the chunk strategy to interfere with Sentry:
- disabling splitVendorChunkPlugin [works](https://github.com/GabrielCousin/my-sentry-vite-buggy-app/pull/2)
- disabling manual chunks [works](https://github.com/GabrielCousin/my-sentry-vite-buggy-app/pull/1)
but… we need these settings to work
Let me know if I can provide further help!
Thank you 🙏 

### Actual Result

When building `npm run build`, all steps are going as expected:
- build completed
- sourcemaps uploaded and visible in the back-office
- the [deployed project](https://my-sentry-vite-buggy-app.vercel.app/) has some unexpected error
![Screenshot 2023-07-28 at 16 16 46](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/7649529/a539fcf6-64a3-4403-b3c5-34092766d5f2)

**Comment by lforst** [comment]
Hey, thanks for writing in. I have narrowed this down to our release injection logic being incompatible with `manualChunks`.

Good news though, there is a workaround. You can set `release.inject: false` in the plugin options and the app should work again.

For whatever reason, having our release injection active will put a `import "./i18n-8da66df6.js";` statement on top of the `vendor-*.js` output which then seems to break the app. I don't quite know why this is happening tbh so I don't have an immediate fix.

Let's see if other people run into this issue!

**Comment by GabrielCousin** [comment]
Thank you for the details and the workaround!

**Comment by lforst** [comment]
I forgot to mention. In case you disable the release injection you manually need to set a `release` value in `Sentry.init()` in case you want to track releases in Sentry!
