### ISSUE TITLE
Angular with custom webpack settings hangs on build when using .scss

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-javascript-bundler-plugins#357]
### Environment

Angular 14.2, but issue exists in Angular 16 as well
`@angular-builders/custom-webpack` 14.1.0
`@sentry/webpack-plugin` 2.4.0

### Steps to Reproduce
[Repro provided by user](https://github.com/TobyBladen/sentry-bug-reproduce)

1. npm install
2. npm run build

### Expected Result

webpack plugin terminates itself after upload

### Actual Result

terminal hangs forever unless force closed - 

<img width="400" alt="Screenshot 2023-07-28 at 10 55 21 AM" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/96670625/128cb056-a65c-4f0a-bc36-529f0126cbc0">

Changing all instances of `scss` to `css` and then running the build solves the issue.  

1 . change filename `app.component.scss` to `app.component.css`
2. change filename `styles.scss` to `styles.css`
3. In `app.component.ts`, change `styleUrls: ['./app.component.scss']` to  `styleUrls: ['./app.component.css']`
4. In `angular.json`, change `"styles": ["src/styles.scss"],` to `"styles": ["src/styles.css"],`

**Comment by sebheitzmann** [comment]
+1 . We have the same pb. Any Idea ?

**Comment by lforst** [comment]
The recommended workaround for now is to use Sentry CLI instead of the webpack plugin.

**Comment by jobejas** [comment]
@lforst is there a way to use `thirdPartyErrorFilterIntegration` with Sentry CLI instead of webpack?

**Comment by lforst** [comment]
@jobejas No there is not but you can use the `allowUrls` option in `Sentry.init()` which achieves similar effects.

**Comment by AbhiPrasad** [comment]
Closing this issue for clean-up. Please re-open if it still applies. Thanks!
