### ISSUE TITLE
Sourcemaps not available after successful Sentry vite-plugin upload

### ISSUE THREAD

**Issue by creckord** [getsentry/sentry-javascript-bundler-plugins#360]
### Environment

What version are you running? Etc.

```
$  npm version
{
  npm: '9.6.7',
  node: '20.3.1',
  ...
}

$ npm ls -D vite @sentry/vite-plugin rollup
├── @sentry/vite-plugin@2.5.0
├─┬ @vitejs/plugin-react@4.0.3
│ └── vite@4.4.7 deduped
├─┬ vite-plugin-eslint@1.8.1
│ └── vite@4.4.7 deduped
├── vite@4.4.7
├── rollup@3.26.3

```

vite.config.js:
```
import {defineConfig} from 'vite';
import react from '@vitejs/plugin-react';
import browserslistToEsbuild from 'browserslist-to-esbuild';
import { sentryVitePlugin } from "@sentry/vite-plugin";

export default defineConfig(() => {
    return {
        base: '/myproject/',
        plugins: [
            react(),
            sentryVitePlugin({
                authToken: process.env.SENTRY_AUTH_TOKEN,
                org: "myorg",
                project: "my-project",
                url: "https://sentry-selfhosted.example.org/",
                debug: true,
                release: {
                    name: "my-test-release",
                    setCommits: {
                        auto: true,
                    }
                },
            }),
        ],
        build: {
            outDir: 'build',
            sourcemap: true,
            target: browserslistToEsbuild(),
        },
    };
});
```
### Steps to Reproduce

I just ran an `npm run build`, which does a `vite build`

### Expected Result

A release is created, commits are added, and bundled sources and sourcemaps from the build are uploaded and associated with the release.

### Actual Result

The release was created, as were the commits.

Locally, the source bundle files and sourcemaps were identified and - according to the logs - successfully uploaded.

In the UI however, there were no artifacts. Looking at the release page for the newly created release, it claimed to have some artifacts:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/393429/28edfb8b-5aa6-4199-8beb-af556a434022)

Clicking on the link, or navigating to the project's sourcemaps page however, the sourcemaps archive for the release was present, but empty (artifacts -1):
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/393429/2b2dd18d-5db8-40c3-80e9-9ecbcc5bdd47)
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/393429/15b1bb89-ccce-46d6-9d86-a95e09e1c60e)

Relevant npm build logs:
```
[sentry-vite-plugin] Debug: No `sourcemaps.assets` option provided, falling back to uploading detected build artifacts.
build/index.html                     3.15 kB │ gzip:   1.43 kB
build/assets/index-5fa0a054.css    263.86 kB │ gzip:  36.77 kB
build/assets/index-062d6867.js   1,297.09 kB │ gzip: 451.66 kB │ map: 6,511.39 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

> Found 2 files
> Analyzing 2 sources
> Analyzing completed in 0.009s
> Adding source map references
> Bundling completed in 0.239s
> Bundled 2 files for upload
> Bundle ID: e106fb55-4dc7-5583-b0e2-87d0983ab202
> Optimizing completed in 0.012s
> Uploading completed in 0.542s
> Uploaded files to Sentry
> Processing completed in 0.163s
> File upload complete (processing pending on server)
> Organization: dpa
> Project: nextar-frontend
> Release: 00002-8b0576e
> Dist: None
> Upload type: artifact bundle

Source Map Upload Report
  Minified Scripts
    ~/3d13895f-7dfc-4882-9a3d-6a322b0f3d6f-0.js (sourcemap at index-062d6867.js.map, debug id 3d13895f-7dfc-4882-9a3d-6a322b0f3d6f)
  Source Maps
    ~/3d13895f-7dfc-4882-9a3d-6a322b0f3d6f-0.js.map (debug id 3d13895f-7dfc-4882-9a3d-6a322b0f3d6f)
[sentry-vite-plugin] Info: Successfully uploaded source maps to Sentry
```

**Comment by creckord** [comment]
I also tried to upload the files manually with the sentry-cli:

```
sentry-cli sourcemaps upload --org myorg -p my-project -r my-test-release build/assets/index-1fa5b6ed.js build/assets/index-1fa5b6ed.js.map
```

This worked as expected, and the artifacts did show up in the frontend.

So I ran both the vite build and the sentry-cli again with debug logging, and noticed that the upload process only differed in the final step.

npm build api calls:
```
request GET https://sentry-selfhosted.example.org/api/0/organizations/myorg/chunk-upload/
request GET https://sentry-selfhosted.example.org/api/0/projects/myorg/my-project/releases/00003-8b0576e/files/?cursor=&checksum=7cc8f65a3d81e5113577cfea968978ab85989de9&checksum=8e6181debbe290d99e44fdc7c91fd12fd6700218
request POST https://sentry-selfhosted.example.org/api/0/organizations/myorg/chunk-upload/
request POST https://sentry-selfhosted.example.org/api/0/organizations/myorg/artifactbundle/assemble/
json body: {"checksum":"97221e46ad5c165ea21a4c02bf178a61661ade33","chunks":["97221e46ad5c165ea21a4c02bf178a61661ade33"],"projects":["my-project"],"version":"my-test-release"}
```

sentry-cli api calls:
```
request GET https://sentry-selfhosted.example.org/api/0/organizations/myorg/chunk-upload/
request POST https://sentry-selfhosted.example.org/api/0/projects/myorg/my-project/releases/
request GET https://sentry-selfhosted.example.org/api/0/projects/myorg/my-project/releases/00003-8b0576e/files/?cursor=&checksum=6187aa85706aae14f76500c6155ee4b39e1a55ee&checksum=9a41bc164614d753421cdb19ad643783abf40036
request POST https://sentry-selfhosted.example.org/api/0/projects/myorg/my-project/releases/
request POST https://sentry-selfhosted.example.org/api/0/organizations/myorg/chunk-upload/
request POST https://sentry-selfhosted.example.org/api/0/organizations/myorg/releases/my-test-release/assemble/
json body: {"checksum":"945d281ed7be81b36b1f77e1a927cb3e2d08b505","chunks":["945d281ed7be81b36b1f77e1a927cb3e2d08b505"]}
```

Aside from sentry-cli making the POST call to create the release twice, the salient difference seems to be the `assemble` call in the end: 

`/api/0/organizations/myorg/artifactbundle/assemble/` with project and version in the body (not working) vs
`/api/0/organizations/myorg/releases/my-test-release/assemble/` with just the checksum and chunks (working).

If I replicate the working assemble post with the chunk data from the /artifactbundle/assemble/ call using curl, those files show up as well.

**Comment by creckord** [comment]
I just tried downgrading to @sentry/vite-plugin@2.4.0, but same issue.

**Comment by creckord** [comment]
Hm, I can confirm that it works with the legacy sourcemaps (had to disable the non-legacy ones with an explicit `assets: []` so it wouldn't attempt the non-legacy upload as well).

However, our Sentry version is `23.6.1` (rolled out via this Helm chart https://github.com/sentry-kubernetes/charts, version 19.3.0). So I would have assumed that the non-legacy upload should have worked.

**Comment by lforst** [comment]
Oh yeah, I think we need to update these docs. The relevant PR is https://github.com/getsentry/sentry/pull/52102 and that is only part of `23.6.2`.

Would you mind upgrading to `23.6.2` (or newer) and verifying if the upload works without the legacy uploading method?

**Comment by creckord** [comment]
Not easily. Let me get back to you next week, if I can schedule an update in the short run. Unfortunately, there is no chart for 23.6.2, and the next chart version, featuring Sentry 23.7.1, has some breaking changes.

**Comment by creckord** [comment]
Scratch that, I found a deployment to play with, and can confirm that after upgrading to 23.6.2, the non-legacy sourcemap upload works great. Thanks you.

**Comment by lforst** [comment]
Glad you could resolve the issue :D I am still kinda cautiously curious what the original issue might have been 🤔

**Comment by creckord** [comment]
Well, the interesting bit is that the archive files were present in the shared data directory. But somehow, despite the assemble call, Sentry didn't seem to be aware of them.

But I guess with newer versions working, it's a bit of a moot point 😅

**Comment by jyuloeng** [comment]
I tried to upload using sentry-cli, why is the number of pages viewed still 0 after success?
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/52498784/93e4cb5d-6f67-435e-9be6-2382d72da1ef)
<img width="1168" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/52498784/3fa550b9-9bd6-4e8c-ab0f-f91aa3d0e764">

**Comment by lforst** [comment]
@jyuloeng With the plugin you're uploading artifact bundles. This is a bit confusing but you can basically ignore release bundles.

**Comment by jyuloeng** [comment]
> @jyuloeng With the plugin you're uploading artifact bundles. This is a bit confusing but you can basically ignore release bundles.

Yeah, but which difference with artifact bundles and release bundles in sentry sourcemap？Any docs here?

**Comment by lforst** [comment]
> > @jyuloeng With the plugin you're uploading artifact bundles. This is a bit confusing but you can basically ignore release bundles.
> 
> Yeah, but which difference with artifact bundles and release bundles in sentry sourcemap？Any docs here?

https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/artifact-bundles/

**Comment by Hello-GBY** [comment]
> > @jyuloeng With the plugin you're uploading artifact bundles. This is a bit confusing but you can basically ignore release bundles.
> 
> I got the same result with the latest vite sentry plugin...QAQ

Please tell me how you solved it. I also encountered this problem.

**Comment by jyuloeng** [comment]
> > > @jyuloeng With the plugin you're uploading artifact bundles. This is a bit confusing but you can basically ignore release bundles.
> > 
> > 
> > I got the same result with the latest vite sentry plugin...QAQ
> 
> how you solved it. I also encountered this problem. help me , brother @jyuloeng

这个问题我也不知道怎么解决的老哥，我们是暂时把 sentry 从自建服务切换到了 sentry 云上就好了。。后面还得再排查下，你们有结论的话麻烦也 cue 我下谢谢～🙏

**Comment by jyuloeng** [comment]
> > > @jyuloeng With the plugin you're uploading artifact bundles. This is a bit confusing but you can basically ignore release bundles.
> > 
> > 
> > I got the same result with the latest vite sentry plugin...QAQ
> 
> how you solved it. I also encountered this problem. help me , brother @jyuloeng

噢噢还有一个就是我们把项目里的 sentry 都升级到了最新版本

**Comment by Hello-GBY** [comment]
> > > > @jyuloeng With the plugin you're uploading artifact bundles. This is a bit confusing but you can basically ignore release bundles.
> > > 
> > > 
> > > I got the same result with the latest vite sentry plugin...QAQ
> > 
> > 
> > how you solved it. I also encountered this problem. help me , brother @jyuloeng
> 
> 噢噢还有一个就是我们把项目里的 sentry 都升级到了最新版本

oh, I'm trying to figure out how to fix this without upgrading, I try try.

**Comment by TheNovemberRain** [comment]
> > > > @jyuloeng With the plugin you're uploading artifact bundles. This is a bit confusing but you can basically ignore release bundles.
> > > 
> > > 
> > > I got the same result with the latest vite sentry plugin...QAQ
> > 
> > 
> > how you solved it. I also encountered this problem. help me , brother @jyuloeng
> 
> 这个问题我也不知道怎么解决的老哥，我们是暂时把 sentry 从自建服务切换到了 sentry 云上就好了。。后面还得再排查下，你们有结论的话麻烦也 cue 我下谢谢～🙏

只要满足下列条件，所有上传的sourcemap将不会作为Release Bundles。
1. @sentry/webpack-plugin 2.x至最新
2. sentry-cli version 2.16.2至最新
3. 自托管Sentry 23.6.2至最新
Release Bundles是个历史功能，以往sourcemap是与版本强绑定的，一个版本只允许存在一套sourcemap。23.6.2开始使用Artifact Bundles的方式管理工件。根据[官方文档](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/artifact-bundles/)的解析，插件在上传sourcemap时会对当前构建的每个代码文件生产全局唯一的Debug ID，并改动已构建的代码，往里面插入以`e._sentryDebugIds=e._sentryDebugIds||{}`开始的代码，以标识该文件的Debug ID。这意味着版本不再与sourcemap强绑定，一个版本是可以存在多套sourcemap的。
所以上面有个老哥跟你说you can basically ignore release bundles.

**Comment by Hello-GBY** [comment]
大佬，请问怎么做啊？
我现在自托管版本 是 23.7.1。 在vite中 提示是 Artifact Bundles上传，并且提示上传成功，但是sentry服务端没有看到上传的包。

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/65537456/17a29fe7-9a9b-46b5-a9bd-238862e05b0a)

但在sentry服务上没有上传产物
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/65537456/f276ee82-1cd8-45e1-89fc-c1b437aba706)

大佬，请教请教

**Comment by TheNovemberRain** [comment]
> 大佬，请问怎么做啊？ 我现在自托管版本 是 23.7.1。 在vite中 提示是 Artifact Bundles上传，并且提示上传成功，但是sentry服务端没有看到上传的包。
> 
> ![image](https://user-images.githubusercontent.com/65537456/284458423-17a29fe7-9a9b-46b5-a9bd-238862e05b0a.png)
> 
> 但在sentry服务上没有上传产物 ![image](https://user-images.githubusercontent.com/65537456/284458606-f276ee82-1cd8-45e1-89fc-c1b437aba706.png)
> 
> 大佬，请教请教

这比较奇怪，你可以试试升级自托管sentry的版本至最新，或者将sentry vite plugin降级到23.7.1发布时间附近的版本。
也可以试试设置sentry vite plugin中release的name。
如果都不行的话，得查服务器日志了。
