### ISSUE TITLE
process.env undefined when I use sentryWebpackPlugin 

### ISSUE THREAD

**Issue by daigang1228** [getsentry/sentry-javascript-bundler-plugins#367]
### Environment

What version are you running? MAC.

@sentry/webpack-plugin 2.5.0

### Steps to Reproduce

const { sentryWebpackPlugin } = require('@sentry/webpack-plugin')

new DefinePlugin({ 'process.env': envConfig })

I modified my process.env as follows when I configured sentryWebpackPlugin.
 I found that in my JS code, process.env reported an error, process undefined
 
### Expected Result
process.env Cannot be changed by plugins

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by daigang1228** [comment]
Hello @lforst 
when you use 
 DefinePlugin({ 'process. env': envConfig }).

Normally you can access process.env in your JS code.

But after adding @sentry/webpack-plugin 2.5.0, you can't access the process.
process => undefined

**Comment by ilijapuaca** [comment]
Seeing the same issue after upgrading esbuild to >0.19.0, when Sentry plugin is used app crashes with `Uncaught ReferenceError: process is not defined` and otherwise works fine without it
