### ISSUE TITLE
0 artifacts in sentry after "File upload complete"

### ISSUE THREAD

**Issue by taoran34** [getsentry/sentry-javascript-bundler-plugins#386]
### Environment

node@16.14.2
webpack@3.12.0
@sentry/vue@6.11.0
@sentry/webpack-plugin@1.20.1

### Steps to Reproduce

I configured sentry webpack plugin following the docs.
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/9361046/8b305716-bfd1-425a-a35d-f768154743b8)

And ran build, showed "File upload complete" and "Source Map Upload Report".
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/9361046/db4931a2-f9c0-461a-9a42-ce5ee0cf0117)

### Expected Result

I thought source maps were uploaded.

### Actual Result

But "There are no artifacts in this archive." in sentry.
<img width="1416" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/9361046/d50eed98-9815-47a9-a8b3-fb17d8501a86">

**Comment by lforst** [comment]
Please upgrade to the latest self-hosted versions.

Our docs show compatibility requirements: https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/
