### ISSUE TITLE
Separating the injection and upload steps

### ISSUE THREAD

**Issue by tom2strobl** [getsentry/sentry-javascript-bundler-plugins#387]
Hi there!

I'm using [serverless-webpack](https://www.serverless.com/plugins/serverless-webpack) to bundle serverless functions with webpack. Something smart they have which I use is the ability to run a single webpack-config, but where each serverless function is compiled and packaged individually, which makes sure it only bundles what the function needs and not all of the modules, that enables tree-shaking, makes bundles smaller and improves cold starts.

It uses the [webpack multi-compiler](https://webpack.js.org/api/node/#multicompiler) feature, which kinda means webpack is sort of run over and over again with the same config on different entry points.

Now I _can_ simply throw in `sentryWebpackPlugin()` into my webpack config and it works, but the issue is that I have 30+ functions which means that it will upload 1+2+3+4+5+[...]+30 times the sourcemaps which obviously is quite the strain on both sentry and our machines. To the point where I think I got rate limited and further calls resulted in errors (which kinda makes sense since it looks like bot behavior).

Since I can't expect from you to make `sentryWebpackPlugin` work out of the box in this rather edge-case scenario, I want to replicate the behaviour but I'm not entirely sure how to proceed.

Looking into https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/packages/webpack-plugin/src/index.ts it looks like there are banner injection steps and then the actual upload step.

In `serverless-webpack` I have a serverless `hooks['after:webpack:package']` that I could use to imperatively upload the sourcemaps.

What would be the best way to go about separating injection and upload steps? Or would you suggest to look into a post-build CLI step using `sentry-cli releases files "$VERSION" upload-sourcemaps /path/to/sourcemaps`

**Comment by lforst** [comment]
Writing a plugin is super complex so I don't recommend going that route unless you really really wanna go with that route.

Instead, I recommend using exclusively Sentry CLI. How would that work? (Basically, you need to follow [this tutorial](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/)):
- AFTER you built all your bundles you run the `sentry-cli sourcemaps inject` command on all of your build artifacts. This doesn't require any network calls and should generally be pretty fast.
- After injecting, you can upload all of the files with the `sentry-cli sourcemaps upload` command. You can do this with a simple glob pattern and this will only upload the files once, as opposed to ((n-1)*n)/2 times with the plugin as you described.
- You need to do this every time you deploy your functions.

**Comment by tom2strobl** [comment]
Thanks for swift response, I'll take your suggestion and go the CLI route. I'll close the issue and re-open it in the unlikely case I'm at a dead end.

✌🏻
