### ISSUE TITLE
how to set urlPrefix 

### ISSUE THREAD

**Issue by liufeisprit** [getsentry/sentry-javascript-bundler-plugins#388]
### Environment
@sentry/webpack-plugin@1.18.9
webpack@4.46.0

### Steps to Reproduce
when I build project and upload source Map and I met a mistake `error: An organization slug is required (provide with --org)`。
my config like this. I have setting the org field。
```
new SentryWebpackPlugin({
          deleteAfterCompile: true,
          include: './dist',
          url: 'https://test.com',
          authToken: 'xxx',
          org: 'org',
          project: 'project',
          urlPrefix: '~/first/second',
        })
```
when I used the .sentryclirc file to set the config, then is build success, but the urlPrefix setting is not work。  

### Expected Result
~/first/second/static/js/app.348a1a61.js.map
 ~/first/second/static/js/app.348a1a61.js 
What you thought would happen.

### Actual Result
```
~/static/js/app.348a1a61.js.map
 ~/static/js/app.348a1a61.js 
```

What actually happened. Maybe a screenshot/recording? Maybe some logs?
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/25600325/6f54ed0a-656e-4194-bdaa-b560cec73bf3)

**Comment by liufeisprit** [comment]
When I used webpack plugin with latest version。 The source map path like this。
<img width="900" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/25600325/bca8c807-a6f6-46a9-ad6d-d4df64eb5587">
`urlPrefix` does not take effect。 
When we use Artifact Bundles, does it mean that path matching is not required?

**Comment by lforst** [comment]
> When I used webpack plugin with latest version。 The source map path like this。 <img alt="image" width="900" src="https://user-images.githubusercontent.com/25600325/264327366-bca8c807-a6f6-46a9-ad6d-d4df64eb5587.png"> `urlPrefix` does not take effect。 When we use Artifact Bundles, does it mean that path matching is not required?

Correct, now you need to deploy your app and check whether your events have debug IDs: https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-your-source-files-contain-debug-id-injection-snippets
