### ISSUE TITLE
Upgrade from v1 to v2. Help required.

### ISSUE THREAD

**Issue by n19htz** [getsentry/sentry-javascript-bundler-plugins#389]
We got self-hosted instance sentry running and @sentry/webpack-plugin@1.20.1 with simple setup:
```
new SentryWebpackPlugin({
          include: projectJson.targets.build.options.outputPath,
          release: packageJson.version,
          urlPrefix: `~${projectJson.targets.build.configurations.production.baseHref}`,
          authToken: process.env.NX_SENTRY_AUTH_TOKEN,
          dryRun,
          setCommits: {
            auto: true,
          },
          deploy: {
            env: 'production',
          },
        })
```

and everything works just fine.

Now I want to upgrade to latest version of @sentry/webpack-plugin@2.x.x and thats where problems begin. Basically no documentation and examples for v2. Thats my results so far:

```
 sentryWebpackPlugin({
      org: process.env.NX_SENTRY_ORG,
      project: process.env.NX_SENTRY_PROJECT,
      authToken: process.env.NX_SENTRY_AUTH_TOKEN,
      url: process.env.NX_SENTRY_URL,
      telemetry: false,
      debug: true,
      sourcemaps: {
        assets: `${projectJson.targets.build.options.outputPath}/**/*.{js,js.map}`,
      },
      release: {
        name: packageJson.version,
        inject: true,
        create: true,
        setCommits: {
          auto: true,
        },
        deploy: {
          env: 'production',
        },
      },
    }),
```

It uploads js files and maps files, but their names corrupted by randomly generated hash with increment (look at screen below). So at the end, these sourcemaps are useless.

<img width="1371" alt="Screenshot 2023-08-25 at 17 48 37" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/39006390/b8b1a23f-23d7-4f5e-a314-fb714b167277">

Could anybody help me convert config v1 to v2 please?

**Comment by lforst** [comment]
Did you try deploying your app and seeing if the errors get unminified yet? To me nothing here looks wrong.

**Comment by n19htz** [comment]
> Did you try deploying your app and seeing if the errors get unminified yet? To me nothing here looks wrong.

yes, deployed and errors showing minified blocks of code. We got lots of different domains where our app is deployed, like ```xx1.domain.com/web/, xx2.domain.com/web/, ... xx100.domain.com/web/``` in this case I need to prefix sourcemap with ```~/web/<filename>.js.map```, but I don't understand how to do it via v2 api. And names of files is not the real file names generated by build.

Also, if I upload via ```sentry-cli sourcemap``` the filenames of ```.js``` and ```.js.map``` files  are correct, but still can't get prefix to work
