### ISSUE TITLE
Can't link stack trace to the source maps using Docker setup

### ISSUE THREAD

**Issue by petruspierre** [getsentry/sentry-javascript-bundler-plugins#391]
Hello,

I'm trying to setup the source maps with Sentry, but I'm have a hard time doing so.

Here's my Sentry config in Webpack:

```js
sentryWebpackPlugin({
  org: process.env.SENTRY_ORG_NAME,
  project: process.env.SENTRY_PROJECT_NAME_API,
  authToken: process.env.SENTRY_AUTH_TOKEN,
  debug: true,
  release: {
    name: `${process.env.ENVIRONMENT}-${process.env.CI_COMMIT_SHORT_SHA}`,
  },
  sourcemaps: {
    assets: "./dist/**"
  },
  disable: !generateSourceMaps
}),
```

and I have `devtool: "source-map"` set in my webpack config

The upload is working fine, I can see the files in Sentry:

<img width="805" alt="Screenshot 2023-08-28 at 20 39 10" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/39802870/5d155582-579e-4113-a96c-14ee3fc24ecb">

However, it can't link to the actual stack trace in the Events:

<img width="688" alt="Screenshot 2023-08-28 at 20 39 53" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/39802870/18f0ad10-b15e-4222-bc95-0c1f9694e693">

I can assure the event's release matches the release with the source maps artifacts in it.

Something I can note is:

I have a Dockerfile for building my app, and in it I use a `WORKDIR /home/node/app`. The source maps, in the other side, are not generated in the Dockerfile build, as I didn't want to expose the variables when calling webpack build, so the webpack build won't use the Sentry plugin, but it shouldn't matter as the release version name matches.

I also tried using the `uploadLegacySourcemaps` option, but again, the assets were uploaded but didn't link to the stack trace

So my question is:
**How can I link the source codes uploaded to Sentry (~/7487c099-c432-46ac-a682-fb3f558ec0e8-0.js.map) with the path I currently see in the stack trace (/home/node/app/dist/bundle.js)?** 

Versions used:
"@sentry/node": "^7.65.0"
"@sentry/tracing": "^7.65.0"
"@sentry/webpack-plugin": "^2.7.0"

**Comment by lforst** [comment]
If you use the webpack plugin, you **need** to deploy the same files that were generated using the Sentry webpack plugin. Reason being that the plugin injects debug IDs into your bundles that are used during runtime for source maps resolution.

`release.uploadLegacySourcemaps` is the right approach if you want an alternative. It will upload files without injecting debug IDs. The annoying part is that you now have to match the stack frame filenames with the names of the uploaded artifacts, which usually requires a bit of playing around.

If you want my recommendation: Just use the Sentry plugin inside your docker builds. I think there is a way of passing build arguments without them being stored in the image.

**Comment by lforst** [comment]
@petruspierre thanks for providing an update! If you have any suggestions on how this use case can be improved, let us know!
