### ISSUE TITLE
All readme files missing options

### ISSUE THREAD

**Issue by Stanzilla** [getsentry/sentry-javascript-bundler-plugins#400]
All the readme files (https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/packages/webpack-plugin/README_TEMPLATE.md for example) are missing their options sections, seems like the generation script did not insert them. Also they should be called README.md so GitHub renders them properly when browsing to the folder.

**Comment by lforst** [comment]
The docs for the packages in this repo can be found on the respective npm pages (eg. https://www.npmjs.com/package/@sentry/vite-plugin). We do not maintain readmes for the packages inside github.

**Comment by Stanzilla** [comment]
> The docs for the packages in this repo can be found on the respective npm pages (eg. [npmjs.com/package/@sentry/vite-plugin](https://www.npmjs.com/package/@sentry/vite-plugin)). We do not maintain readmes for the packages inside github.

Aw, sad. The UX on GitHub is so much better, is that something you could reconsider?

**Comment by lforst** [comment]
@Stanzilla right now we don't believe it is worth the effort to change. All of our docs point to the npm readme so there is little to gain.
