### ISSUE TITLE
`computing gzip size (0)...[sentry-debug-id-upload-plugin] spawn node_modules/@sentry/cli/sentry-cli ENOENT`

### ISSUE THREAD

**Issue by pattrickrice** [getsentry/sentry-javascript-bundler-plugins#401]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Use yarn workspaces with Yarn Berry
```console
./package.json
./apps/project/package.json <- sentry used here
```
2. yarn install
```console
./package.json
./node_modules/
./apps/project/package.json
./apps/project/node_modules/
./apps/project/node_modules/node_modules/@sentry/cli/sentry-cli <-exists
```
3. remove nested node_modules ./apps/project/node_modules/
```console
 ./package.json
./node_modules/
./apps/project/package.json
```
4. yarn install
```console
./package.json
./node_modules/
./apps/project/package.json
./apps/project/node_modules/
./apps/project/node_modules/node_modules/@sentry/cli/sentry-cli <-missing!
```

### Expected Result

Successful build with Vite

### Actual Result

```console
➜  frontend git:(master) yarn build
vite v4.0.4 building for production...
✓ 26224 modules transformed.
computing gzip size (0)...[sentry-debug-id-upload-plugin] spawn /home/price/.../frontend/node_modules/@sentry/cli/sentry-cli ENOENT
error during build:
Error: spawn /home/price/.../frontend/node_modules/@sentry/cli/sentry-cli ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
 ```

### Product Area

Issues - Source Maps

### Version

@sentry/vite-plugin@npm:2.5.0

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1924) by [Unito](https://www.unito.io)

**Comment by lforst** [comment]
Hi, Sentry CLI uses a post-install script to install its binary. Can you check whether you have post install scripts disabled somehow? Thanks!

Otherwise, can you please share a small reproduction repo where this is happening? Thanks!

**Comment by loewenheim** [comment]
Possibly related? https://github.com/getsentry/sentry-cli/issues/1731

**Comment by lforst** [comment]
@ant1m4tt3r would you mind opening a new issue with repro steps, and versions you are using?
