### ISSUE TITLE
Error With Uni-App App framework，Does it support the Uni App framework?

### ISSUE THREAD

**Issue by Wanganqi0704** [getsentry/sentry-javascript-bundler-plugins#403]
### Environment
Uni-App App  

```[tasklist]
### Tasks
```

**Comment by Wanganqi0704** [comment]
Running on Uni App

**Comment by Wanganqi0704** [comment]
<img width="887" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/40813278/29af0098-a6b9-47bd-bad4-18ffcce1bb06">

**Comment by Wanganqi0704** [comment]
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/40813278/aa63aaaf-e519-4d05-a6fb-660966af46a5)

**Comment by Wanganqi0704** [comment]
without @sentry/webpack-plugin ，project can running normally，and the  error prompt is gone

**Comment by Wanganqi0704** [comment]
"@sentry/webpack-plugin": "^2.7.1"

**Comment by lforst** [comment]
Hey, I don't know what uni is. Can you share a bit more information? Best would be if you shared a repository we could clone to reproduce this bug. Thanks!

**Comment by Wanganqi0704** [comment]
Thank You !!!  how very nice of you, the community is that: https://github.com/Wanganqi0704/test-uni-app-sentry-webpack-plugin.git

**Comment by Wanganqi0704** [comment]
This is too much trouble for you，your need to download other development tools to run this project. Thank you very much for being willing to solve this problem

**Comment by lforst** [comment]
@Wanganqi0704 I took a look but unfortunately, this is a bit involved and I lack the expertise (and frankly the Chinese skills) to tackle this right now. I can give you some pointers on what I think might be going on:

- You are maybe using an old incompatible webpack version
- Uni is potentially not calling webpack plugins correctly.

An alternative you could try is to use Sentry CLI to upload source maps instead. That should work for sure! https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/

**Comment by Wanganqi0704** [comment]
Thank you for taking the time out of your busy schedule to review this issue，This is indeed quite involved. I will use sentry cli to upload source map.  Thanks
