### ISSUE TITLE
@sentry-cli not working with @sentry/vite-plugin when installed with bun

### ISSUE THREAD

**Issue by shapeshifta78** [getsentry/sentry-javascript-bundler-plugins#412]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/browser

### SDK Version

7.57.0

### SDK Setup

```javascript
Sentry.onLoad(() => {
  Sentry.init({
    enabled: import.meta.env.PROD,
    dsn,
    release,
  
  });
});
```

### Steps to Reproduce

Install @sentry-cli and @sentry/vite-plugin with bun and try to run it. **Works fine when installed with npm ci,** but does not work with bun.

### Expected Result

Sourcemaps get generated and uploaded to sentry.

### Actual Result

Error: spawn /Users/xxx/Projects/xxx/node_modules/@sentry/cli/sentry-cli ENOENT

**Comment by crax0** [comment]
Same problem for me with nextjs. First saw a problem with vercel "error - Sentry CLI binary not found. Source maps will not be uploaded." This lead me to add it as trustedDependencies to run post install scripts but its not working.
`"trustedDependencies": ["@sentry/nextjs", "@sentry/cli"],`

Current Bun version: 1.0.3

**Comment by Lms24** [comment]
Hmm I'm wondering if `trustedDependencies` only applies to direct dependencies but not to transitive ones?

**Comment by shapeshifta78** [comment]
Gave this a retry and now it's working. Not sure what I did different the last time or if it's maybe related to updating bun.

Using trustedDependencies works, here are the steps: https://github.com/oven-sh/bun/issues/2998#issuecomment-1735560575

**Comment by Cluster2a** [comment]
I am still getting the problem with svelteKit 1.27.6 / vite 4.5 + @sentry/sveltekit.
Adding the dependencies to trustedDependencies does not seem to work.

**Comment by lforst** [comment]
@Cluster2a you need to add `@sentry/cli` to the trusted dependencies

**Comment by Cluster2a** [comment]
> @Cluster2a you need to add `@sentry/cli` to the trusted dependencies

I added all of them.
`"trustedDependencies": ["@sentry/cli", "@sentry/vite-plugin", "@sentry/sveltekit"],`

```
Error: spawn /xxx/node_modules/@sentry/cli/sentry-cli ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /xxx/node_modules/@sentry/cli/sentry-cli',
  path: '/xxx/node_modules/@sentry/cli/sentry-cli',
  spawnargs: [ 'releases', 'propose-version' ],
  cmd: '/xxx/node_modules/@sentry/cli/sentry-cli releases propose-version'
}

Node.js v19.4.0
error: script "build" exited with code 1 (SIGHUP)
```

**Comment by lforst** [comment]
@Cluster2a I recommend just making sure `@sentry/cli`'s `install` script runs before you use the CLI.
