### ISSUE TITLE
The sourcemap has been uploaded, but the error still cannot be displayed normally.

### ISSUE THREAD

**Issue by wuhaohuang** [getsentry/sentry-javascript-bundler-plugins#426]
### Environment

What version are you running? Etc. "@sentry/vue": "^7.74.0", "@sentry/vite-plugin": "^2.8.0",

The sourcemap has been uploaded and can be seen in the background, as shown in the figure:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/19322584/8fb58f6d-50ce-44c5-8cce-5c44fc5b3fcc)

init: 
Sentry.init({
      app,
      dsn: 'xxxxxxxxxxxxxxxxxxx',
      integrations: [
        new Sentry.BrowserTracing({
          routingInstrumentation: Sentry.vueRouterInstrumentation(router),
        }),
        new Sentry.Replay(),
      ],
      tracesSampleRate: 1.0,
      tracePropagationTargets: [window.location.origin],
      replaysSessionSampleRate: 0.1,
      replaysOnErrorSampleRate: 1.0,
      environment: import.meta.env.VITE_BUILD_ENV,
      release: '1.0.4',
      dist: 'ts-1.0.0',
    });

upload:
sentryVitePlugin({
          org: 'xxx',
          project: 'xxxxxx',
          authToken: 'xxxxxxx',
          url: 'xxxxxxx',
          release: {
            name: '1.0.4',
            uploadLegacySourcemaps: {
              paths: ['dist'],
              ignore: ['./node_modules'],
            },
            dist: 'ts-1.0.0',
          },
          sourcemaps: {
            assets: 'dist/static/js/**',
            ignore: ['node_modules'],
          },
        })

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/19322584/2e02f229-40f9-4735-a72f-6c7712157dd0)

pls help!

I don't know if it has anything to do with this. There is no more effective information other than this.
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/19322584/7e9f557d-8483-4d4b-ad47-a7c43675165d)

**Comment by AbhiPrasad** [comment]
Closing this issue for clean-up. Please open a new issue if it still applies. Thanks!
