### ISSUE TITLE
"Error: unable to get local issuer certificate" with @sentry/vite-plugin on Node.js v20.9.0 and macOS 14.0

### ISSUE THREAD

**Issue by shubov** [getsentry/sentry-javascript-bundler-plugins#446]
### Environment

- Sentry Vite Plugin Version: `2.10.1`
- Vite Version: `4.5.0`
- Node.js Version: `v20.9.0`
- Operating System: macOS 14.0 (23A344)

### Steps to Reproduce

1. Installed `@sentry/vite-plugin` version `2.10.1` in my Vite project (version `4.5.0`).
2. Set up the plugin in the Vite configuration file.
3. Ran the project using `yarn run dev`.

### Expected Result

The project should have started without any SSL certificate issues, and Sentry should be integrated smoothly.

### Actual Result

Received an error related to SSL certificates when starting the dev server. The specific error message was:

Error: unable to get local issuer certificate
at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
at TLSSocket.emit (node:events:514:28)
at TLSSocket.emit (node:domain:488:12)
at TLSSocket._finishInit (node:_tls_wrap:1070:8)
at ssl.onhandshakedone (node:_tls_wrap:856:12)

**Comment by lforst** [comment]
Hi, we're not doing any custom network things/tls in the plugins so this is likely an issue with your setup.

**Comment by AbhiPrasad** [comment]
Closing for clean-up. Please open a new issue if this still applies. Thanks!
