### ISSUE TITLE
[webpack] debugId on main entry file keeps changing due to other chunk

### ISSUE THREAD

**Issue by vincenthend** [getsentry/sentry-javascript-bundler-plugins#447]
### Environment

@sentry/webpack-plugin@2.7.0

### Steps to Reproduce
- I have a multiple entry files (main.js, other_entry.js) and few other chunks (foo.js and bar.js). foo.js is uniquely generated per build.
  - `other_entry.js` is using `foo.js`
  - `main.js` is using `bar.js`
- Each chunk in the build will be generated with the name `[id].[contentHash].js` for caching purposes
- Since `foo.js` keeps changing on every build, the`debugId` generated for `main.js` is affected
- The `debugId` for `main.js` changed changing the final `contentHash` and breaking the cache behaviour
- The `debugId` for `bar.js` remains constant

Apparently this happened due to the use of `hash` for generating `debugId`

```typescript
        new BannerPlugin({
          raw: true,
          include: /\.(js|ts|jsx|tsx|mjs|cjs)$/,
          banner: (arg?: BannerPluginCallbackArg) => {
            const debugId = arg?.chunk?.hash ? stringToUUID(arg.chunk.hash) : uuidv4();
            return getDebugIdSnippet(debugId);
          },
        })
```

### Expected Result
- `debugID` on `main.js` should remain constant since the real file content doesn't change

### Actual Result
- `debugID` for `main.js` changed although the real content of the file doesn't change.

### Suggestion
Probably good if we can have it generated based on `contentHash` instead of `hash`

**Comment by lforst** [comment]
> Since foo.js keeps changing on every build, thedebugId generated for main.js is affected

Can you explain why changing foo.js affects the hash of main.js?

But in general you're probably right that we should use the content hash instead.
