### ISSUE TITLE
Can't upload source maps in multi module workspace

### ISSUE THREAD

**Issue by fgatti675** [getsentry/sentry-javascript-bundler-plugins#449]
I am not sure this is a bug or I am doing something wrong, thanks for the patience in advance!

### Environment

I have a monorepo with multiple modules that get built in cascade using lerna and vite.
For simplicity let's say I have `core` and `saas` (which depends on `core`)

First `core` is built and then `saas` uses it's output (note that I can't build `saas` directly linking to the `core` source code, I need to compile `core` first and then use the compiled version).

This is my simplified vite config:

```
import path from "path";
import { defineConfig, loadEnv } from "vite";
import { sentryVitePlugin } from "@sentry/vite-plugin";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig(async ({ command, mode }) => {
    return ({
        build: {
            target: "esnext",
            modulePreload: false,
            minify: true,
            cssCodeSplit: false,
            outDir: "./build",
            sourcemap: true
        },
        plugins: [
            react(),
            sentryVitePlugin({
                authToken: process.env.SENTRY_AUTH_TOKEN,
                org: "...",
                project: "...",
                debug: true,
                sourcemaps: {
                    assets: [
                        "./build/assets/**",
                        "../firecms_core/dist/**",
                    ]
                }
            })
        ],
        resolve: {
            alias: {
                "@firecms/core": path.resolve(__dirname, "../firecms_core"),
            }
        }
    });
})

```

The sourcemaps of the `saas` projects are uploaded correctly.
The ones for `core` are found, but I get an error message:

```
Debug: Could not determine debug ID from bundle. This can happen if you did not clean your output folder before installing the Sentry plugin. File will not be source mapped: /Users/francesco/firecms-tailwind/packages/firecms_core/dist/index.umd.js
[sentry-vite-plugin] 
Debug: Could not determine debug ID from bundle. This can happen if you did not clean your output folder before installing the Sentry plugin. File will not be source mapped: /Users/francesco/firecms-tailwind/packages/firecms_core/dist/index.es.js
```

The JS and maps seem to be generated correctly in the `core` project.

Any help would be highly appreciated!!

### Expected Result

I would expect to have source maps  generated correctly for internal dependencies

### Actual Result

Only the entry point source maps are used correctly

**Comment by fgatti675** [comment]
Thanks @lforst 
Unfortunately the source maps for `core` are not picked up automatically. Can I assume this is a bug or maybe there is anything else I can try?

**Comment by lforst** [comment]
Are the sources from `core` included in the output source maps for `saas`? If not, it is likely a configuration issue on your end with vite. If they are, remove the `sourcemaps` option from the sentry vite plugin and everything should just work. Please note that the console message you shared is a warning and not an error and does not indicate that anything is necessarily wrong.

**Comment by fschwahn** [comment]
Just a heads up, because I spent a lot of time figuring out why the esbuild plugin did not work as expected (it also spit out the `Could not determine debug ID from bundle` message from above):

I had the entrypoints defined as a glob expression. Somehow the esbuild-plugin does not work in that case:

```js
const config = {
  entryPoints: [
    "app/javascript/*.js",
  ],
  # ...
}
```

Replacing it with an explicit list of entry points fixed it:

```js
const config = {
  entryPoints: [
    "app/javascript/foo.js",
    "app/javascript/bar.js",
  ],
  # ...
}
```
