### ISSUE TITLE
[Feature Request] Deterministic bundle building against release name change 

### ISSUE THREAD

**Issue by kkimdev** [getsentry/sentry-javascript-bundler-plugins#453]
We found that our `vendor.[contentHash].js` is never cached because it includes Sentry's release name, which is the current Git hash by default.

So as a temporary workaround, we assigned a constant release name for all builds for now.

```
          release: { name: "Unnamed" },
```

It would be great if the release name can be independent from the bundle content.

**Comment by kkimdev** [comment]
Hi, thanks for the quick response.

Our usecase is that `vendor.[contentHash].js` rarely changes across different releases, so we would like to cache them even if the release name changes.  If we're forced to choose only one, then we have to give up specifying the release name (as you noted).

**Comment by kkimdev** [comment]
@lforst Q: Can we distinguish release versions on Sentry UI even with `release.inject: false` ?

**Comment by lforst** [comment]
Well you can set the release value in Sentry.init.
