### ISSUE TITLE
error: Two different url values supplied:

### ISSUE THREAD

**Issue by furlongmatt** [getsentry/sentry-javascript-bundler-plugins#465]
### Environment

What version are you running? Etc.

- "@sentry/vite-plugin": "^2.10.3",
- "@sentry/vue": "^7.94.1",

### Steps to Reproduce

```
      sentryVitePlugin({
        authToken: env.VITE_SENTRY_AUTH_TOKEN,
        org: 'sentry',
        project: 'call-center-front-end',
        url: 'https://INTERNAL_URL_HERE',
        debug: true,
      }),
```

### Expected Result

Source maps uploaded to a our self-hosted sentry

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

We keep getting this error:  **error: Two different url values supplied: `` (from token), `https://INTERNAL_URL_HERE`** 

```
Starting: NPM Install and Build - front-end
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.231.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/2c145116-a596-4e1b-adc2-bbbf87f7ebd3.sh

added 340 packages, and audited 341 packages in 11s

116 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 17 packages, removed 11 packages, changed 35 packages, and audited 347 packages in 13s

116 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> front-end@3.0.1 build
> vite build

vite v5.0.12 building for production...
transforming...
✓ 584 modules transformed.
rendering chunks...
computing gzip size...
[sentry-debug-id-upload-plugin] Command failed: /home/vsts/work/1/s/front-end/node_modules/@sentry/cli-linux-x64/bin/sentry-cli releases new 7f47f0b545688275e2ecf77a9a7d069bb5ea16d9
error: Two different url values supplied: `` (from token), `https://INTERNAL_URL_HERE`./

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

**Comment by lforst** [comment]
Hi, I recommend leaving away the `url` option in the plugin. The url is already encoded in the auth token.

**Comment by lforst** [comment]
Okay, I believe the issue here is that you are on a buggy version of self-hosted Sentry, that is configured in an unlucky way. Our recommendation here is for you to upgrade your self-hosted instance to the latest version and make sure you have the `system.url-prefix` option set in your self-hosted instance. Then you have to generate a new auth token which should have a properly encoded URL. After switching it out I also recommend removing the `url` option in the plugin because the url is already encoded in the auth token.

**Comment by furlongmatt** [comment]
> Okay, I believe the issue here is that you are on a buggy version of self-hosted Sentry, that is configured in an unlucky way. Our recommendation here is for you to upgrade your self-hosted instance to the latest version and make sure you have the `system.url-prefix` option set in your self-hosted instance. Then you have to generate a new auth token which should have a properly encoded URL. After switching it out I also recommend removing the `url` option in the plugin because the url is already encoded in the auth token.

This looks to have done the trick. Appreciate the help!
