### ISSUE TITLE
@sentry/vite-plugin stuck on vercel

### ISSUE THREAD

**Issue by sirpy** [getsentry/sentry-javascript-bundler-plugins#466]
### Environment
node-18
react
vite
### Steps to Reproduce
add sentry plugin

### Expected Result
build finishes successfully

### Actual Result
vercel build stuck on 
```
vite v4.5.2 building for production...
--
18:26:07.447 | transforming...
```

If I remove the sentryPlugin definitions from plugins it works just fine
locally build works just fine

**Comment by lforst** [comment]
Hi, I cannot reproduce this issue. Would you mind sharing a minimal reproduction repository that when deployed to vercel gets stuck? Thank you!

**Comment by sirpy** [comment]
issue was solved by defining node old space size to 7G.
also using manualChunks to reduce main chunk size
