### ISSUE TITLE
API request failed 

### ISSUE THREAD

**Issue by St-coder** [getsentry/sentry-javascript-bundler-plugins#470]
### Environment

node version is 14.16.1
"vue": "^2.5.2",
"@sentry/vue": "^7.98.0",
@sentry/webpack-plugin": "^2.10.3

vue.config.js
Object.assign(config, {
      plugins: [
        ...config.plugins,
        sentryWebpackPlugin({

          url: "https://sentry.io", // Sentry 后台地址
          release: process.env.VUE_APP_RELEASE, // 和 `Sentry.init` 中的保持一致
          include: path.join(process.cwd(), "/dist"), // 需要上传到 sentry 服务器的资源目录
          ignore: ["node_modules", "vue.config.js"], // 忽略文件目录，如果在 inlcude 中已经定义了具体路径，这个参数可以不加
          authToken: process.env.VUE_APP_SENTRYUserAuthTokens, // 上文中的 User auth tokens
          org: 'newhopeservice', // 上文中的组织名称
          project: 'basic-platform', // 上文中的项目名称
          urlPrefix: "~/static/js", // 上传资源的路径前缀，uni-app build 的路径通常是 `/static/js`, 如有变化自行更改
        }),
      ],
      // 不加这个uni-app不会生成soucemap文件
      devtool: "source-map",
    });

### Steps to Reproduce

npm run build --log-info

### Expected Result

upload sourceMap success

### Actual Result
![400301ed-dda7-4c96-868d-8e93ea7cdf2f](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/16557111/b80cf51e-b04a-46ce-8d6b-fbe4de79f61f)

API request failed 
UnhandledPromiseRejectionWarning: Error: Command failed: D:\项目库\basic-platform\node_modules\@sentry\cli-win32-x64\bin\sentry-cli.exe releases new 3da621637cdc874f20b6bba97eca7a7f31f271f1
  INFO    2024-01-31 17:28:55.833753900 +08:00 sentry-cli was invoked with the following command line: "D:\项目库\basic-platform\node_modules\@sentry\cli-win32-x64\bin\sentry-cli.exe" "releases" "new" "3da621637cdc874f20b6bba97eca7a7f31f271f1"
error: API request failed
  caused by: [35] SSL connect error (schannel: failed to receive handshake, SSL/TLS connection failed)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

![144c7f56-ae14-4dc4-9572-dd018970fd63](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/16557111/3e752141-3fb2-4f00-b09f-7c6383faaa72)

**Comment by St-coder** [comment]
The network is fine; I switched from the company's network to my phone's hotspot, and it still shows this error.

**Comment by Lms24** [comment]
Hi @St-coder, looks like the wizard isn't the only place where this is happening. I have a feeling this is related to an entity interfering with the request. I don't necessarily think there's a bug within the plugin. Have you tried running the plugin while being connected to a VPN?

**Comment by Kenvdb** [comment]
> Hi @St-coder, looks like the wizard isn't the only place where this is happening. I have a feeling this is related to an entity interfering with the request. I don't necessarily think there's a bug within the plugin. Have you tried running the plugin while being connected to a VPN?

Yes, when VPN is active, this issue occurs. Same here on my env.

**Comment by Lms24** [comment]
Hey, this still is most likely a network issue on your end. We've had a report [coming in](https://github.com/getsentry/sentry-cli/issues/1921) recently in the Sentry CLI repo which is very similar to this one. 

Since the requests are made from Sentry CLI (a dependency of the plugin) I suggest following the debugging steps in https://github.com/getsentry/sentry-cli/issues/1921.

**Comment by St-coder** [comment]
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/16557111/d59ebda9-71b7-4552-9ea3-6ccc43f30a57)
Thanks!
I just tried the command you provided, curl -X POST https://sentry.io/api/0/projects/pixel-order/qingtian-xr/releases/, and it resulted in an error: "failed to receive handshake, SSL/TLS connection failed". I had friends from different companies also try this command, and they encountered the same error as shown in the picture above. We are in China, could there be an issue with your certificate?

**Comment by St-coder** [comment]
> > Hi @St-coder, looks like the wizard isn't the only place where this is happening. I have a feeling this is related to an entity interfering with the request. I don't necessarily think there's a bug within the plugin. Have you tried running the plugin while being connected to a VPN?
> 
> Yes, when VPN is active, this issue occurs. Same here on my env.

Have you solved this problem? 
i open Vpn, youtube  is visited  successfully，but this issue  still occurs

**Comment by lforst** [comment]
I think it is very likely that China's firewall is interfering with your requests. We have no other reports of requests failing like this, except for when they come from countries with restrictive internet access. We also have no reasonable suspicion that our certificates are not set up correctly. Please double-check that your traffic to Sentry is properly being routed through the VPN.

**Comment by St-coder** [comment]
> Reference in

Yes, it may be caused by China's firewall. I didn't have this problem after deploying Sentry in a private manner.

**Comment by St-coder** [comment]
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/16557111/9445dcb8-dd3e-444a-bcc7-92d1b02377b8)
question has been resolved.thanks！！

**Comment by St-coder** [comment]
> Hey, this still is most likely a network issue on your end. We've had a report [coming in](https://github.com/getsentry/sentry-cli/issues/1921) recently in the Sentry CLI repo which is very similar to this one.
> 
> Since the requests are made from Sentry CLI (a dependency of the plugin) I suggest following the debugging steps in [getsentry/sentry-cli#1921](https://github.com/getsentry/sentry-cli/issues/1921).

Please help me close this issue. The problem has been solved. Thank you!
