### ISSUE TITLE
Why `@sentry/vite-plugin` install half of internet to my node_modules?

### ISSUE THREAD

**Issue by mahnunchik** [getsentry/sentry-javascript-bundler-plugins#476]
Why this plugin install half of internet to my node_modules?

### Steps to Reproduce

Install `@sentry/vite-plugin`

### Expected Result

A reasonable amount of dependencies.

### Actual Result

```json
    "@babel/core": "7.18.5",
    "@babel/preset-env": "7.18.2",
    "@babel/preset-typescript": "7.17.12",
+ half of internet
```

**Comment by lforst** [comment]
Welcome to JS ecosystem! No jk. I actually don't think it's too bad. Any dependency in particular that you think is too much?

**Comment by mahnunchik** [comment]
`babel/*` is too much. This plugin should upload source maps, that's all.

**Comment by lforst** [comment]
We will not remove this dependency as of now. Maybe we can reevaluate in the future.

**Comment by mahnunchik** [comment]
This is sad, I'm looking for an alternative to sentry.

**Comment by lforst** [comment]
@mahnunchik I struggle to see how this is an issue for you. `@sentry/vite-plugin` amounts to 2MB including all of it's dependencies. None of which will make it into your bundles. But all the power to you for finding an alternative!

**Comment by eMerzh** [comment]
hey here =) 
although it's not a huge deal and i'm maybe not 100% on the form here, 

i was surprise today to see that a big part of my SBOM is made of babel stuff from here.
i'm not 100% sure why it's used.. 
is it because of the inclusion of babel-plugin-component-annotate ?

**Comment by lforst** [comment]
> is it because of the inclusion of babel-plugin-component-annotate ?

I think that is a very very big part of it - yes.
