### ISSUE TITLE
Sourcemap upload successful, artifacts show in UI, no sourcemaps in Sentry

### ISSUE THREAD

**Issue by echjordan0** [getsentry/sentry-javascript-bundler-plugins#480]
### Environment

What version are you running? Etc.
  "@sentry/vite-plugin": "^2.10.2",
  "@sentry/capacitor": "0.14.0",
  "@sentry/core": "7.73.0",
  "@sentry/vue": "7.73.0",

self-hosted instance is on 23.7.1

Relevant vite config
```js
    sentryVitePlugin({
      org: 'sentry',
      project: process.env.PROJECT,
      url: process.env.URL,
      disable: !process.env.TOKEN,
      sourcemaps: {
        filesToDeleteAfterUpload: ['**/*.js.map'],
      },
      release: {
        name: version,
        setCommits: {
          auto: true,
          ignoreMissing: true,
        },
      },
    }),
```

Example of successful deploy logs
```
[2024-01-30T18:57:47.621Z] > Found 238 files
[2024-01-30T18:57:47.878Z] > Analyzing 238 sources
[2024-01-30T18:57:47.878Z] > Adding source map references
[2024-01-30T18:57:50.398Z] > Bundled 238 files for upload
[2024-01-30T18:57:50.398Z] > Bundle ID: 9bc5d9f3-89e6-5375-8b03-a58483068492
[2024-01-30T18:57:50.962Z] > Uploaded files to Sentry
[2024-01-30T18:57:50.962Z] > File upload complete (processing pending on server)
[2024-01-30T18:57:50.962Z] > Organization: sentry
[2024-01-30T18:57:50.962Z] > Project: freshebt-vue-prod
[2024-01-30T18:57:50.962Z] > Release: 6.9.0
[2024-01-30T18:57:50.962Z] > Dist: None
[2024-01-30T18:57:50.962Z] > Upload type: artifact bundle
[2024-01-30T18:57:50.962Z] Source Map Upload Report
[2024-01-30T18:57:50.962Z]   Minified Scripts
...
```

### Steps to Reproduce
Tough to create a reproduction but general sequence of events seems to be

1. Upload sourcemaps with vite plugin and the versions mentioned

### Expected Result

Sourcemaps will appear in Sentry

### Actual Result
Example event without any sourcemap-related errors but also no sourcemaps
![Screenshot 2024-02-02 at 4 31 54 PM](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/103529370/8186d214-90d5-4bc7-9c4a-cffed02ee27b)

The file and its map in the Artifacts UI in Sentry
![Screenshot 2024-02-02 at 4 33 34 PM](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/103529370/897a6aa6-b3ba-44fc-93f4-fd01ec4f6646)

I've followed the Troubleshooting docs:
- [X] Verified Artifacts Are Uploaded
- [X] Verified That we're Building Source Maps
- [X] Verified we're Running a Production Build
- [X] Verified our Source Files Contain Debug ID Injection Snippets
- [X] Verified our SDK is Up-to-Date -- spotchecking JSON for events I didn't see a property called `raw_stacktrace` but I saw `stacktrace` which did match `debug_meta.image.code_file` exactly
- [X] Verified Artifacts Are Uploaded Before Errors Occur (artifacts are uploaded before the code is deployed)
- [X] Verified built version of our app serves sourcemaps correctly
- [X] Verified Your Source Files Aren't Too Large
- [X] Sourcemap files don't appear to be g zipped
- [ ] **Verify Workers Are Sharing Same Volume as Web (if running self-hosted Sentry via Docker)**
- [X] Verified not using `source-map-support` package

Spot checked an event in the release with the CLI and received:
```
✔ Fetched data for event: XXX
✔ Event has release name: 6.9.0
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
✖ Release has no artifacts uploaded
ℹ https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-artifacts-are-uploaded
```

Re: Verify Workers Are Sharing Same Volume as Web (if running self-hosted Sentry via Docker)
We use S3 storage for our self-hosted instance. This configuration has not changed in many months -- perhaps there's some specific upload method required if the self-hosted instance uses S3 storage?

**Comment by lforst** [comment]
Hi, can you upgrade your self-hosted instance? Yours is already quite dated. Please also check the logs for the `symbolicator` service.

**Comment by zakhenry** [comment]
I had the same symptoms, in our case it was a fresh install of Sentry self hosted and we had forgotten to enable symbolicator and sourcemaps in the helm config.

It would be ideal if the sentry-cli diagnostic tool could verify that symbolicator is up and running to give a more explicit error message.

**Comment by lforst** [comment]
@zakhenry Fair suggestion. I don't think adding such a check is a priority for us right now, especially since it would be quite involved and would require backend and infra changes.

I'll close this issue since it seems resolved/stale.
