### ISSUE TITLE
esbuild-plugin is missing a name

### ISSUE THREAD

**Issue by LukasKlement** [getsentry/sentry-javascript-bundler-plugins#483]
Trying to use the vite-plugin in an Angular application with angular-builders/custom-esbuild (https://github.com/just-jeb/angular-builders/tree/master/packages/custom-esbuild) produces the error on build: throw new Error(`Plugin at index ${i} is missing a name`);

In angular.json I use the builder: "builder": "@angular-builders/custom-esbuild:application" and in options "plugins": ["./vite.config.ts"],

The plugin is from the documentation - manual setup: https://docs.sentry.io/platforms/node/guides/connect/sourcemaps/uploading/vite/

Environment:
- @angular/core 17.1.3
- @angular-builders/custom-esbuild 17.1.0-beta.0
- @sentry/vite-plugin 2.14.0

**Comment by lforst** [comment]
Hi, would you mind console logging your plugins on build and sharing them here? I cannot immediately spot where we would be missing a plugin name. Maybe the logs help us find the culprit.

**Comment by LukasKlement** [comment]
These are the plugins being loaded (console logging node_modules/esbuild/lib/main.js):
```
[
  { name: 'angular-sourcemap-ignorelist', setup: [Function: setup] },
  { name: 'angular-compiler', setup: [AsyncFunction: setup] },
  { build: { sourcemap: true }, plugins: [ [Object] ] }
]
```

These are the items I get when logging the let item of plugins iterator:
```
{ name: 'angular-sourcemap-ignorelist', setup: [Function: setup] }
{ name: 'angular-compiler', setup: [AsyncFunction: setup] }
plugins:  [
  { name: 'angular-sourcemap-ignorelist', setup: [Function: setup] },
  { name: 'angular-polyfills', setup: [Function: setup] }
]
{ name: 'angular-sourcemap-ignorelist', setup: [Function: setup] }
{ name: 'angular-polyfills', setup: [Function: setup] }
plugins:  [
  { name: 'angular-styles-global', setup: [Function: setup] },
  { name: 'angular-sass', setup: [AsyncFunction: setup] },
  { name: 'angular-less', setup: [AsyncFunction: setup] },
  { name: 'angular-css', setup: [Function: setup] },
  { name: 'angular-css-resource', setup: [Function: setup] },
  { name: 'angular-css-inline-fonts-plugin', setup: [Function: setup] }
]
{ name: 'angular-styles-global', setup: [Function: setup] }
{ name: 'angular-sass', setup: [AsyncFunction: setup] }
{ name: 'angular-less', setup: [AsyncFunction: setup] }
{
  build: { sourcemap: true },
  plugins: [
    {
      '0': [Object],
      '1': [Object],
      '2': [Object],
      enforce: 'post',
      name: 'sentry'
    }
  ]
}
{ name: 'angular-css', setup: [Function: setup] }
{ name: 'angular-css-resource', setup: [Function: setup] }
```

The vite.config.ts is the one from your docs:
```
import { defineConfig } from "vite";
import { sentryVitePlugin } from "@sentry/vite-plugin";

export default defineConfig({
  build: {
    sourcemap: true,
  },
  plugins: [
    sentryVitePlugin({
      org: "my-org",
      project: "my-project",
      authToken: process.env.SENTRY_TOKEN,
    }),
  ],
});

```

**Comment by LukasKlement** [comment]
Thanks for the note, apologies posted on the wrong plugin. The error is the same though, this is the config:

angular.json: "builder": "@angular-builders/custom-esbuild:application",

esbuild.config.ts:

import { sentryEsbuildPlugin } from "@sentry/esbuild-plugin";
import esbuild from "esbuild";

esbuild.build({
  sourcemap: true, // Source map generation must be turned on
  plugins: [
    // Put the Sentry esbuild plugin after all other plugins
    sentryEsbuildPlugin({
      org: "menutech",
      project: "menutech-ordertaking-webclient",
      authToken: process.env.SENTRY_AUTH_TOKEN,
    }),
  ],
});

**Comment by lforst** [comment]
I cannot reproduce this with the latest version of esbuild and the esbuild plugin. Would you mind sharing a small reproduction example? Thanks!

**Comment by LukasKlement** [comment]
Hi, thanks - here's an example: https://stackblitz.com/edit/stackblitz-starters-ddzaip?file=src%2Fmain.ts
Indeed, I get the following error now: "Add only entry points to the 'files' or 'include' properties in your tsconfig."

**Comment by lforst** [comment]
@LukasKlement the stackblitz you shared doesn't contain any Sentry plugins 🤔 did you press save?
