### ISSUE TITLE
@sentry/vite-plugin inclusion in vite.config.js causes it to skip .env.production

### ISSUE THREAD

**Issue by 719media** [getsentry/sentry-javascript-bundler-plugins#484]
### Environment

What version are you running? Etc.

### Steps to Reproduce

1. npm install @sentry/vite-plugin
2. .env.production files are no longer used. Major problem! (however, .env.production.local files appear to still be used)

### Expected Result

.env.production files should be used

### Actual Result

.env.production files are no longer used, and instead just .env (and .env.local, .env.[name].local) are brought in

**Comment by 719media** [comment]
Sorry, I know the report is sparse, I will dig a little more, but I'm going to guess it has something to do with
[sentry-vite-plugin] Info: Using environment variables configured in ".env.sentry-build-plugin".

**Comment by lforst** [comment]
Hi, I tried this with the steps you outlined but couldn't reproduce the issue you're describing. Would you mind creating a reproduction repo we could pull to replicate this? Thank you!

**Comment by 719media** [comment]
Sure. Here you go
https://github.com/719media/sentry-vite-env-bug

**Comment by lforst** [comment]
Awesome thank you. Found the bug. Will release it asap.
