### ISSUE TITLE
Unclear on how to urlPrefix my maps.

### ISSUE THREAD

**Issue by mbaldi-orangeloops** [getsentry/sentry-javascript-bundler-plugins#488]
Hi!

Firstly, I am using the webpack plugin.

I am having a problem that the uploaded maps are with the name of ~/whatever and they don't match what is built which is named ~/static/js/whatever. In previous versions, I saw that there was a urlPrefix option for this. But I can't find an explicit alternative for newer versions. How could I do that in the new way?

Thanks in advance.

**Comment by mbaldi-orangeloops** [comment]
Yes, is there like a parsing to the new options? Or do I have to use the legacy (no-no word) options?

**Comment by mbaldi-orangeloops** [comment]
I assumed that if those options are legacy, there is a no-legacy way to do it with the new options. If there isn't that's fine also.

**Comment by lforst** [comment]
Since we completely changed the way we recommend people to upload source maps (using debug IDs), there wasn't really a sensical migration path. In theory that option is completely redundant if you use the new process.
