### ISSUE TITLE
Using the "filesToDeleteAfterUpload" plugin setting breaks source maps with esbuild plugin

### ISSUE THREAD

**Issue by bryansoftdev** [getsentry/sentry-javascript-bundler-plugins#490]
### Environment

- esbuild: 0.15.18
- @sentry/esbuild-plugin: 2.14.1
- @sentry/serverless: 6.15.0

### Steps to Reproduce

- Set `NODE_OPTIONS=--enable-source-maps` environment variable

- serverless.yml:

  ```
  custom:
    esbuild:
      exclude:
        - '@aws-sdk'
      plugins: './esbuild.plugins.js'
      sourcemap: true
  ```

- esbuild.plugin.js:

  ```
  const { sentryEsbuildPlugin } = require('@sentry/esbuild-plugin');
  
  module.exports = [
    sentryEsbuildPlugin({
      authToken: process.env.SENTRY_AUTH_TOKEN,
      org: '...',
      project: '...',
      release: {
        name: process.env.SENTRY_RELEASE,
        setCommits: { auto: true },
      },
      sourcemaps: {
        assets: './.esbuild/.build/**/*',
        filesToDeleteAfterUpload: './.esbuild/.build/**/*.map',
      },
    }),
  ];
  ```

I triggered a test event on AWS without changing the default values to make an error occur on purpose. I did it once without the filesToDeleteAfterUpload setting in my config, and then repeated with filesToDeleteAfterUpload set.

### Expected Result
Before enabling the filesToDeleteAfterUpload setting:
<img width="1069" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/25192073/c8eeabfc-abc2-4dcd-abb6-0dc8be719ea8">

### Actual Result
After enabling the filesToDeleteAfterUpload setting:
<img width="1081" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/25192073/9a5d0c7e-33e0-4614-8303-af841c074ead">

**Comment by lforst** [comment]
NODE_OPTIONS=--enable-source-maps is generally not supported by Sentry as it makes stack traces resolve to the original location which is not what we want when source maps are uploaded. Either you remove that option or you upload sourcemaps. It seems like something didnt work in the second screenshot though. What does the `unminify code` button say?

**Comment by bryansoftdev** [comment]
@lforst Thank you, I reviewed what the button said, and I realized my version of the sentry SDK was very out of date. Updating from @sentry/serverless: 6.15.0 to ^7.56.0 fixed the problem. 

The stack trace looks better now & my serverless zip has the source maps removed. 👍 
<img width="1097" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/25192073/57969933-cf70-49d6-95da-a4e982240a1c">


(I also removed `NODE_OPTIONS=--enable-source-maps` like you said)

**Comment by lforst** [comment]
Awesome, glad it worked for you!
