### ISSUE TITLE
Proxy for uploading sourcemaps?

### ISSUE THREAD

**Issue by gcunsolo** [getsentry/sentry-javascript-bundler-plugins#491]
Hello Sentries,

Big fan, big up!

### Context

I'm using the Webpack plugin to upload my sourcemaps to sentry.io 

For my CD, I'm using a (very) restrained self-hosted instance of Jenkins.

For security matters, this instance cannot freely communicate with the whole WWW

Well, it actually could, but only via a proxy.

Cannot find anything proxy related in your doc.

Ideally, i'd like to

```js
sentryWebpackPlugin({
	  proxy: 'https://my-awesome-proxy',
      url: 'https://sentry.io'
}),
```

Thanks for your feedback!

**Comment by lforst** [comment]
Thanks for writing in. I think your request makes sense. I unfortunately cannot give a timeline when we will get to implementing this - it is not high prio.

As a workaround, can you try setting the `http_proxy` environment variable when building? [docs](https://docs.sentry.io/product/cli/configuration/#:~:text=The%20URL%20that%20should%20be%20used%20for%20the%20HTTP%20proxy.%20The%20standard%20http_proxy%20environment%20variable%20is%20also%20honored.%20Note%20that%20it%20is%20lowercase.) For some reason it needs to be lowercase apparently 🤔 Please don't ask me why.

**Comment by gcunsolo** [comment]
Thanks for your reply @lforst

As far as I understand, applying your workaround would mean to drop the Webpack Plugin and do my things via the cli right after the build, right?

I'll give it a try, thanks again!

**Comment by lforst** [comment]
@gcunsolo No you shouldn't have to drop the webpack plugin. The webpack plugin uses the CLI under the hood, so the env var should be picked up by the CLI and use the proxy!

**Comment by AbhiPrasad** [comment]
Given we have the workaround to use `http_proxy` environmental variable, let's close this issue for now. If someone is unable to use the workaround, please re-open and we'll take another look. Thanks!
