### ISSUE TITLE
Sentry Vite Plugin throws error while building the app: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by cesarriva-br** [getsentry/sentry-javascript-bundler-plugins#494]
### Environment
Local dev environment running a Vite React Application
Vite+React app
Node v20.0.0

What version are you running? Etc.
Sentry Vite Plugin v2.14.2
Vite v5.1.3

### Steps to Reproduce

1. I followed the installation steps:
- npm install @sentry/vite-plugin --save-dev
- added the necessary config to the vite.config.js file as in the example and replaced the values with the ones from my Sentry project
3. Executed npm run build to build 

### Expected Result

The build process would run smoothly, creating my build bundle with the .map files and uploading them to Sentry.

### Actual Result

The build fails with the following:
<img width="1014" alt="Screenshot 2024-02-28 at 22 38 49" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/139487682/5ba7be2b-27be-429d-8e3e-c9e0f8ce4071">

This is my vite.config.js:
<img width="761" alt="Screenshot 2024-02-28 at 22 40 03" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/139487682/82bcb4c8-8d96-46b5-af64-79686a59ce47">

If I remove the call to the sentryVitePlugin, everything works and the build runs fine.

**Comment by lforst** [comment]
This looks odd. I cannot reproduce this. Would you mind sharing a reproduction example, ideally a github repo, that anyone can use to get this error? Thank you!
