### ISSUE TITLE
sentry-vite + CDN sourcemaps not working

### ISSUE THREAD

**Issue by siosio34** [getsentry/sentry-javascript-bundler-plugins#499]
### Environment

@sentry/react 7.105.0
@sentry/vite-plugin: 2.14.2
vite 5.1

In previous versions of Sentry, even when uploading to CDN, the sourcemap was automatically mapped when ~/{projectName} was used through urlPrefix.

However, in the latest version, the method of specifying urlPrefix has been updated, so I applied it as it is in the official document, but the sourcemap was not mapped.

There was uploadLegacySourcemaps in the sentry-vite plugin, so I used that field, but when I browsed the sourcemap in sentry, urlPrefix did not work.

Are there any examples where the source map works properly when using sentry + vite + cdn?

I'm also sharing my sentry vite settings in case it helps.

<img width="314" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/7166022/8296ce17-489d-459c-885e-41a76ee017bf">

### Expected Result

When the source map is uploaded and an error occurs, the error code location must be well mapped, just like before.

**Comment by lforst** [comment]
Hi, we need more information!

- You mention a previous version of the plugin. Which one?
- What exactly does not work? Can you share a Sentry event?

**Comment by siosio34** [comment]
1. we before use @sentry/webpack-plugin": "^1.20.0, @sentry/react": "7.44.2" but current use @sentry/vite-plugin": "^2.14.2, @sentry/react
2. sry we are use self hosted sentry environment 
3.We are distributing our React project using CDN.

@lforst

**Comment by lforst** [comment]
Please try using `sourcemaps.assets: './dist/assets/**'` and updating your self hosted instance. Thank you!

Also, would you mind answering the rest of my questions? Thanks.

> What did your previous setup look like?
> What exactly does not work?

**Comment by siosio34** [comment]
> Please try using sourcemaps.assets: './dist/assets/**' and updating your self hosted instance. Thank you!

The methods are not the same either.

> What did your previous setup look like?

I used sentry Webpack plugin

<img width="554" alt="스크린샷 2024-03-07 오후 8 04 08" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/7166022/6576c2bd-2426-462c-bb1d-287df63a7a2b">

> What exactly does not work?
Source map upload is possible. However, when catching an error, it does not capture the location of the error source. like below

<img width="1009" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/7166022/966a6a96-50a1-4216-94c4-9fa9d9d73454">


@lforst

**Comment by siosio34** [comment]
Is there a way to specify the urlPrefix using only the uploadLegacySourcemaps field without using the debug id?

If it is possible to do so, even if it means lowering the version, I would like to do so.

Uploading a self-hosted version of Sentry is a bit burdensome for our company, so we would like to avoid it as much as possible

**Comment by siosio34** [comment]
Currently I am using sentryVitePlugin in webpack. Are these also the same?

@lforst

**Comment by siosio34** [comment]
I'm sorry for causing you to misunderstand. Previously, I used webpack, but as I switched to Vite, I was changing the sentry settings and I am talking about the issues that arise as a result.


<img width="645" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/7166022/394219be-129a-4d94-8711-4cf296348956">


I want to check if I understand Sentry well. If you are receiving js from a path like CDN address/project name/assets as above, isn't it correct to set the uploadLegacySourcemaps setting during sentryvite settings as shown in the code below?

<img width="245" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/7166022/cf4888e7-cad0-4f6f-a836-8854c6c0f04f">

@lforst

**Comment by lforst** [comment]
From your screenshot it looks like you had it configured as

```
{
  include: 'dist',
  urlPrefix: '~/upbit-nft'
}
```

why don't you try?

```ts
sentryVitePlugin({
  debug: true,
  // your other options here! ...
  release: {
    uploadLegacySourcemaps: {
      paths: ['dist'],
      urlPrefix: '~/upbit-nft'
    }
  }
})
```

**Comment by siosio34** [comment]
The reason is that when building with webpack, there were js files directly in the dist folder, but after building with vite, js files were created in the dist/assets folder. and even if you do what you said, it still doesn't work as shown in the picture below.

<img width="1057" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/7166022/dcac8149-1482-43de-ad52-adb11b3a16f9">

**Comment by siosio34** [comment]
Are there any examples using the CDN + vite + sentry-vite plugin? I think many vite users are probably experiencing the same issue as me. Our front team tried to solve the issue, but we couldn't solve it, so we want to check if this works.

**Comment by siosio34** [comment]
Do I have to set the release version unconditionally? I'm asking because in the previous webpack plugin, it worked fine without specifying a release version name.

**Comment by lforst** [comment]
I have a very hard time debugging this with you because I lack a ton of information about your setup, what you upload to Sentry and how your events look.

I personally do not think many people run into this particular issue, rather it is a config issue on your end. Please go through the troubleshooting guide: [docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/legacy-uploading-methods](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/legacy-uploading-methods/) because I have a feeling you haven't done that.

**Comment by siosio34** [comment]
It would be nice to have at least one example. There seems to be an issue with many developers on the team going through so much trial and error after seeing the official link and ultimately failing to link it. When you have time, it would be nice to have an example using vite + sentryVite + cdn. However, our project settings probably won't work because we don't do much different from the default settings.

@lforst

**Comment by siosio34** [comment]
> What you upload to your Sentry instance.
> A Sentry event that isn't source mapped. Ideally the payload.
> 

I think a detailed explanation of these two items is needed.

**Comment by siosio34** [comment]
Oh wait, I think I figured out the cause. Let's test it out for a moment.

**Comment by lforst** [comment]
> > What you upload to your Sentry instance.
> > A Sentry event that isn't source mapped. Ideally the payload.

> I think a detailed explanation of these two items is needed.

We outline all of these very detailed here https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/legacy-uploading-methods/

**Comment by siosio34** [comment]
@lforst I found out. It does not work if you use the chunk function of rollup. After deleting the option shown in the picture below, the source is captured. However, chunk seems to be essential to reduce the size of the entire file. Is there a way to ensure that the source can be found accurately even when applying the chunk option?

<img width="384" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/7166022/f5f0fb96-90f1-48b3-9338-8fe1056a8c60">

**Comment by lforst** [comment]
> Is there a way to ensure that the source can be found accurately even when applying the chunk option?

I don't understand what you mean by that. You are responsible yourself for specifying the correct files with the `paths` option and for matching the stack frames with the uploaded artifacts.

**Comment by siosio34** [comment]
The problem was the manualChunks option for creating chunk files in the rollupOptions item in the vite.config.ts configuration file. If you remove that option, the sourcemap will load normally.

However, the process of creating a chunk file seems essential for fast loading. Is it possible to make sourcemap work well even if there is a chunk file in sentry?

**Comment by lforst** [comment]
You need to include the chunks in your uploaded files

**Comment by siosio34** [comment]
we are already includes chunk files...

<img width="1182" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/7166022/3c056e26-b8d1-4d2e-8f1d-f0a42b5397c7">

**Comment by lforst** [comment]
You successfully uploaded the chunks to Sentry. Now you need to match stack frames to the file names with the `rewriteFramesIntegration`!

**Comment by siosio34** [comment]
@lforst 

I read the documentation for rewriteFramesIntegration, but I didn't really understand how to use it. I think it would be good to be more detailed.

As I understand it, if urlPrefix is ​​~/{path1}/${path2}

rewriteFrames({
  prefix: ~/${path1}/${path2}
})

Can I do it like this?

**Comment by siosio34** [comment]
I tried both methods below, but they don't work.

```
rewriteFrames({
prefix: ~/${path1}/${path2}
})


rewriteFrames({
root: ~/${path1}/${path2}
})

**Comment by siosio34** [comment]
I changed it to using sentry cli directly and it seems to work well. This issue is closed. Thank you for responding to the issue together.
