### ISSUE TITLE
Roadmap to Sentry Bundler Plugins

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-javascript-bundler-plugins#50]
# Roadmap to Package Release

This issue serves as a roadmap to releasing Sentry bundler plugins for Vite, esbuild, Rollup. Eventually, we'll also replace our Sentry Webpack plugin with this new plugin.

## Necessary for initial release

https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/50#tasklist-block-5ed8fed2-765d-4f89-9f34-61425fe21f26

https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/50#tasklist-block-e151d2cd-db49-4556-adca-479ebb3ef33b

https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/50#tasklist-block-58033726-21b8-4f83-843c-4ab4a4bf3f43

https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/50#tasklist-block-51c2de9d-d960-4ecc-99ab-daa6b7f7cd0c

https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/50#tasklist-block-8e181a81-eb09-4be9-be43-0cec95f0f3d2

### After the initial release

https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/50#tasklist-block-883e7144-21d5-4a9c-a00d-9b4e20df0d80

**Comment by smeubank** [comment]
the goal for now is not to replace webpack-plugin right?

**Comment by lforst** [comment]
> the goal for now is not to replace webpack-plugin right?

It is kinda. In intermediary steps we can release packages just for the other bundlers, but goal is to be able to replace the webpack plugin.
