### ISSUE TITLE
Cannot read properties of undefined (reading "silent")

### ISSUE THREAD

**Issue by Tofandel** [getsentry/sentry-javascript-bundler-plugins#501]
Error is happening on this line

https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/fe6169b73a8f5a95d9ac2c263ddb592756ec90f4/packages/bundler-plugin-core/src/index.ts#L76

### Environment

When calling `sentryVitePlugin()` without any configuration option

**Comment by lforst** [comment]
Hi, we just released a "fix" for this in the latest release!
