### ISSUE TITLE
Add `bundlesizeOptimizations` options to docs

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-javascript-bundler-plugins#518]
we export [options](https://github.com/getsentry/hackweek-sentry-unplugin/blob/5bd855d3fe0e30bd7d1beb0b29dad8da4c2fc416/packages/bundler-plugin-core/src/types.ts/#L231-L234) around automating tree shaking but don't document them at the moment. We should add the options to the documentation generation script.

**Comment by s1gr1d** [comment]
Was added here: https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/582/files#diff-5cae8150c6ef04a7e9356e37f46c0d36edc662f5a028861874a82ce1534b5e43
