### ISSUE TITLE
Source map loaded and connected to release, but still don't see any readable trace

### ISSUE THREAD

**Issue by Lvovk** [getsentry/sentry-javascript-bundler-plugins#519]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I wanted to upload source map to sentry, so I could see readable source code and error trace 

So, I use webpack plugin this way(pic 1). And it seems to be loading source maps to sentry and connecting it to proper release (pic 2), but I can't see any source-code-mantions (pic 3)

Is it expected? Or how can i Fix it ?

![image](https://github.com/getsentry/sentry/assets/119592873/9b3e3b4a-2c72-41e5-bc59-ffe90b5b827a)
![image](https://github.com/getsentry/sentry/assets/119592873/46e401a6-cda8-40b0-b67e-30ce2ef35cb4)
![image](https://github.com/getsentry/sentry/assets/119592873/fd540a05-0f74-4a2c-ad2e-6d32e9e0adf3)

### Expected Result

Source map loaded, connected to release, and I see readable source code trace

### Actual Result

Source map loaded, connected to release, but I don't see souce code trace

### Product Area

Unknown

### Version

7.106.0

**Comment by Lms24** [comment]
Hi @Lvovk!

I think the problem is much rather that there is no stack trace rather than the source code not being unminified with the uploaded source maps. Since you're using Sentry SaaS (sentry.io), can you post a link to the event in Sentry? 

Furthermore, to debug this please:
* tell us your SDK version
* show your `Sentry.init` code
* tell us how to reproduce this behaviour in a minimal reproduciton.
Or, ideally, provide a Stackblitz/GH repo or similar with a working minimal reproducible example. thanks!

**Comment by Lvovk** [comment]
Hi @Lms24 ! Thanks for the answear !

Link to the event: https://notsy-b-v.sentry.io/issues/5168873424/events/2fd0e174c105437196a0a3e053d5260e/
My SDK version is 7.106.0
My Sentry init looks like this (img 1) 

How to reproduce:

1. I use webpack plugin, which is suposed to load sourcemap to sentry and it seems to do it
2. I have added mock errors (tried "Throw" experssions, syntax errors and ETC) inside my code and started the page 
3. I see those errors on sentry, but can't see the trace

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/119592873/25911c1c-8189-48e8-b846-6a9e997dd0d3)

**Comment by Lms24** [comment]
> I have added mock errors (tried "Throw" experssions, syntax errors and ETC) inside my code and started the page

I looked at the event you linked and I can confirm that the SDK did not send a stack trace to Sentry. How exactly are you throwing and capturing this error? Are you using `Sentry.captureMessage`/`Sentry.captureException` or are you simply doing something like `throw('test string')`? Also _where_ are you throwing the error? Any chance it's directly in a <script> tag? On button click? 

Generally, the SDK should try to generate a stack trace, even if the value that's captured (e.g. just a string) doesn't have a stacktrace attached. So I'm wondering where things go wrong here.

As you can see, there are quite a few variables to debug this properly. I assume you're adding Sentry to a non-trivial application - any chance you can narrow it down to a more minimal example and post it as a stackblitz or GitHub repo?
