### ISSUE TITLE
Sourcemapping broken with vite 5.1.7 and 5.2.10

### ISSUE THREAD

**Issue by bickauskaslaurynas** [getsentry/sentry-javascript-bundler-plugins#529]
### Environment

What version are you running? Etc.
multiple vue projects tested using these versions 
"vite": "5.1.7" + "@sentry/vite-plugin": "2.7.0",
"vite": "5.1.7" + "@sentry/vite-plugin": "2.16.1",
 "vite": "5.2.10", + "@sentry/vite-plugin": "2.16.1",
 
 vue and sentry vue versions:  "@sentry/vue": "7.111.0", "vue": "3.4.3" some other versions on other projects same issue

### Steps to Reproduce
Had well working sourcemaping with vite 5.1.1 version at our projects
bumped vite to 5.1.7 to resolve security issue
sourcemapping broke it now maps incorrectly to completely irrelevant component 
80% of all issues sources now map to the same component on a project 

Same issue on multiple projects after bumping to 5.1.7

### Expected Result
sourcemapping works as it did with Vite 5.1.1

### Actual Result
80% of issues are sourcemapped to the same irrelevant component

**Comment by lforst** [comment]
Hi, this sounds more like a vite bug tbh. Was there any particular reason you reported it here we should look into? Would you mind opening an issue in the vite repository? Ideally with reproduction.

**Comment by bickauskaslaurynas** [comment]
@lforst 
`Was there any particular reason you reported it here we should look into?` 
I guess the reason is lack of knowledge on how sourcemapping, vite, sentry vite work together (what does what), my assumption was that sentry is the one that is generating sourcemaps and that a minor version bump of vite could not break this, but your comment makes me think now that vite does the generation and sentry plugin only does the uploading, maybe something more. Do you have any resources for me to understand the responsibilities of each package better ?

`Would you mind opening an issue in the vite repository?` 
I could do that for sure but i am not sure how to check if generated sourcemaps are good or not how could i do that without using sentry. I mean i can generate sourcemaps by running production build locally but i dont know how to tell if the issue is reproduced or not any tips or resources for me to be able to figure this out ? I would like to track down the exact change on vite that resulted in this bug then.

**Comment by lforst** [comment]
> `Was there any particular reason you reported it here we should look into?`
> I guess the reason is lack of knowledge on how sourcemapping, vite, sentry vite work together

Totally fine, no blame on you 😄. Vite (and also potentially some vite plugins you have installed) is the one generating the source maps. My suspicion is that vite introduced a regression generating source maps in a patch of theirs. The Sentry vite plugin only picks up the generated source maps and uploads them to Sentry.

> `Would you mind opening an issue in the vite repository?`
> I could do that for sure but i am not sure how to check if generated sourcemaps are good or not how could i do that without using sentry.

I usually use https://sokra.github.io/source-map-visualization/ or https://marketplace.visualstudio.com/items?itemName=colder.source-map-visualization to verify sourcemaps. You could also do a prod build locally and try and see your assets in the browser-dev tools.

I think if you provide the Vite folks with a test app that shows right sourcemaps for version A and wrong sourcemaps for version B, they're already gonna be pretty happy.

**Comment by bickauskaslaurynas** [comment]
Actually i found that on one of our projects we didnt even bump vite, on package-lock the version stayed the same, and only esbuild was changed in package-lock.json and it broke , does that point to an issue with esbuild then ? how could that be ?

**Comment by lforst** [comment]
Potentially yes.

**Comment by bickauskaslaurynas** [comment]
@lforst i am having quite a bit of trouble identifying / pinpointing the issue
what i found is that the generated sourcemaps seem to have a line missmatch, so lets say raw stacktracke says 
: 13: 46048
in sourcemap line 13 is empty but you can actually find the source if you just go to 
: 14: 46048 this ends up being the source of the error 

any ideas on what could be causing this

**Comment by lforst** [comment]
Did you report the issue to the vite folks? I really recommend directing the discussion there. Also, what browser are you using? (exact version) Some browsers have off-by one errors in their stack traces. Could also be something like an off-by one in vite.

**Comment by bickauskaslaurynas** [comment]
Created the bug on Vite

**Comment by bickauskaslaurynas** [comment]
Was not able to replicate with just Vite on a smaller project so kept looking, after a while I've identified that the issue was not vite itself but rather that the differently generated vite file after going through cloudflare js minification lost a line.
After turning off this minification sourcemapping works.
