### ISSUE TITLE
[Help]: Change project release details for uploaded sourcemaps

### ISSUE THREAD

**Issue by jd-carroll** [getsentry/sentry-javascript-bundler-plugins#534]
We have 100+ lambda functions we are bring on to Sentry for monitoring and then eventually using metrics 🎊 

I've just wrapped up the majority of the integration and I'm looking through the "releases" on Sentry, which look like:
<img width="1067" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/1885864/3a8fa955-afa4-4a29-8fc0-2193275970b2">

Under `Project Release Details` there is a `Package` field which is empty. **Is there a way to add a "package" name?** (I didn't see an option under `release` for the esbuild plugin.)

My objective is to clearly show the lambda function name so that it is easy to know which lambda we are working with. Ideally, there would be a way to have the lambda function name (package name?) and the separately have a version (version?).

Additionally, is there a length limitation for the Version? If there is no way to provide a "Package" name, then I can cannibalize the package name to use the format: `${lambdaName}_${version}_${gitSha}`

**Comment by Lms24** [comment]
Hey @jd-carroll it took me a minute to find the respective documentation for this but you can set the package name by specifying it in the `release.name` option in a specific format (see [docs here](https://docs.sentry.io/platforms/javascript/configuration/releases/#bind-the-version))

> Additionally, is there a length limitation for the Version? If there is no way to provide a "Package" name, then I can cannibalize the package name to use the format: ${lambdaName}_${version}_${gitSha}

I'm not sure about a length limit but I'd recommend trying this format to get all three parts in:

```js
release: {
  name: '${lambdaName}@${version}+${gitSha}'
}
```

**Comment by jd-carroll** [comment]
Thank you, I had missed that "cannot" section
