### ISSUE TITLE
`moduleMetadata` and or `moduleMetadataIntegration` do not work with `vite-plugin`

### ISSUE THREAD

**Issue by oskar-dragon** [getsentry/sentry-javascript-bundler-plugins#543]
I am not sure whether this is a bug or I am doing something wrong but I've been following [this guide](https://docs.sentry.io/platforms/javascript/best-practices/micro-frontends/) while setting up Sentry for microfrontends and unfortunately it doesn't work. Any help or guidance would be appreciated and thank you in advance for your patience and understanding.

### Environment

I have a monorepo with two applications that work as micro-frontends. 
- **Host app**: React app with Vite and Tanstack Router
- **Microfrontend app**: Vue 2.0 app with Vite

for Microfrontend implementation I am using `single-spa`.

I am following the guide provided in your best practices, but for some reason, the module metadata is missing.

This is my Vite configuration with `sentryVitePlugin`. The microfrontend app setup is very similar, just different DSN.
```
import path from 'node:path';
import { sentryVitePlugin } from '@sentry/vite-plugin';
import { TanStackRouterVite } from '@tanstack/router-vite-plugin';
import react from '@vitejs/plugin-react-swc';
import { defineConfig, loadEnv } from 'vite';
import vitePluginSingleSpa from 'vite-plugin-single-spa';

// https://vitejs.dev/config/
/** @type {import('vite').UserConfig} */
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), 'SENTRY_');
  return {
    build: {
      sourcemap: true,
    },
    server: {
      port: 8081,
    },
    preview: {
      port: 8081,
    },
    plugins: [
      react(),
      TanStackRouterVite(),
      vitePluginSingleSpa({
        type: 'root',
        imo: '3.1.1',
        importMaps: {
          dev: ['importMap.dev.json'],
          build: ['importMap.json'],
        },
      }),
      sentryVitePlugin({
        authToken: env.SENTRY_AUTH_TOKEN,
        project: '__PROJECT__',
        org: '__ORG__',
        _experiments: {
          moduleMetadata: ({ release }: { project: string; release: string }) => ({
            dsn: __HOST_APP_DSN__
            release,
          }),
        },
        sourcemaps: {
          // Directory specified containing build artifacts
          assets: './**',
          // Don't upload the source maps of dependencies
          ignore: ['./node_modules/**', 'vite.config.ts'],
        },
        reactComponentAnnotation: { enabled: true },
      }),
    ],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
      },
    },
  };
});
```

I run `sentry.init()` within the React app and nothing in the Vue app as per documentation to avoid creating two instances of Sentry in a browser. sentry.init() is being imported in the root React component of our application.

`sentryInit.ts`
```
import { clientEnv } from '@repo/utils';
import * as Sentry from '@sentry/react';

import { router } from '../tanstackRouter/router';

const EXTRA_KEY = 'ROUTE_TO';

const transport = Sentry.makeMultiplexedTransport(Sentry.makeFetchTransport, (args) => {
  const event = args.getEvent();

  console.log({ event });

  if (event && event.extra && EXTRA_KEY in event.extra && Array.isArray(event.extra[EXTRA_KEY])) {
    return event.extra[EXTRA_KEY];
  }
  return [];
});

Sentry.init({
  dsn: __DSN__,
  environment: clientEnv.VITE_APP_MODE,
  tunnel: __TUNNEL_URL__,
  integrations: [
    Sentry.moduleMetadataIntegration(),
    Sentry.tanstackRouterBrowserTracingIntegration(router),
    Sentry.zodErrorsIntegration(),
  ],
  transport,
  beforeSend: (event, hint) => {
    console.log('beforeSend', { event });
    if (event?.exception?.values?.[0]?.stacktrace?.frames) {
      const { frames } = event.exception.values[0].stacktrace;
      // Find the last frame with module metadata containing a DSN
      const routeTo = frames
        .filter((frame) => frame.module_metadata && frame.module_metadata.dsn)
        .map((v) => v.module_metadata)
        .slice(-1); // using top frame only - you may want to customize this according to your needs

      if (routeTo.length) {
        // eslint-disable-next-line no-param-reassign
        event.extra = {
          ...event.extra,
          [EXTRA_KEY]: routeTo,
        };
      }
    }

    return event;
  },
// rest of config
});

```

### What version are you running? Etc.
@sentry/react: "^8.7.0",
@sentry/vue: "^8.7.0",
@sentry/vite-plugin: "^2.17.0"

### Expected Result

The module medata would be passed to sentry so we can access it at runtime so we can redirect errors to a right project.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?
![Screenshot 2024-06-04 at 12 37 59](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/32719913/0811f004-7d1e-499a-ab37-fdd12e1cfa4d)

**Comment by lforst** [comment]
Hi, what is the exact version of the vite plugin you are using and if you print `_sentryModuleMetadataGlobal` in your browser console, what shows up?

**Comment by oskar-dragon** [comment]
I use v`2.17.0` and I've just updated it to 2.18.0. No change.

When I tried to print `_sentryModuleMetadataGlobal` it was undefined, however, `_sentryModuleMetadata` is available and this is what I can see. However, it's only in preview mode or when the app is already deployed, not in serve/dev mode. 

![Screenshot 2024-06-04 at 15 03 39](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/32719913/3067a45f-244a-4e0f-84a6-6d61b586fec7)

**Comment by oskar-dragon** [comment]
@lforst 

The version of vite plugin is `2.17.0` and

**Comment by oskar-dragon** [comment]
I use v`2.17.0` and I've just updated it to 2.18.0. No change.

When I tried to print `_sentryModuleMetadataGlobal` it was undefined, however, `_sentryModuleMetadata` is available and this is what I can see. However, it's only in preview mode or when the app is already deployed, not in serve/dev mode. 

![Screenshot 2024-06-04 at 15 03 39](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/32719913/3067a45f-244a-4e0f-84a6-6d61b586fec7)

**Comment by lforst** [comment]
Ah, It looks like you have a dev server running in your original post. This might not work for dev-mode as vite maybe doesn't process node_modules with the sentryPlugin. Can you try prod mode?

**Comment by oskar-dragon** [comment]
It looks that it works once built. However, events are not being router to the project.

**Comment by lforst** [comment]
Can you log what is returned from your `makeMultiplexedTransport` callback?

**Comment by oskar-dragon** [comment]
It is working now. My last issue was dependency version not aligning between projects. Thanks for you help!
