### ISSUE TITLE
`filesToDeleteAfterUpload` is deleting files before upload in latest versions

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-javascript-bundler-plugins#556]
### Environment

`@sentry/vite-plugin`

### Steps to Reproduce

1. Install latest version of vite plugin 2.20.0 or 2.19.0
2. add the filesToDeleteAfterUpload option.  Mine is `sourcemaps: {filesToDeleteAfterUpload: ["distVite/assets/**.js.map"]}`
3. See the upload logs not include the map file that I listed as to delete after upload.

[Resulting Bundle in my org](https://francisorg.sentry.io/settings/projects/bundlers/source-maps/artifact-bundles/719caf68-d8fd-567c-8913-c5b2ef681901/)

Downgrading to 2.18.0 or lower seems to make it work again.  [Bundle from 2.18.0 with both the source and map.](https://francisorg.sentry.io/settings/projects/bundlers/source-maps/artifact-bundles/0ed51309-f442-558c-9df3-9386a497ae5d/)

### Expected Result

Files should be deleted after upload

### Actual Result

Files are being deleted prior to upload

**Comment by Fwang36** [comment]
Awesome thanks!

Here are all my options for the plugin currently.

```
    sentryVitePlugin({

      org: process.env.VITE_SENTRY_ORG,
      project: process.env.VITE_SENTRY_PROJECT,
      authToken: process.env.VITE_SENTRY_AUTH_TOKEN,

      sourcemaps: {filesToDeleteAfterUpload: ["distVite/assets/**.js.map"]}
      
    })
```

**Comment by lforst** [comment]
@Fwang36 we released a new version `2.20.1` with a fix. Can you try it out?

**Comment by Fwang36** [comment]
Yes, I just tried it and it works again in `2.20.1`

Thanks!

**Comment by julianCast** [comment]
Hi! This is also happening in `@sentry/webpack-plugin`

**Comment by lforst** [comment]
It should also be fixed in the webpack plugin.
