### ISSUE TITLE
Sentry sourcemap use `@vitejs/plugin-legacy` and `@sentry/vite-plugin` conflict.

### ISSUE THREAD

**Issue by itaober** [getsentry/sentry-javascript-bundler-plugins#564]
### Environment
Node: `v18.16.0`
Vite: `v5.3.1 (latest)`
@sentry/vite-plugin: `^2.20.0`
@vitejs/plugin-legacy: `^5.4.1`
Project created using `npm create vite`, and choose `React + TypeScript`

What version are you running? Etc.

### Steps to Reproduce
1. Create a new Vite project.
2. Config `@vitejs/plugin-legacy`.
3. Config `sentryVitePlugin`, like this:
vite.config.ts:
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import legacy from "@vitejs/plugin-legacy";
import { sentryVitePlugin } from "@sentry/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    sourcemap: true,
  },
  plugins: [
    react(),
    legacy({
      targets: ["defaults", "not IE 11"],
    }),
    // notice: ... is my private config
    sentryVitePlugin({
      url: "...",
      org: "...",
      project: "...",
      authToken: "...",
      release: {
        name: "...",
      },
      sourcemaps: {
        assets: "dist/assets/**",
        ignore: ["node_modules"],
        filesToDeleteAfterUpload: "dist/**/*.map",
      },
    }),
  ],
});
```
4. Add the following to `App.tsx` to test:
App.tsx:
```
// ...
<button
  onClick={() => {
      throw new Error("VITE SENTRY");
    })
  }
>
  count is {count}
</button>
// ...
```

### Expected Result

The expected result is similar to the second image under the "Actual Result" section.

### Actual Result

With the legacy plugin enabled:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/102474041/bc550256-bb3a-4d28-9c96-d6a005f90467)

Without the legacy plugin:
vite.config.ts:
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import legacy from "@vitejs/plugin-legacy";
import { sentryVitePlugin } from "@sentry/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    sourcemap: true,
  },
  plugins: [
    react(),
    // notice: ... is my private config
    sentryVitePlugin({
      url: "...",
      org: "...",
      project: "...",
      authToken: "...",
      release: {
        name: "...",
      },
      sourcemaps: {
        assets: "dist/assets/**",
        ignore: ["node_modules"],
        filesToDeleteAfterUpload: "dist/**/*.map",
      },
    }),
  ],
});
```
This configuration works correctly:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/102474041/f4b77665-ccf4-447c-9dd2-ca0af9a768bb)

When using the legacy plugin, the build uploads two sourcemaps:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/102474041/0d630f2f-3ee3-425b-9f90-eda7413e8884)
Without the legacy plugin, only one sourcemap is uploaded:
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/102474041/72001477-a32e-4022-989c-b4cd4b21ab89)

### Issue
I need to use the legacy plugin, but it seems incompatible with Sentry sourcemaps. Any help would be appreciated.

**Comment by lforst** [comment]
Hi, can you try version `2.20.1` of the `@sentry/vite-plugin`? Thanks!

**Comment by itaober** [comment]
> Hi, can you try version `2.20.1` of the `@sentry/vite-plugin`? Thanks!

Thank you for your suggestion. I tried version `2.20.1` of the `@sentry/vite-plugin`, but the issue persists.

I noticed that with the `legacy` plugin enabled, the sourcemaps are uploaded twice during the build:
<img width="860" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/102474041/09d74412-8867-47ee-8c9b-49fc5da583ed">

When the `legacy` plugin is disabled, the sourcemaps are only uploaded once:
<img width="737" alt="image" src="https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/102474041/7f69faae-210a-44f0-9b7a-efb64c5aef8f">

Because of this, Sentry errors cannot be mapped to the source code locations. I believe this issue is related to the double upload of sourcemaps, but I'm not sure how to resolve it. I encountered this problem with a newly created Vite project with minimal configuration.

Any assistance would be greatly appreciated.

Thank you!

**Comment by itaober** [comment]
And this is my `package.json`:
````
{
  "name": "sentry-test",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@typescript-eslint/eslint-plugin": "^7.13.1",
    "@typescript-eslint/parser": "^7.13.1",
    "@vitejs/plugin-react": "^4.3.1",
    "eslint": "^8.57.0",
    "eslint-plugin-react-hooks": "^4.6.2",
    "eslint-plugin-react-refresh": "^0.4.7",
    "typescript": "^5.2.2",
    "vite": "^5.3.1",
    "@sentry/vite-plugin": "^2.20.1",
    "@vitejs/plugin-legacy": "^5.4.1",
    "@sentry/react": "^8.11.0"
  }
}
```

**Comment by itaober** [comment]
I was wondering if it's possible to upload the sourcemap after the build is finished, rather than during the build, but I haven't been able to configure the `@sentry/vite-plugin` to do this.

**Comment by lforst** [comment]
I think our Vite plugin is incompatible with `vitejs/plugin-legacy` due to it doing funky stuff during build. Please use Sentry CLI to upload source maps for now: https://docs.sentry.io/platforms/javascript/guides/angular/sourcemaps/uploading/cli/

**Comment by itaober** [comment]
> I think our Vite plugin is incompatible with `vitejs/plugin-legacy` due to it doing funky stuff during build. Please use Sentry CLI to upload source maps for now: https://docs.sentry.io/platforms/javascript/guides/angular/sourcemaps/uploading/cli/

I use the `@sentry/cli` upload sourcemap, this is my config:

.sentryclirc:
```
[auth]
token = xxx
[defaults]
url = xxx
org = sentry
project = react-sentry-test
```

package.json -> scripts:
```
"sentry": "sentry-cli releases files 0.0.1 upload-sourcemaps --url-prefix '~/assets' './dist/assets'"
```

I upload sourcemap success, but it not work, can you help me check if the configuration is correct?
![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/102474041/a7d21762-3a39-4f7c-a5d5-df84f309df5d)

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/102474041/93d1902e-06cf-4bb5-8ce8-2371d8f3b436)

**Comment by lforst** [comment]
Please follow the guide I linked. It is different from your setup.

**Comment by tyouzu1** [comment]
> I think our Vite plugin is incompatible with `vitejs/plugin-legacy` due to it doing funky stuff during build. Please use Sentry CLI to upload source maps for now: https://docs.sentry.io/platforms/javascript/guides/angular/sourcemaps/uploading/cli/

So will this problem be solved, or does it need to be solved by Vite?

**Comment by lforst** [comment]
@tyouzu1 we are currently not looking into it. I think the vite folks should likely also investigate.

**Comment by tyouzu1** [comment]
@lforst 
I I checked the execution logic of `vite legacy.` 
It seems `legacy` will use `outputOptions`, so `writeBundle` to be [triggered twice](https://rollupjs.org/plugin-development/#writebundle)
However, the `deletion task` that is triggered for the second time seems to be executed in an *earlier* order.

I didn't have enough time to check the logic of the sentry plugin,So I can only provide simple suggestions, such as forcing the deletion task to be executed last.
[https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/568](https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/568)

I can't guarantee there are no bugs, if you have time maybe you can help me take a look, If you need anything else, let me know

The log looks like this,  with `[debug] upload` and `[debug] delete`
```bash
dist/assets/index-legacy-Lvy-jIUq.js       0.63 kB │ gzip:  0.36 kB │ map: 1.73 kB
dist/assets/polyfills-legacy-DlS80YAc.js  55.74 kB │ gzip: 22.43 kB
----------------------[debug] upload  [
  '4a719ab0-69d1-4fea-8dfe-0583bff4b570-0.js',
  '4a719ab0-69d1-4fea-8dfe-0583bff4b570-0.js.map'
] [ Promise { <pending> }, Promise { <pending> } ]
> Found 2 files
> Analyzing 2 sources
> Bundled 2 files for upload
[sentry-vite-plugin] Info: Successfully uploaded source maps to Sentry
> Found 3 files
> Analyzing 3 sources
> Nothing to upload
----------------------[debug] delete  [
  '/xxxxx/dist/assets/index-legacy-Lvy-jIUq.js.map'
]
dist/index.html                2.03 kB │ gzip: 0.94 kB
dist/assets/index-CCZnuigm.js  1.32 kB │ gzip: 0.71 kB │ map: 1.71 kB
----------------------[debug] delete  [
  '/xxxxx/dist/assets/index-CCZnuigm.js.map'
]
----------------------[debug] upload  [
  '4a719ab0-69d1-4fea-8dfe-0583bff4b570-1.js',
  '4ae9580f-02df-4968-9b14-31508fe6e9e9-0.js'
] [ Promise { <pending> }, Promise { <pending> } ]
> Found 2 files
> Analyzing 2 sources
```
After modification, it looks like

```bash
dist/assets/index-legacy-Lvy-jIUq.js       0.63 kB │ gzip:  0.36 kB │ map: 1.73 kB
dist/assets/polyfills-legacy-DlS80YAc.js  55.74 kB │ gzip: 22.43 kB
----------------------[debug] upload  [
  '4a719ab0-69d1-4fea-8dfe-0583bff4b570-0.js',
  '4a719ab0-69d1-4fea-8dfe-0583bff4b570-0.js.map'
] [ Promise { <pending> }, Promise { <pending> } ]
> Found 2 files
> Analyzing 2 sources
> Uploaded files to Sentry
> Found 3 files
> Analyzing 3 sources
> Nothing to upload
----------------------[debug] delete  [
  '/xxxxxx/dist/assets/index-legacy-Lvy-jIUq.js.map'
]
dist/index.html                2.03 kB │ gzip: 0.94 kB
dist/assets/index-CCZnuigm.js  1.32 kB │ gzip: 0.71 kB │ map: 1.71 kB
----------------------[debug] upload  [
  '4a719ab0-69d1-4fea-8dfe-0583bff4b570-1.js',
  '4ae9580f-02df-4968-9b14-31508fe6e9e9-0.js',
  '4ae9580f-02df-4968-9b14-31508fe6e9e9-0.js.map'
] [ Promise { <pending> }, Promise { <pending> }, Promise { <pending> } ]
> Found 3 files
> Analyzing 3 sources
> Bundled 3 files for upload
> Uploaded files to Sentry
[sentry-vite-plugin] Info: Successfully uploaded source maps to Sentry
> Found 4 files
> Analyzing 4 sources
----------------------[debug] delete  [
  '/xxxxx/dist/assets/index-CCZnuigm.js.map'
]
```

**Comment by lforst** [comment]
That's some nice investigation. Thanks a lot! I'll take a look whether I can get your fix in.

**Comment by lforst** [comment]
@tyouzu1 we released the changes, does it fix the problem?

**Comment by tyouzu1** [comment]
> @tyouzu1 we released the changes, does it fix the problem?

Thanks . It completely solved my case.

![image](https://github.com/getsentry/sentry-javascript-bundler-plugins/assets/26712711/86800117-a968-4ed1-93c2-463fdff3f627)

**Comment by lforst** [comment]
Closing this then. Let me know if there are any more issues!
