### ISSUE TITLE
vite-plugin Docs should provide guidance and exmaples for removing source maps after upload

### ISSUE THREAD

**Issue by douglasg14b** [getsentry/sentry-javascript-bundler-plugins#567]
The docs here: https://docs.sentry.io/platforms/javascript/guides/vue/sourcemaps/uploading/vite/#automatic-setup

Make no mention of the problem around always generating sourcemaps for builds, which is exposing them in production.

The docs should call this out, and provide guidance on how to avoid this problem.

**Comment by lforst** [comment]
Hi, thanks for writing in! You are completely right, we should highlight this way more in our docs. I'll get to it soon.
