### ISSUE TITLE
Update `@sentry/node` to v8

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-javascript-bundler-plugins#579]
We still use v7 of the Node SDK, we should bump our own usage to v8.

We can also explore using `ServerRuntimeClient` from `@sentry/core` instead of `NodeClient`. We only manually create a client, so maybe we can skip the OTEL dependencies etc. here.

**Comment by timfish** [comment]
I've mostly completed the migration to v8 but the build fails with the previously reported issue with `opentelemetry-instrumentation-fetch-node`.

I can either wait until this dependency gets removed or drop `@sentry/node` entirely as a dependency. At this point the only export we need is the Node transport.

![Image](https://github.com/user-attachments/assets/7717a674-02f9-40e9-a08d-a836bedac03b)

**Comment by timfish** [comment]
Ah, I added that to externals and hit a load of other bundling warnings and issue with otel 😂

![Image](https://github.com/user-attachments/assets/2ecaa5bf-b2ff-4795-a924-19fdf45ffd10)
