### ISSUE TITLE
Cannot use import statement outside a module issue, when upgrading from 2.16.1 to 2.17.0

### ISSUE THREAD

**Issue by borkanee** [getsentry/sentry-javascript-bundler-plugins#583]
Upgrading from 2.16.1 to 2.17.0 gives us

import "./_sentry-release-injection-file-.js";

Uncaught SyntaxError: Cannot use import statement outside a module

Any idea why this happens?

**Comment by andreiborza** [comment]
Hi @borkanee, do you have a reproduction repo or stackblitz we could take a look? We need more details to investigate this.

**Comment by AbhiPrasad** [comment]
Closing this for clean-up. Please re-open if it still applies. Thank you!
