### ISSUE TITLE
Vite production build failed due to SENTRY_RELEASE containing double quotes

### ISSUE THREAD

**Issue by kenn** [getsentry/sentry-javascript-bundler-plugins#584]
### Environment

Latest everything

### Steps to Reproduce

1. Set git commit as release string with `process.env.SENTRY_RELEASE = execSync('git log -1 --pretty=%B')`
2. Get error on production build with a following error:

```js
_global.SENTRY_RELEASE={id:"commit containing "double quotes""};
```

### Expected Result

If it's stored in a JSON, double quotes should be escaped appropriately.

### Actual Result

![Image](https://github.com/user-attachments/assets/74df5268-9114-44d2-a25c-b5ada0c8a4e6)

**Comment by lforst** [comment]
Small note though: You're assigning a buffer to `process.env. SENTRY_RELEASE` which is probably not the best idea 😄 Maybe do `.toString()` or decode as `utf8` so that it becomes a string.

**Comment by kenn** [comment]
Thanks for the quick fix!

That was for reporting abbreviation and this was the actual code, for anyone who finds it useful.

```js
// Get the git info
const DATE = execSync(
  "git log -1 --date=format:'%Y-%m-%d' --pretty=format:'%ad'",
)
  .toString()
  .trim()
const MESSAGE = execSync('git log -1 --pretty=%B')
  .toString()
  .trim()
  .split('\n')[0]
  .slice(0, 20)
const HASH = execSync('git rev-parse --short HEAD').toString().trim()
process.env.SENTRY_RELEASE = `${DATE} ${MESSAGE} - ${HASH}`
```
