### ISSUE TITLE
Disable in vite plugin doesnt stop requesting through retry count

### ISSUE THREAD

**Issue by kyeshmz** [getsentry/sentry-javascript-bundler-plugins#590]
### Environment

"@sentry/vite-plugin": ^2.22.2

### Steps to Reproduce

1. Create vite with
```
 plugins: [
      react(),
      sentryVitePlugin({
        org: "----",
        project: "-----",

        disable: true,
        telemetry:false,

      }),
    ],
```

### Expected Result
No logging

### Actual Result
I still get this error because of adblock? Even still, I think this shouldn't be emitting.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://us.i.posthog.com/e/?retry_count=1&ip=1&_=--------&ver=1.151.0&compression=base64. (Reason: CORS request did not succeed).
```

This just fills my console.log which hinders local dev.

**Comment by lforst** [comment]
Hi, I don't fully understand. The request you shared is for posthog and not Sentry and I also don't think the vite plugin would affect browser requests like that in any way.

**Comment by kyeshmz** [comment]
Oh my. Should have noticed sooner, apologies.
