### ISSUE TITLE
Error with stack traces display - incorrect paths for uploaded source maps

### ISSUE THREAD

**Issue by pdziewa** [getsentry/sentry-javascript-bundler-plugins#599]
I'm encountering an issue with the display of error stack traces. The stacks appear as follows:

![Image](https://github.com/user-attachments/assets/a9f2f3e6-f91d-4eb2-af5a-a7cd1480b608)

The uploaded source maps are displayed like this:

![Image](https://github.com/user-attachments/assets/2d04ac99-52f5-486a-81c0-49c54851a980)

I suspect there may be an issue with the paths. In another Next.js project that I have set up, which operates without any issues, the paths include `~/_next/static/chunks/...`

**Versions**
- Sentry (self-hosted) - `24.3.0`
- next - `14.2.3`
- @sentry/nextjs - `8.27.0`

**Configuration**

`next.config.js`

```js
[...]

module.exports = withSentryConfig(module.exports, {
  org: 'xxx',
  project: 'xxx',
  sentryUrl: 'xxx',

  silent: !process.env.CI,
  telemetry: false,
  debug: true,

  widenClientFileUpload: true,
  disableLogger: true,
  automaticVercelMonitors: false,
});
```

**Comment by pdziewa** [comment]
I will request our DevOps team to retrieve the logs tomorrow.

**Comment by pdziewa** [comment]
So our DevOps checked the logs, but there were no logs at all.

**Comment by lforst** [comment]
@pdziewa No logs at all may indicate that the service isn't running at all. The `symbolicator` service is critical for source mapping. Can you check that it runs? Thanks!

**Comment by pdziewa** [comment]
Uptime ~2 months

**Comment by lforst** [comment]
Honestly, no idea what could be going on then. We need more information in general on your source files, what they look like, event payload, ...

**Comment by pdziewa** [comment]
Just a quick update: we've upgraded Sentry to version `24.8.0`, and I've made a couple of adjustments:

- I've removed the `productionBrowserSourceMaps: true` from the Next.js configuration.
- I've set `hideSourceMaps: true` in the Sentry configuration.

Now, it seems that the stack traces are functioning correctly.
