### ISSUE TITLE
Can the rsbuild plugin be supported?

### ISSUE THREAD

**Issue by mengbo-ji** [getsentry/sentry-javascript-bundler-plugins#607]
Hi, I'm using [rsbuild ](https://rsbuild.dev/zh/plugins/list/index)

but my project uses the sentry monitoring system, I hope you can support rsbuildPlugin!

![Image](https://github.com/user-attachments/assets/4ed40edb-a42a-4f36-9a48-0f36cf41fa47)

**Comment by AbhiPrasad** [comment]
cc @smeubank 

https://www.npmjs.com/package/@rsbuild/core

![Image](https://github.com/user-attachments/assets/4cbb2d4b-b6bf-4d21-a6db-b819fca7e985)

there is pretty solid adoption, so I think we should start considering it. Maybe when it gets above 100k weekly downloads?

**Comment by AbhiPrasad** [comment]
@mengbo-ji for now you can use `tools.rspack` (https://rsbuild.dev/zh/config/tools/rspack#toolsrspack) and add the sentry webpack plugin: https://www.npmjs.com/package/@sentry/webpack-plugin

**Comment by eliliam** [comment]
@mengbo-ji or @AbhiPrasad, could you provide an example of how to properly configure this as @AbhiPrasad described? I'm having a difficult time figuring that part out.

**Comment by lforst** [comment]
I haven't tried it myself tbh but I'd assume that you would just have to add the webpack plugin here: https://rspack.dev/guide/migration/webpack#community-plugins

What exactly isn't working?

**Comment by ephill** [comment]
Can confirm that `tools.rspack` works just fine:
```
  tools: {
    rspack: (config, { appendPlugins }) => {
...
          appendPlugins([
            sentryWebpackPlugin({
              authToken: process.env.SENTRY_AUTH_TOKEN,
              org: 'foo',
              project: 'bar'
            })
          ]);
...
      return config;
    }
```
in my RsBuild config worked without issue.

**Comment by basitqayoom** [comment]
SHELL Application RsBuild Config:

```
const EXTRA_KEY = 'ROUTE_TO';

const transport = makeMultiplexedTransport(makeFetchTransport, args => {
  const event = args.getEvent();
  if (
    event &&
    event.extra &&
    EXTRA_KEY in event.extra &&
    Array.isArray(event.extra[EXTRA_KEY])
  ) {
    return event.extra[EXTRA_KEY];
  }
  return [];
});

init({
  dsn: 'https://88c48b1b16d1657bf55218fb9a73107e@o4508374916726784.ingest.us.sentry.io/4508374919479296',
  integrations: [moduleMetadataIntegration()],
  transport,
  beforeSend: event => {
    if (event?.exception?.values?.[0]?.stacktrace?.frames) {
      const { frames } = event.exception.values[0].stacktrace;
      // Find the last frame with module metadata containing a DSN
      const routeTo = frames
        .filter(frame => frame.module_metadata && frame.module_metadata.dsn)
        .map(v => v.module_metadata)
        .slice(-1); // using top frame only - you may want to customize this according to your needs

      if (routeTo.length) {
        // eslint-disable-next-line no-param-reassign
        event.extra = {
          ...event.extra,
          [EXTRA_KEY]: routeTo,
        };
      }
    }

    return event;
  },
});
```





Remote Application RSBuild Config :

```
  tools: {
    webpack: {
      plugins: [
        sentryWebpackPlugin({
          moduleMetadata: ({ release }) => ({
            dsn: "REMOTE_DSN",
            release,
          })
        })
      ],
    },
  },
```




on printing event which is being sent, there are not meta data inside the events when printed from shell application side. Any idea why?

**Comment by chargome** [comment]
@basitqayoom not sure about your rsbuild setup but have you tried the setup in the comment above (adding the config to `tools.rspack`)?

**Comment by andreiborza** [comment]
Closing for cleanup. See:

> I haven't tried it myself tbh but I'd assume that you would just have to add the webpack plugin here: https://rspack.dev/guide/migration/webpack#community-plugins
> 
> What exactly isn't working?

If this is still an issue, please re-open.
