### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by ethanlaj** [getsentry/sentry-javascript-bundler-plugins#612]
### Environment

Latest vite plugin, latest @sentry/vite-plugin. Happens on older versions too

### Steps to Reproduce

1. Clone https://github.com/ethanlaj/vite-sentry-plugin-issue
2. Delete `.git` directory from the cloned folder
3. Run `npm install`
4. Run `npm run preview`

### Expected Result

A fatal error would not be logged into the console when the git repository isn't available. This is needed for monorepos that don't have git repositories initialized in the child directories (and Docker environments)

### Actual Result

fatal: not a git repository (or any of the parent directories): .git - is logged to the console

**Comment by chargome** [comment]
@ethanlaj thanks for raising this, will be out with the next release
