### ISSUE TITLE
Add an Option to Delete Sourcemaps Regardless of Upload Result

### ISSUE THREAD

**Issue by alizadeh118** [getsentry/sentry-javascript-bundler-plugins#630]
I'm using `SentryWebpackPlugin` to upload sourcemaps to Sentry and then delete them to avoid exposing sourcemaps in production. My Webpack configuration includes `devtool: 'source-map'` and the `sourcemaps.filesToDeleteAfterUpload` option.

To prevent CI/CD pipeline failures, I've overridden the `errorHandler` to log errors without breaking the process. However, when the plugin encounters an error during the upload process, the sourcemaps are not deleted since the plugin does not complete its task. This results in sourcemaps being exposed in production.

Feature Request: It would be great to have an option (or behavior similar to `.finally` in JavaScript promises) to ensure that sourcemaps are deleted after the process, regardless of whether the upload succeeds or fails.

This would provide a failsafe cleanup mechanism and prevent accidental exposure of sourcemaps in production environments.

Thank you.

**Comment by lforst** [comment]
That's a very valid point. I think we should always delete when `filesToDeleteAfterUpload` is set - no matter what.

**Comment by lforst** [comment]
Actually, this should already be happening. What version of the plugin are you using?

**Comment by alizadeh118** [comment]
My mistake!
I checked again, and you're absolutely right. It deletes the source maps regardless.
Apologies, and thank you!
