### ISSUE TITLE
Release names don't make sense?

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-javascript-bundler-plugins#634]
I have a SvelteKit website, using `@sentry/sveltekit` and thus its Vite plugin as well.

This is my `vite.config.js`:

```
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig, loadEnv } from "vite";
import { sentrySvelteKit } from "@sentry/sveltekit";

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "");

  return {
    plugins: [
      sentrySvelteKit({
        sourceMapsUploadOptions: {
          org: "xx",
          project: "xx",
          telemetry: false,
          authToken: env.SENTRY_AUTH_TOKEN,
        },
      }),
      sveltekit(),
    ],
    build: {
      sourcemap: true,
      target: "es2015",
    },
    server: {
      proxy: {
        "/sitemap.xml": env.PUBLIC_API_URL || "",
        "/accounts/sso": env.PUBLIC_API_URL || "",
      },
    },
    test: {
      include: ["src/**/*.{test,spec}.{js,ts}"],
    },
  };
});
```

I use `adapter-node`, the site is running on a Hetzner VPS, and is checked out via Git. The problem is that issues get assigned to releases which make no sense. For example `Last Seen a day ago in release b9397c217320`. There is no commit with such a SHA, so I don't know where this is coming from? When I click on the release name, there are no commits, no files changed:

![Image](https://github.com/user-attachments/assets/a733699e-7b04-4b92-9d4c-6eab9841f28f)

When I look at the docs (https://www.npmjs.com/package/@sentry/vite-plugin/v/2.14.2#release), it makes it seem that the release name should automatically be set to the commit SHA, but when I run `git rev-parse HEAD`, in my repo, there is no release with this SHA. Also `release.setCommits.previousCommit` says "Defaults to the last commit of the previous release in Sentry." So why am I not seeing this in any release?

**Comment by lforst** [comment]
A few things:

- The logic in the bundler plugins to automatically determine a release name is here: https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/514055a1dbcf80cf4ca60967b233696e50e0b11d/packages/bundler-plugin-core/src/utils.ts#L212
- If you feel like you're getting spammed by releases you can disable release creation in the plugin.
- Sentry creates releases also when an event is ingested that has a release value. In case you have a frontend project (which I assume since this is svelte), it's possible that some browser extension or similar is leaking into your Sentry instance.

**Comment by kevinrenskers** [comment]
I don't really understand what you're saying. My issue is that Sentry is creating release names which don't seem to correspond to git commits, and the releases don't have any commits or changed files or anything like that.

I don't feel I'm getting spammed by releases, it's just that the release names are not helpful to figure out where an issue was introduced. How does disabling release creation help?

**Comment by s1gr1d** [comment]
You might get the fallback string which is defined in the SDK code here: https://github.com/getsentry/sentry-javascript/blob/7e78d67de327884f712447167280b9e1419d5187/packages/sveltekit/src/vite/sourceMaps.ts#L280

Somehow, the SDK cannot parse the git head in your project. Can you provide a minimal reproduction?

**Comment by lforst** [comment]
The reason why my comment was a bit vague because I have no insight into your deployment process. It's possible your release pipeline creates a commit for whatever reason and never pushes it. It's possible that you have some environment variable configured that gets picked up as a release value. That's the reason I pointed you to the code determining what is used as release.

We make no guarantees that the automatic release names are deterministic nor that they will be equal your git SHAs. We simply use best-effort heuristics to generate release names that will make sense for people in most cases.

If you want releases to have a particular name, use the `release` option. Currently, I have no reason to believe the plugin is faulty - we are simply lacking insight into your deployiment setup.

**Comment by kevinrenskers** [comment]
When I push the main branch to the server, a build is created. No new commit is created, the git status is always clean on the server. We don't set any environment variables other than `SENTRY_AUTH_TOKEN`.

Looking at https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/514055a1dbcf80cf4ca60967b233696e50e0b11d/packages/bundler-plugin-core/src/utils.ts#L212, it should always end up with the value of `gitRevision()` since none of the ENV variables should be set.

I'll add some logging to this `utils` file and see what's happening with my builds.

**Comment by lforst** [comment]
@kevinrenskers you may actually run into the fallback case already shared by @s1gr1d in this thread: https://github.com/getsentry/sentry-javascript/blob/7e78d67de327884f712447167280b9e1419d5187/packages/sveltekit/src/vite/sourceMaps.ts#L280

Here we generate a uuid (without dashes).

I recommend making sure that git is available and ready to be executed on your machine, or you can also just pass in whatever release value you like as `release` option. There you can have your own logic to grab the SHA.

**Comment by kevinrenskers** [comment]
Right, but why is it using the fallback? Why wouldn't git be "available and ready to be executed" on my machine?

Repro steps, on macOS:

1. Create a brand new SvelteKit app using `pnpx sv create myapp`, choosing "SvelteKit minimal" with TS syntax and no other additions
2. Inside the new folder I ran `@sentry/wizard@latest -I sveltekit`, and I connected to a Sentry project
3. Ran `git init && git add -A && git commit -m "Initial commit"`
4. Ran `git rev-parse HEAD`, made note of the SHA
5. Ran `pnpm build` and saw a release with a different name

**Comment by kevinrenskers** [comment]
So when I run `git rev-parse HEAD` on the command line I get a SHA value just fine. However when I run `console.log(child_process.execSync('git rev-parse HEAD', { stdio: 'ignore' }));` in Node I get `null`. So yeah it's using the fallback value.

Not sure why this is happening.

**Comment by kevinrenskers** [comment]
Found it. It's the `{ stdio: 'ignore' }` part that messes things up.

`console.log(child_process.execSync('git rev-parse HEAD').toString());` gives a result
`console.log(child_process.execSync('git rev-parse HEAD', { stdio: 'ignore' }).toString());` does not

**Comment by lforst** [comment]
Just found the same thing. Will fix! Thanks for the help here!

**Comment by kevinrenskers** [comment]
Great! One question I am left with: why there are seemingly two different ways to determine the release name? There's `determineReleaseName()` in `utils.ts`, which uses a bunch of ENV variables, and falls back to git using `childProcess.execSync("git rev-parse HEAD", { stdio: ["ignore", "pipe", "ignore"] }).toString().trim()` (which I guess also doesn't work!), and we have `detectSentryRelease()` in `sourceMaps.ts` which only checks git and falls back to uuid. Won't this always result in different release names when somebody does use those ENV variables?
