### ISSUE TITLE
Vite plugin gives release/sourcemap warnings in developer mode

### ISSUE THREAD

**Issue by memcorrupt** [getsentry/sentry-javascript-bundler-plugins#635]
### Environment

"@sentry/vite-plugin": "^2.22.6"

### Steps to Reproduce

`vite dev`

### Expected Result

Should not attempt to upload sourcemaps and create release in dev mode.

### Actual Result

```
> vite dev

[sentry-vite-plugin] Warning: No auth token provided. Will not create release. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[sentry-vite-plugin] Warning: No auth token provided. Will not upload source maps. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
```

**Comment by lforst** [comment]
Dev mode is actually not reliable to detect sometimes. As a workaround you can either set `disable: true` in devmode or not add the plugin at all.

**Comment by andreiborza** [comment]
Closing this issue for cleanup, if you find this didn't help don't hesitate to re-open @memcorrupt.

**Comment by lforst** [comment]
Duplicate of https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/344
