### ISSUE TITLE
Stack frame path doesn't match a source file artifact name

### ISSUE THREAD

**Issue by GMartigny** [getsentry/sentry-javascript-bundler-plugins#640]
Hi,

I'm trying to setup "unminifying code" on Sentry.io errors reports. I'm a Nuxt application, so I used the [@nuxtjs/sentry](https://github.com/nuxt-community/sentry-module) configuration. This worked well to create and upload source-maps.

However, on Sentry, errors show up with id like `~/_nuxt/41db8b4.js` which match the build logs generated by nuxt : `41db8b4.js     363 KiB           5  [emitted] [immutable]  [big]  commons/app`.

![Image](https://github.com/user-attachments/assets/3feef3c7-9801-4087-b088-0aa5d9b47580)

But the module logs show completly different looking ids, ex: `~/024cc788-e0dd-460e-a8b2-1d698a0ffe62-31.js (sourcemap at 024cc788-e0dd-460e-a8b2-1d698a0ffe62-31.js.map, debug id 024cc788-e0dd-460e-a8b2-1d698a0ffe62)`

The artifact indeed doesn't have a `dist` value.

> Found 144 files
> Analyzing 144 sources
> Adding source map references
> Bundled 144 files for upload
> Bundle ID: d9400af2-6ee7-524a-851a-c66a2875e49a
> Uploaded files to Sentry
> File upload complete (processing pending on server)
> Organization: my-org-name
> Project: my-project
> Release: 017745e8d455c27e6aa05199a96ba984d29fd401
> Dist: None
> Upload type: artifact bundle

`nuxt.config.js` :
```js
sentry: {
  dsn: process.env.SENTRY_DSN,
  disabled: base.env.IS_DEV,
  tracing: true,
  config: {
    environment: process.env.SENTRY_ENV,
    sampleRate: +process.env.SENTRY_SAMPLE_RATE || 1,
  },
  publishRelease: {
    authToken: process.env.SENTRY_AUTH_TOKEN,
    org: 'my-org-name',
    project: 'my-project',
    release: {
      setCommits: {
        auto: true,
      },
    },
  },
},
```
@nuxtjs/sentry@8.0.8
@sentry/webpack-plugin@2.22.7

I saw #633, but my @sentry/cli is at the latest version 2.39.1

Am I doing something wrong ?

**Comment by s1gr1d** [comment]
Hello, are you using Nuxt 2? `@nuxtjs/sentry` is a community-based library which is only available for Nuxt 2 (which is end of life). If you have issues with this library, please open an issue in their repository.

If you are using Nuxt 3+, you can use our official `@sentry/nuxt` SDK: https://docs.sentry.io/platforms/javascript/guides/nuxt/
This SDK automatically includes the bundler plugins.

**Comment by GMartigny** [comment]
I'm using Nuxt@2.16.3 to be exact. The plugin works as expected, generating source-maps and uploading them to Sentry. My issue here seems to be that the `@sentry/webpack-plugin` doesn't use the correct ids for each chunks.

**Comment by lforst** [comment]
@GMartigny would you mind sharing a minimal reproduction of your setup? It's super hard to debug these kinds of issues when we lack in-depth details about the build configs.

**Comment by GMartigny** [comment]
I didn't manage to reproduce using a minimal repo. So, I cleared out all my previous errors in Sentry, made a new build and started fresh. Now, errors are correctly "unminified".

Looks like Sentry is having trouble "unmifying" when error are paired with previously raised errors.

Sorry for taking your time.
